import type { Fact } from "@/types";

export const facts: Fact[] = [
  {
    id: 1,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 2,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 3,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 4,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 5,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 6,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 7,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 8,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 9,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 10,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 11,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 12,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 13,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 14,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 15,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 16,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 17,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 18,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 19,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 20,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 21,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 22,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 23,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 24,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 25,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 26,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 27,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 28,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 29,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 30,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 31,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 32,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 33,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 34,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 35,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 36,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 37,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 38,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 39,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 40,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 41,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 42,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 43,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 44,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 45,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 46,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 47,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 48,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 49,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 50,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 51,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 52,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 53,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 54,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 55,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 56,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 57,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 58,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 59,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 60,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 61,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 62,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 63,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 64,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 65,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 66,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 67,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 68,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 69,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 70,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 71,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 72,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 73,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 74,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 75,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 76,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 77,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 78,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 79,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 80,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 81,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 82,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 83,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 84,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 85,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 86,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 87,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 88,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 89,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 90,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 91,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 92,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 93,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 94,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 95,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 96,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 97,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 98,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 99,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 100,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 101,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 102,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 103,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 104,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 105,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 106,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 107,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 108,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 109,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 110,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 111,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 112,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 113,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 114,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 115,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 116,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 117,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 118,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 119,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 120,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 121,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 122,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 123,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 124,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 125,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 126,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 127,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 128,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 129,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 130,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 131,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 132,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 133,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 134,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 135,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 136,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 137,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 138,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 139,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 140,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 141,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 142,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 143,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 144,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 145,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 146,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 147,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 148,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 149,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 150,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 151,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 152,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 153,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 154,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 155,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 156,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 157,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 158,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 159,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 160,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 161,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 162,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 163,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 164,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 165,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 166,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 167,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 168,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 169,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 170,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 171,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 172,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 173,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 174,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 175,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 176,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 177,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 178,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 179,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 180,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 181,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 182,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 183,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 184,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 185,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 186,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 187,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 188,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 189,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 190,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
  {
    id: 191,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["fruit", "biology", "weird"],
    isVerified: true,
  },
  {
    id: 192,
    fact: "Sharks existed before trees.",
    category: "Science",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["sharks", "evolution", "ancient"],
    isVerified: true,
  },
  {
    id: 193,
    fact: "The Eiffel Tower can be 15 cm taller during hot days.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["eiffel", "expansion", "heat"],
    isVerified: true,
  },
  {
    id: 194,
    fact: "Octopuses have three hearts.",
    category: "Animals",
    funLevel: 4,
    source: "NOAA",
    tags: ["octopus", "hearts", "marine"],
    isVerified: true,
  },
  {
    id: 195,
    fact: "The Great Wall of China is not visible from space with the naked eye.",
    category: "History",
    funLevel: 2,
    source: "NASA",
    tags: ["great wall", "china", "myth"],
    isVerified: true,
  },
  {
    id: 196,
    fact: "Honey never spoils; archaeologists found 3000-year-old edible honey.",
    category: "Nature",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["honey", "ancient", "food"],
    isVerified: true,
  },
  {
    id: 197,
    fact: "There are more stars in the universe than grains of sand on Earth.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "universe", "cosmos"],
    isVerified: true,
  },
  {
    id: 198,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["wombat", "poop", "weird"],
    isVerified: true,
  },
  {
    id: 199,
    fact: "The first computer bug was an actual moth found in a computer in 1947.",
    category: "Technology",
    funLevel: 5,
    source: "Computer History Museum",
    tags: ["bug", "moth", "computers"],
    isVerified: true,
  },
  {
    id: 200,
    fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "History.com",
    tags: ["cleopatra", "moon landing", "pyramids"],
    isVerified: true,
  },
];
