import type { Quote } from "@/types";

export const quotes: Quote[] = [
  {
    id: 1,
    content: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Passion",
    tags: ["work", "love", "passion"],
    popularity: 4.9,
  },
  {
    id: 2,
    content: "The unexamined life is not worth living.",
    author: "Socrates",
    category: "Wisdom",
    tags: ["life", "philosophy", "wisdom"],
    popularity: 4.7,
  },
  {
    id: 3,
    content: "That which does not kill us makes us stronger.",
    author: "Friedrich Nietzsche",
    category: "Strength",
    tags: ["adversity", "strength"],
    popularity: 4.8,
  },
  {
    id: 4,
    content: "I think, therefore I am.",
    author: "René Descartes",
    category: "Philosophy",
    tags: ["existence", "thinking"],
    popularity: 4.5,
  },
  {
    id: 5,
    content:
      "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    author: "Ralph Waldo Emerson",
    category: "Individuality",
    tags: ["authenticity", "self"],
    popularity: 4.9,
  },
  {
    id: 6,
    content: "The journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    category: "Perseverance",
    tags: ["journey", "beginnings"],
    popularity: 5.0,
  },
  {
    id: 7,
    content: "He who has a why to live can bear almost any how.",
    author: "Friedrich Nietzsche",
    category: "Purpose",
    tags: ["purpose", "life", "meaning"],
    popularity: 4.6,
  },
  {
    id: 8,
    content: "You must be the change you wish to see in the world.",
    author: "Mahatma Gandhi",
    category: "Change",
    tags: ["action", "change", "inspiration"],
    popularity: 5.0,
  },
  {
    id: 9,
    content:
      "In three words I can sum up everything I've learned about life: it goes on.",
    author: "Robert Frost",
    category: "Life",
    tags: ["life", "resilience"],
    popularity: 4.7,
  },
  {
    id: 10,
    content: "The only thing we have to fear is fear itself.",
    author: "Franklin D. Roosevelt",
    category: "Courage",
    tags: ["fear", "courage"],
    popularity: 4.8,
  },
  {
    id: 11,
    content:
      "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Resilience",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 12,
    content: "What we think, we become.",
    author: "Buddha",
    category: "Mindset",
    tags: ["thoughts", "mindset"],
    popularity: 4.6,
  },
  {
    id: 13,
    content: "Strive not to be a success, but rather to be of value.",
    author: "Albert Einstein",
    category: "Value",
    tags: ["success", "value", "purpose"],
    popularity: 4.7,
  },
  {
    id: 14,
    content: "The best way to predict the future is to create it.",
    author: "Peter Drucker",
    category: "Action",
    tags: ["future", "creation"],
    popularity: 4.5,
  },
  {
    id: 15,
    content:
      "Genius is one percent inspiration and ninety-nine percent perspiration.",
    author: "Thomas Edison",
    category: "Work",
    tags: ["hardwork", "genius", "inspiration"],
    popularity: 4.8,
  },
  {
    id: 16,
    content: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    category: "Humility",
    tags: ["wisdom", "knowledge", "humility"],
    popularity: 4.7,
  },
  {
    id: 17,
    content: "An eye for an eye will only make the whole world blind.",
    author: "Mahatma Gandhi",
    category: "Peace",
    tags: ["peace", "revenge"],
    popularity: 4.6,
  },
  {
    id: 18,
    content:
      "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    author: "Aristotle",
    category: "Excellence",
    tags: ["habits", "excellence"],
    popularity: 4.9,
  },
  {
    id: 19,
    content: "Imagination is more important than knowledge.",
    author: "Albert Einstein",
    category: "Creativity",
    tags: ["imagination", "knowledge"],
    popularity: 4.8,
  },
  {
    id: 20,
    content: "Not all those who wander are lost.",
    author: "J.R.R. Tolkien",
    category: "Exploration",
    tags: ["travel", "purpose"],
    popularity: 5.0,
  },
  {
    id: 21,
    content:
      "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    category: "Perseverance",
    tags: ["resilience", "failure"],
    popularity: 4.9,
  },
  {
    id: 22,
    content:
      "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
    author: "Charles Darwin",
    category: "Adaptability",
    tags: ["change", "survival"],
    popularity: 4.7,
  },
  {
    id: 23,
    content: "The purpose of our lives is to be happy.",
    author: "Dalai Lama",
    category: "Happiness",
    tags: ["happiness", "purpose"],
    popularity: 4.6,
  },
  {
    id: 24,
    content: "Get busy living or get busy dying.",
    author: "Stephen King",
    category: "Life",
    tags: ["life", "action"],
    popularity: 4.8,
  },
  {
    id: 25,
    content:
      "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
    author: "Dr. Seuss",
    category: "Potential",
    tags: ["choice", "potential"],
    popularity: 4.7,
  },
  {
    id: 26,
    content: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    category: "Life",
    tags: ["life", "plans"],
    popularity: 4.9,
  },
  {
    id: 27,
    content:
      "When you reach the end of your rope, tie a knot in it and hang on.",
    author: "Franklin D. Roosevelt",
    category: "Endurance",
    tags: ["perseverance", "hope"],
    popularity: 4.5,
  },
  {
    id: 28,
    content:
      "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    category: "Dreams",
    tags: ["dreams", "future", "belief"],
    popularity: 4.8,
  },
  {
    id: 29,
    content:
      "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    author: "Benjamin Franklin",
    category: "Learning",
    tags: ["education", "learning"],
    popularity: 4.7,
  },
  {
    id: 30,
    content:
      "It is during our darkest moments that we must focus to see the light.",
    author: "Aristotle",
    category: "Hope",
    tags: ["hope", "adversity"],
    popularity: 4.6,
  },
  {
    id: 31,
    content: "Whoever is happy will make others happy too.",
    author: "Anne Frank",
    category: "Happiness",
    tags: ["happiness", "kindness"],
    popularity: 4.5,
  },
  {
    id: 32,
    content:
      "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    author: "Ralph Waldo Emerson",
    category: "Innovation",
    tags: ["leadership", "originality"],
    popularity: 4.8,
  },
  {
    id: 33,
    content:
      "You will face many defeats in life, but never let yourself be defeated.",
    author: "Maya Angelou",
    category: "Resilience",
    tags: ["defeat", "resilience"],
    popularity: 4.7,
  },
  {
    id: 34,
    content: "The greatest wealth is to live content with little.",
    author: "Plato",
    category: "Simplicity",
    tags: ["contentment", "wealth"],
    popularity: 4.3,
  },
  {
    id: 35,
    content:
      "In the end, it's not the years in your life that count. It's the life in your years.",
    author: "Abraham Lincoln",
    category: "Life",
    tags: ["life", "meaning"],
    popularity: 4.9,
  },
  {
    id: 36,
    content: "Life is either a daring adventure or nothing at all.",
    author: "Helen Keller",
    category: "Adventure",
    tags: ["adventure", "life"],
    popularity: 4.7,
  },
  {
    id: 37,
    content:
      "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    author: "Thomas A. Edison",
    category: "Perseverance",
    tags: ["failure", "perseverance"],
    popularity: 4.6,
  },
  {
    id: 38,
    content:
      "You have power over your mind - not outside events. Realize this, and you will find strength.",
    author: "Marcus Aurelius",
    category: "Mindfulness",
    tags: ["mind", "strength", "stoicism"],
    popularity: 4.8,
  },
  {
    id: 39,
    content:
      "If you want to live a happy life, tie it to a goal, not to people or things.",
    author: "Albert Einstein",
    category: "Purpose",
    tags: ["happiness", "goals"],
    popularity: 4.7,
  },
  {
    id: 40,
    content:
      "Never let the fear of striking out keep you from playing the game.",
    author: "Babe Ruth",
    category: "Courage",
    tags: ["risk", "fear"],
    popularity: 4.6,
  },
  {
    id: 41,
    content:
      "Money and success don’t change people; they merely amplify what is already there.",
    author: "Will Smith",
    category: "Character",
    tags: ["character", "success"],
    popularity: 4.2,
  },
  {
    id: 42,
    content:
      "Your time is limited, so don't waste it living someone else's life.",
    author: "Steve Jobs",
    category: "Authenticity",
    tags: ["time", "life"],
    popularity: 4.9,
  },
  {
    id: 43,
    content: "Not how long, but how well you have lived is the main thing.",
    author: "Seneca",
    category: "Life",
    tags: ["life", "quality"],
    popularity: 4.4,
  },
  {
    id: 44,
    content:
      "If life were predictable it would cease to be life, and be without flavor.",
    author: "Eleanor Roosevelt",
    category: "Adventure",
    tags: ["life", "unpredictability"],
    popularity: 4.3,
  },
  {
    id: 45,
    content:
      "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.",
    author: "Henry Ford",
    category: "Destiny",
    tags: ["destiny", "purpose"],
    popularity: 4.5,
  },
  {
    id: 46,
    content:
      "To live is the rarest thing in the world. Most people exist, that is all.",
    author: "Oscar Wilde",
    category: "Living",
    tags: ["life", "existence"],
    popularity: 4.8,
  },
  {
    id: 47,
    content: "That it will never come again is what makes life so sweet.",
    author: "Emily Dickinson",
    category: "Appreciation",
    tags: ["life", "time"],
    popularity: 4.3,
  },
  {
    id: 48,
    content: "It is never too late to be what you might have been.",
    author: "George Eliot",
    category: "Potential",
    tags: ["change", "potential"],
    popularity: 4.7,
  },
  {
    id: 49,
    content: "To be wronged is nothing, unless you continue to remember it.",
    author: "Confucius",
    category: "Forgiveness",
    tags: ["forgiveness", "mindset"],
    popularity: 4.2,
  },
  {
    id: 50,
    content: "Pain is inevitable. Suffering is optional.",
    author: "Haruki Murakami",
    category: "Mindset",
    tags: ["pain", "suffering"],
    popularity: 4.6,
  },
  {
    id: 51,
    content: "All that we are is the result of what we have thought.",
    author: "Buddha",
    category: "Mind",
    tags: ["mind", "thoughts"],
    popularity: 4.5,
  },
  {
    id: 52,
    content: "I have not failed. I've just found 10,000 ways that won't work.",
    author: "Thomas A. Edison",
    category: "Perspective",
    tags: ["failure", "perspective"],
    popularity: 4.8,
  },
  {
    id: 53,
    content: "A man who stands for nothing will fall for anything.",
    author: "Malcolm X",
    category: "Conviction",
    tags: ["principles", "conviction"],
    popularity: 4.6,
  },
  {
    id: 54,
    content: "Be kind, for everyone you meet is fighting a hard battle.",
    author: "Plato",
    category: "Kindness",
    tags: ["kindness", "empathy"],
    popularity: 4.8,
  },
  {
    id: 55,
    content: "Let the beauty of what you love be what you do.",
    author: "Rumi",
    category: "Passion",
    tags: ["love", "passion", "work"],
    popularity: 4.7,
  },
  {
    id: 56,
    content: "The only impossible journey is the one you never begin.",
    author: "Tony Robbins",
    category: "Action",
    tags: ["beginnings", "action"],
    popularity: 4.4,
  },
  {
    id: 57,
    content: "The mind is everything. What you think you become.",
    author: "Buddha",
    category: "Mindset",
    tags: ["mind", "thoughts", "reality"],
    popularity: 4.9,
  },
  {
    id: 58,
    content:
      "We can't solve problems by using the same kind of thinking we used when we created them.",
    author: "Albert Einstein",
    category: "Innovation",
    tags: ["thinking", "problems"],
    popularity: 4.8,
  },
  {
    id: 59,
    content: "Everything you can imagine is real.",
    author: "Pablo Picasso",
    category: "Imagination",
    tags: ["imagination", "creativity"],
    popularity: 4.7,
  },
  {
    id: 60,
    content:
      "There is no greater agony than bearing an untold story inside you.",
    author: "Maya Angelou",
    category: "Expression",
    tags: ["storytelling", "expression"],
    popularity: 4.6,
  },
  {
    id: 61,
    content: "What's done is done.",
    author: "William Shakespeare",
    category: "Acceptance",
    tags: ["past", "acceptance"],
    popularity: 4.1,
  },
  {
    id: 62,
    content: "When words are both true and kind, they can change the world.",
    author: "Buddha",
    category: "Kindness",
    tags: ["words", "kindness"],
    popularity: 4.3,
  },
  {
    id: 63,
    content: "A day without laughter is a day wasted.",
    author: "Charlie Chaplin",
    category: "Joy",
    tags: ["laughter", "joy"],
    popularity: 4.6,
  },
  {
    id: 64,
    content: "Simplicity is the ultimate sophistication.",
    author: "Leonardo da Vinci",
    category: "Simplicity",
    tags: ["simplicity", "elegance"],
    popularity: 4.7,
  },
  {
    id: 65,
    content: "It is not what you look at that matters, it is what you see.",
    author: "Henry David Thoreau",
    category: "Perspective",
    tags: ["perspective", "seeing"],
    popularity: 4.5,
  },
  {
    id: 66,
    content: "Do one thing every day that scares you.",
    author: "Eleanor Roosevelt",
    category: "Courage",
    tags: ["fear", "courage", "growth"],
    popularity: 4.8,
  },
  {
    id: 67,
    content:
      "You can't use up creativity. The more you use, the more you have.",
    author: "Maya Angelou",
    category: "Creativity",
    tags: ["creativity", "art"],
    popularity: 4.6,
  },
  {
    id: 68,
    content: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    category: "Action",
    tags: ["action", "motivation"],
    popularity: 4.7,
  },
  {
    id: 69,
    content: "Fall seven times, stand up eight.",
    author: "Japanese Proverb",
    category: "Resilience",
    tags: ["perseverance", "resilience"],
    popularity: 4.9,
  },
  {
    id: 70,
    content: "The best revenge is massive success.",
    author: "Frank Sinatra",
    category: "Success",
    tags: ["success", "revenge"],
    popularity: 4.4,
  },
  {
    id: 71,
    content: "Whether you think you can or you think you can't, you're right.",
    author: "Henry Ford",
    category: "Belief",
    tags: ["belief", "mindset"],
    popularity: 4.9,
  },
  {
    id: 72,
    content:
      "I am not a product of my circumstances. I am a product of my decisions.",
    author: "Stephen Covey",
    category: "Choice",
    tags: ["choice", "responsibility"],
    popularity: 4.7,
  },
  {
    id: 73,
    content:
      "The question isn't who is going to let me; it's who is going to stop me.",
    author: "Ayn Rand",
    category: "Ambition",
    tags: ["ambition", "determination"],
    popularity: 4.5,
  },
  {
    id: 74,
    content: "You miss 100% of the shots you don't take.",
    author: "Wayne Gretzky",
    category: "Risk",
    tags: ["opportunity", "risk"],
    popularity: 5.0,
  },
  {
    id: 75,
    content:
      "Build your own dreams, or someone else will hire you to build theirs.",
    author: "Farrah Gray",
    category: "Dreams",
    tags: ["dreams", "ambition"],
    popularity: 4.6,
  },
  {
    id: 76,
    content: "Everything has beauty, but not everyone sees it.",
    author: "Confucius",
    category: "Beauty",
    tags: ["beauty", "perspective"],
    popularity: 4.4,
  },
  {
    id: 77,
    content:
      "The two most important days in your life are the day you are born and the day you find out why.",
    author: "Mark Twain",
    category: "Purpose",
    tags: ["purpose", "life", "meaning"],
    popularity: 4.9,
  },
  {
    id: 78,
    content:
      "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    author: "Zig Ziglar",
    category: "Growth",
    tags: ["growth", "goals"],
    popularity: 4.5,
  },
  {
    id: 79,
    content: "Believe you can and you're halfway there.",
    author: "Theodore Roosevelt",
    category: "Belief",
    tags: ["belief", "confidence"],
    popularity: 4.8,
  },
  {
    id: 80,
    content:
      "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    category: "Doubt",
    tags: ["doubt", "belief", "future"],
    popularity: 4.6,
  },
  {
    id: 81,
    content: "Act as if what you do makes a difference. It does.",
    author: "William James",
    category: "Impact",
    tags: ["action", "impact"],
    popularity: 4.5,
  },
  {
    id: 82,
    content:
      "The successful warrior is the average man, with laser-like focus.",
    author: "Bruce Lee",
    category: "Focus",
    tags: ["focus", "success"],
    popularity: 4.7,
  },
  {
    id: 83,
    content:
      "You can't have a better tomorrow if you're still thinking about yesterday.",
    author: "Charles F. Kettering",
    category: "Present",
    tags: ["past", "future", "present"],
    popularity: 4.3,
  },
  {
    id: 84,
    content:
      "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
    author: "Ayn Rand",
    category: "Motivation",
    tags: ["creativity", "motivation"],
    popularity: 4.1,
  },
  {
    id: 85,
    content:
      "If you are not willing to risk the usual you will have to settle for the ordinary.",
    author: "Jim Rohn",
    category: "Risk",
    tags: ["risk", "success"],
    popularity: 4.5,
  },
  {
    id: 86,
    content:
      "All our dreams can come true, if we have the courage to pursue them.",
    author: "Walt Disney",
    category: "Dreams",
    tags: ["dreams", "courage"],
    popularity: 4.8,
  },
  {
    id: 87,
    content: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Patience",
    tags: ["perseverance", "patience"],
    popularity: 4.7,
  },
  {
    id: 88,
    content:
      "Our lives begin to end the day we become silent about things that matter.",
    author: "Martin Luther King Jr.",
    category: "Justice",
    tags: ["courage", "justice"],
    popularity: 4.9,
  },
  {
    id: 89,
    content:
      "The person who says it cannot be done should not interrupt the person who is doing it.",
    author: "Chinese Proverb",
    category: "Action",
    tags: ["action", "possibility"],
    popularity: 4.6,
  },
  {
    id: 90,
    content:
      "Don't judge each day by the harvest you reap but by the seeds that you plant.",
    author: "Robert Louis Stevenson",
    category: "Effort",
    tags: ["patience", "effort"],
    popularity: 4.7,
  },
  {
    id: 91,
    content:
      "The best time to plant a tree was 20 years ago. The second best time is now.",
    author: "Chinese Proverb",
    category: "Opportunity",
    tags: ["action", "opportunity"],
    popularity: 5.0,
  },
  {
    id: 92,
    content: "If you want to lift yourself up, lift up someone else.",
    author: "Booker T. Washington",
    category: "Kindness",
    tags: ["kindness", "service"],
    popularity: 4.6,
  },
  {
    id: 93,
    content: "I would rather die of passion than of boredom.",
    author: "Vincent van Gogh",
    category: "Passion",
    tags: ["passion", "life"],
    popularity: 4.5,
  },
  {
    id: 94,
    content: "A person who never made a mistake never tried anything new.",
    author: "Albert Einstein",
    category: "Growth",
    tags: ["mistakes", "growth"],
    popularity: 4.8,
  },
  {
    id: 95,
    content: "What you do speaks so loudly that I cannot hear what you say.",
    author: "Ralph Waldo Emerson",
    category: "Action",
    tags: ["actions", "character"],
    popularity: 4.7,
  },
  {
    id: 96,
    content:
      "I have learned over the years that when one's mind is made up, this diminishes fear.",
    author: "Rosa Parks",
    category: "Conviction",
    tags: ["fear", "conviction"],
    popularity: 4.6,
  },
  {
    id: 97,
    content: "If you tell the truth, you don't have to remember anything.",
    author: "Mark Twain",
    category: "Honesty",
    tags: ["truth", "honesty"],
    popularity: 4.8,
  },
  {
    id: 98,
    content: "A friend is someone who knows all about you and still loves you.",
    author: "Elbert Hubbard",
    category: "Friendship",
    tags: ["friendship", "love"],
    popularity: 4.7,
  },
  {
    id: 99,
    content:
      "To know that we know what we know, and to know that we do not know what we do not know, that is true knowledge.",
    author: "Nicolaus Copernicus",
    category: "Knowledge",
    tags: ["knowledge", "wisdom"],
    popularity: 4.3,
  },
  {
    id: 100,
    content: "The only source of knowledge is experience.",
    author: "Albert Einstein",
    category: "Experience",
    tags: ["knowledge", "experience"],
    popularity: 4.6,
  },
  {
    id: 101,
    content:
      "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
    author: "Martin Luther King Jr.",
    category: "Love",
    tags: ["love", "hate", "peace"],
    popularity: 5.0,
  },
  {
    id: 102,
    content:
      "Insanity is doing the same thing over and over again and expecting different results.",
    author: "Albert Einstein",
    category: "Change",
    tags: ["change", "insanity"],
    popularity: 4.9,
  },
  {
    id: 103,
    content:
      "The weak can never forgive. Forgiveness is the attribute of the strong.",
    author: "Mahatma Gandhi",
    category: "Forgiveness",
    tags: ["forgiveness", "strength"],
    popularity: 4.6,
  },
  {
    id: 104,
    content:
      "We must not allow other people’s limited perceptions to define us.",
    author: "Virginia Satir",
    category: "Selfworth",
    tags: ["identity", "selfworth"],
    popularity: 4.2,
  },
  {
    id: 105,
    content:
      "Keep your face always toward the sunshine—and shadows will fall behind you.",
    author: "Walt Whitman",
    category: "Optimism",
    tags: ["optimism", "positivity"],
    popularity: 4.7,
  },
  {
    id: 106,
    content: "The true sign of intelligence is not knowledge but imagination.",
    author: "Albert Einstein",
    category: "Imagination",
    tags: ["intelligence", "imagination"],
    popularity: 4.6,
  },
  {
    id: 107,
    content: "There are no shortcuts to any place worth going.",
    author: "Beverly Sills",
    category: "Effort",
    tags: ["hardwork", "effort"],
    popularity: 4.3,
  },
  {
    id: 108,
    content: "You can't blame gravity for falling in love.",
    author: "Albert Einstein",
    category: "Love",
    tags: ["love", "humor"],
    popularity: 4.4,
  },
  {
    id: 109,
    content:
      "It is not a lack of love, but a lack of friendship that makes unhappy marriages.",
    author: "Friedrich Nietzsche",
    category: "Love",
    tags: ["love", "marriage", "friendship"],
    popularity: 4.3,
  },
  {
    id: 110,
    content: "Love all, trust a few, do wrong to none.",
    author: "William Shakespeare",
    category: "Wisdom",
    tags: ["wisdom", "trust"],
    popularity: 4.7,
  },
  {
    id: 111,
    content: "If you want to be happy, be.",
    author: "Leo Tolstoy",
    category: "Happiness",
    tags: ["happiness", "choice"],
    popularity: 4.6,
  },
  {
    id: 112,
    content: "Courage is grace under pressure.",
    author: "Ernest Hemingway",
    category: "Courage",
    tags: ["courage", "grace"],
    popularity: 4.5,
  },
  {
    id: 113,
    content:
      "The fool doth think he is wise, but the wise man knows himself to be a fool.",
    author: "William Shakespeare",
    category: "Wisdom",
    tags: ["wisdom", "humility"],
    popularity: 4.6,
  },
  {
    id: 114,
    content: "He who is brave is free.",
    author: "Seneca",
    category: "Freedom",
    tags: ["bravery", "freedom"],
    popularity: 4.1,
  },
  {
    id: 115,
    content:
      "The greatest way to live with honor in this world is to be what we pretend to be.",
    author: "Socrates",
    category: "Authenticity",
    tags: ["honesty", "authenticity"],
    popularity: 4.3,
  },
  {
    id: 116,
    content: "Luck is what happens when preparation meets opportunity.",
    author: "Seneca",
    category: "Opportunity",
    tags: ["luck", "preparation"],
    popularity: 4.7,
  },
  {
    id: 117,
    content:
      "Wise men speak because they have something to say; fools because they have to say something.",
    author: "Plato",
    category: "Wisdom",
    tags: ["wisdom", "speaking"],
    popularity: 4.6,
  },
  {
    id: 118,
    content:
      "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
    author: "Aristotle",
    category: "Thinking",
    tags: ["mind", "thinking"],
    popularity: 4.8,
  },
  {
    id: 119,
    content:
      "Education is the most powerful weapon which you can use to change the world.",
    author: "Nelson Mandela",
    category: "Education",
    tags: ["education", "change"],
    popularity: 4.9,
  },
  {
    id: 120,
    content: "The roots of education are bitter, but the fruit is sweet.",
    author: "Aristotle",
    category: "Education",
    tags: ["education", "perseverance"],
    popularity: 4.4,
  },
  {
    id: 121,
    content: "A room without books is like a body without a soul.",
    author: "Marcus Tullius Cicero",
    category: "Reading",
    tags: ["books", "reading"],
    popularity: 4.7,
  },
  {
    id: 122,
    content:
      "A leader is one who knows the way, goes the way, and shows the way.",
    author: "John C. Maxwell",
    category: "Leadership",
    tags: ["leadership", "action"],
    popularity: 4.5,
  },
  {
    id: 123,
    content:
      "To handle yourself, use your head; to handle others, use your heart.",
    author: "Eleanor Roosevelt",
    category: "Leadership",
    tags: ["leadership", "empathy"],
    popularity: 4.6,
  },
  {
    id: 124,
    content:
      "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
    author: "Jimmy Dean",
    category: "Adaptability",
    tags: ["adaptability", "attitude"],
    popularity: 4.5,
  },
  {
    id: 125,
    content:
      "Perfection is not attainable, but if we chase perfection we can catch excellence.",
    author: "Vince Lombardi",
    category: "Excellence",
    tags: ["perfection", "excellence"],
    popularity: 4.6,
  },
  {
    id: 126,
    content:
      "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
    author: "Vince Lombardi",
    category: "Willpower",
    tags: ["success", "willpower"],
    popularity: 4.4,
  },
  {
    id: 127,
    content: "Winning isn't everything, but wanting to win is.",
    author: "Vince Lombardi",
    category: "Motivation",
    tags: ["winning", "motivation"],
    popularity: 4.3,
  },
  {
    id: 128,
    content: "The more I practice, the luckier I get.",
    author: "Gary Player",
    category: "Practice",
    tags: ["practice", "luck"],
    popularity: 4.2,
  },
  {
    id: 129,
    content: "It's hard to beat a person who never gives up.",
    author: "Babe Ruth",
    category: "Perseverance",
    tags: ["perseverance", "determination"],
    popularity: 4.7,
  },
  {
    id: 130,
    content:
      "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.",
    author: "Michael Jordan",
    category: "Failure",
    tags: ["failure", "success"],
    popularity: 5.0,
  },
  {
    id: 131,
    content: "The way to get started is to quit talking and begin doing.",
    author: "Walt Disney",
    category: "Action",
    tags: ["action", "motivation"],
    popularity: 4.6,
  },
  {
    id: 132,
    content:
      "The most difficult thing is the decision to act, the rest is merely tenacity.",
    author: "Amelia Earhart",
    category: "Action",
    tags: ["action", "tenacity"],
    popularity: 4.4,
  },
  {
    id: 133,
    content:
      "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.",
    author: "Steve Jobs",
    category: "Vision",
    tags: ["passion", "vision"],
    popularity: 4.8,
  },
  {
    id: 134,
    content:
      "The only person you are destined to become is the person you decide to be.",
    author: "Ralph Waldo Emerson",
    category: "Destiny",
    tags: ["destiny", "choice"],
    popularity: 4.7,
  },
  {
    id: 135,
    content: "An unexamined life is not worth living.",
    author: "Socrates",
    category: "Wisdom",
    tags: ["self-reflection", "life"],
    popularity: 4.8,
  },
  {
    id: 136,
    content: "Fortune favors the bold.",
    author: "Virgil",
    category: "Courage",
    tags: ["courage", "fortune"],
    popularity: 4.6,
  },
  {
    id: 137,
    content: "Float like a butterfly, sting like a bee.",
    author: "Muhammad Ali",
    category: "Strategy",
    tags: ["strategy", "strength"],
    popularity: 4.7,
  },
  {
    id: 138,
    content: "Nothing is impossible, the word itself says 'I'm possible'!",
    author: "Audrey Hepburn",
    category: "Possibility",
    tags: ["possibility", "optimism"],
    popularity: 4.8,
  },
  {
    id: 139,
    content:
      "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    author: "Helen Keller",
    category: "Love",
    tags: ["love", "beauty", "feeling"],
    popularity: 4.7,
  },
  {
    id: 140,
    content:
      "Tis better to have loved and lost than never to have loved at all.",
    author: "Alfred Lord Tennyson",
    category: "Love",
    tags: ["love", "loss"],
    popularity: 4.6,
  },
  {
    id: 141,
    content:
      "For every minute you are angry you lose sixty seconds of happiness.",
    author: "Ralph Waldo Emerson",
    category: "Happiness",
    tags: ["anger", "happiness"],
    popularity: 4.5,
  },
  {
    id: 142,
    content: "Change your thoughts and you change your world.",
    author: "Norman Vincent Peale",
    category: "Mindset",
    tags: ["thoughts", "change"],
    popularity: 4.6,
  },
  {
    id: 143,
    content:
      "The man who moves a mountain begins by carrying away small stones.",
    author: "Confucius",
    category: "Patience",
    tags: ["patience", "perseverance"],
    popularity: 4.7,
  },
  {
    id: 144,
    content:
      "It is our choices that show what we truly are, far more than our abilities.",
    author: "J.K. Rowling",
    category: "Choice",
    tags: ["choices", "character"],
    popularity: 4.8,
  },
  {
    id: 145,
    content: "The measure of intelligence is the ability to change.",
    author: "Albert Einstein",
    category: "Change",
    tags: ["change", "intelligence"],
    popularity: 4.7,
  },
  {
    id: 146,
    content: "We know what we are, but know not what we may be.",
    author: "William Shakespeare",
    category: "Potential",
    tags: ["potential", "future"],
    popularity: 4.4,
  },
  {
    id: 147,
    content:
      "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.",
    author: "Aristotle",
    category: "Strategy",
    tags: ["goals", "strategy"],
    popularity: 4.3,
  },
  {
    id: 148,
    content:
      "Happiness is not something ready made. It comes from your own actions.",
    author: "Dalai Lama",
    category: "Happiness",
    tags: ["happiness", "action"],
    popularity: 4.7,
  },
  {
    id: 149,
    content:
      "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
    author: "Oprah Winfrey",
    category: "Gratitude",
    tags: ["gratitude", "perspective"],
    popularity: 4.8,
  },
  {
    id: 150,
    content: "Peace begins with a smile.",
    author: "Mother Teresa",
    category: "Peace",
    tags: ["peace", "kindness"],
    popularity: 4.5,
  },
  {
    id: 151,
    content:
      "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Confucius",
    category: "Resilience",
    tags: ["failure", "resilience"],
    popularity: 4.8,
  },
  {
    id: 152,
    content: "Life is really simple, but we insist on making it complicated.",
    author: "Confucius",
    category: "Simplicity",
    tags: ["life", "simplicity"],
    popularity: 4.6,
  },
  {
    id: 153,
    content: "Do what you can, with what you have, where you are.",
    author: "Theodore Roosevelt",
    category: "Action",
    tags: ["action", "resourcefulness"],
    popularity: 4.7,
  },
  {
    id: 154,
    content:
      "You can never cross the ocean until you have the courage to lose sight of the shore.",
    author: "Christopher Columbus",
    category: "Courage",
    tags: ["courage", "risk"],
    popularity: 4.5,
  },
  {
    id: 155,
    content: "I am the master of my fate, I am the captain of my soul.",
    author: "William Ernest Henley",
    category: "Destiny",
    tags: ["destiny", "control"],
    popularity: 4.9,
  },
  {
    id: 156,
    content:
      "Go confidently in the direction of your dreams! Live the life you've imagined.",
    author: "Henry David Thoreau",
    category: "Dreams",
    tags: ["dreams", "confidence"],
    popularity: 4.8,
  },
  {
    id: 157,
    content: "Either you run the day, or the day runs you.",
    author: "Jim Rohn",
    category: "Control",
    tags: ["discipline", "control"],
    popularity: 4.5,
  },
  {
    id: 158,
    content: "Dream big and dare to fail.",
    author: "Norman Vaughan",
    category: "Ambition",
    tags: ["dreams", "failure"],
    popularity: 4.4,
  },
  {
    id: 159,
    content:
      "Too many of us are not living our dreams because we are living our fears.",
    author: "Les Brown",
    category: "Fear",
    tags: ["dreams", "fear"],
    popularity: 4.6,
  },
  {
    id: 160,
    content: "Life is 10% what happens to us and 90% how we react to it.",
    author: "Charles R. Swindoll",
    category: "Attitude",
    tags: ["attitude", "reaction"],
    popularity: 4.8,
  },
  {
    id: 161,
    content: "When I let go of what I am, I become what I might be.",
    author: "Lao Tzu",
    category: "Growth",
    tags: ["growth", "change"],
    popularity: 4.5,
  },
  {
    id: 162,
    content:
      "The most common way people give up their power is by thinking they don't have any.",
    author: "Alice Walker",
    category: "Power",
    tags: ["power", "belief"],
    popularity: 4.4,
  },
  {
    id: 163,
    content:
      "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.",
    author: "John Milton",
    category: "Mind",
    tags: ["mind", "perspective"],
    popularity: 4.3,
  },
  {
    id: 164,
    content: "There is nothing either good or bad, but thinking makes it so.",
    author: "William Shakespeare",
    category: "Perspective",
    tags: ["perspective", "thinking"],
    popularity: 4.6,
  },
  {
    id: 165,
    content: "The best preparation for tomorrow is doing your best today.",
    author: "H. Jackson Brown, Jr.",
    category: "Preparation",
    tags: ["preparation", "effort"],
    popularity: 4.4,
  },
  {
    id: 166,
    content: "What we achieve inwardly will change outer reality.",
    author: "Plutarch",
    category: "Change",
    tags: ["change", "mindset"],
    popularity: 4.2,
  },
  {
    id: 167,
    content: "I am a slow walker, but I never walk back.",
    author: "Abraham Lincoln",
    category: "Perseverance",
    tags: ["perseverance", "progress"],
    popularity: 4.5,
  },
  {
    id: 168,
    content: "The power of imagination makes us infinite.",
    author: "John Muir",
    category: "Imagination",
    tags: ["imagination", "potential"],
    popularity: 4.3,
  },
  {
    id: 169,
    content:
      "Let us sacrifice our today so that our children can have a better tomorrow.",
    author: "A. P. J. Abdul Kalam",
    category: "Sacrifice",
    tags: ["sacrifice", "future"],
    popularity: 4.1,
  },
  {
    id: 170,
    content:
      "If you can't explain it simply, you don't understand it well enough.",
    author: "Albert Einstein",
    category: "Understanding",
    tags: ["simplicity", "understanding"],
    popularity: 4.8,
  },
  {
    id: 171,
    content:
      "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    author: "Ralph Waldo Emerson",
    category: "Potential",
    tags: ["potential", "self"],
    popularity: 4.7,
  },
  {
    id: 172,
    content: "Try to be a rainbow in someone's cloud.",
    author: "Maya Angelou",
    category: "Kindness",
    tags: ["kindness", "hope"],
    popularity: 4.6,
  },
  {
    id: 173,
    content:
      "Be the reason someone smiles. Be the reason someone feels loved and believes in the goodness in people.",
    author: "Roy T. Bennett",
    category: "Kindness",
    tags: ["kindness", "love"],
    popularity: 4.5,
  },
  {
    id: 174,
    content: "No act of kindness, no matter how small, is ever wasted.",
    author: "Aesop",
    category: "Kindness",
    tags: ["kindness", "impact"],
    popularity: 4.7,
  },
  {
    id: 175,
    content:
      "The desire to create is one of the deepest yearnings of the human soul.",
    author: "Dieter F. Uchtdorf",
    category: "Creativity",
    tags: ["creativity", "passion"],
    popularity: 4.1,
  },
  {
    id: 176,
    content: "Creativity is intelligence having fun.",
    author: "Albert Einstein",
    category: "Creativity",
    tags: ["creativity", "intelligence", "fun"],
    popularity: 4.9,
  },
  {
    id: 177,
    content: "To be creative means to be in love with life.",
    author: "Osho",
    category: "Creativity",
    tags: ["creativity", "life"],
    popularity: 4.0,
  },
  {
    id: 178,
    content: "The chief enemy of creativity is good sense.",
    author: "Pablo Picasso",
    category: "Creativity",
    tags: ["creativity", "risk"],
    popularity: 4.3,
  },
  {
    id: 179,
    content:
      "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    author: "Steve Jobs",
    category: "Work",
    tags: ["work", "passion", "satisfaction"],
    popularity: 4.8,
  },
  {
    id: 180,
    content:
      "Choose a job you love, and you will never have to work a day in your life.",
    author: "Confucius",
    category: "Passion",
    tags: ["work", "love"],
    popularity: 4.9,
  },
  {
    id: 181,
    content:
      "A comfort zone is a beautiful place, but nothing ever grows there.",
    author: "Unknown",
    category: "Growth",
    tags: ["growth", "comfort"],
    popularity: 4.6,
  },
  {
    id: 182,
    content: "The bad news is time flies. The good news is you're the pilot.",
    author: "Michael Altshuler",
    category: "Time",
    tags: ["time", "control"],
    popularity: 4.5,
  },
  {
    id: 183,
    content:
      "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    author: "Marcus Aurelius",
    category: "Happiness",
    tags: ["happiness", "mindset"],
    popularity: 4.7,
  },
  {
    id: 184,
    content:
      "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough.",
    author: "Mark Zuckerberg",
    category: "Innovation",
    tags: ["innovation", "risk"],
    popularity: 4.1,
  },
  {
    id: 185,
    content: "I have no special talent. I am only passionately curious.",
    author: "Albert Einstein",
    category: "Curiosity",
    tags: ["curiosity", "learning"],
    popularity: 4.6,
  },
  {
    id: 186,
    content: "Stay hungry, stay foolish.",
    author: "Steve Jobs",
    category: "Ambition",
    tags: ["ambition", "curiosity"],
    popularity: 4.9,
  },
  {
    id: 187,
    content:
      "If you don't build your dream, someone else will hire you to help them build theirs.",
    author: "Dhirubhai Ambani",
    category: "Dreams",
    tags: ["dreams", "ambition"],
    popularity: 4.5,
  },
  {
    id: 188,
    content:
      "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.",
    author: "Mark Caine",
    category: "Success",
    tags: ["success", "change"],
    popularity: 4.3,
  },
  {
    id: 189,
    content:
      "Knowing is not enough; we must apply. Willing is not enough; we must do.",
    author: "Johann Wolfgang von Goethe",
    category: "Action",
    tags: ["action", "knowledge"],
    popularity: 4.6,
  },
  {
    id: 190,
    content:
      "What you lack in talent can be made up with desire, hustle and giving 110% all the time.",
    author: "Don Zimmer",
    category: "Effort",
    tags: ["effort", "hustle"],
    popularity: 4.2,
  },
  {
    id: 191,
    content:
      "The best leaders are those most interested in surrounding themselves with assistants and associates smarter than they are.",
    author: "John C. Maxwell",
    category: "Leadership",
    tags: ["leadership", "teamwork"],
    popularity: 4.1,
  },
  {
    id: 192,
    content:
      "The function of leadership is to produce more leaders, not more followers.",
    author: "Ralph Nader",
    category: "Leadership",
    tags: ["leadership", "growth"],
    popularity: 4.5,
  },
  {
    id: 193,
    content:
      "A genuine leader is not a searcher for consensus but a molder of consensus.",
    author: "Martin Luther King Jr.",
    category: "Leadership",
    tags: ["leadership", "vision"],
    popularity: 4.4,
  },
  {
    id: 194,
    content:
      "Success is stumbling from failure to failure with no loss of enthusiasm.",
    author: "Winston Churchill",
    category: "Success",
    tags: ["success", "failure", "enthusiasm"],
    popularity: 4.8,
  },
  {
    id: 195,
    content: "To improve is to change; to be perfect is to change often.",
    author: "Winston Churchill",
    category: "Change",
    tags: ["change", "improvement"],
    popularity: 4.5,
  },
  {
    id: 196,
    content: "Life shrinks or expands in proportion to one's courage.",
    author: "Anais Nin",
    category: "Courage",
    tags: ["courage", "life"],
    popularity: 4.6,
  },
  {
    id: 197,
    content:
      "If you don't like something, change it. If you can't change it, change your attitude.",
    author: "Maya Angelou",
    category: "Attitude",
    tags: ["change", "attitude"],
    popularity: 4.7,
  },
  {
    id: 198,
    content:
      "We are all in the gutter, but some of us are looking at the stars.",
    author: "Oscar Wilde",
    category: "Optimism",
    tags: ["optimism", "perspective"],
    popularity: 4.8,
  },
  {
    id: 199,
    content: "Every saint has a past, and every sinner has a future.",
    author: "Oscar Wilde",
    category: "Redemption",
    tags: ["forgiveness", "future"],
    popularity: 4.5,
  },
  {
    id: 200,
    content:
      "Logic will get you from A to B. Imagination will take you everywhere.",
    author: "Albert Einstein",
    category: "Imagination",
    tags: ["logic", "imagination"],
    popularity: 4.9,
  },
];
