import type { Quote } from "@/types";

export const quotes:Quote[] =[
  {
    id: 1,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Perseverance",
    tags: ["passion", "work", "love", "dedication"],
    popularity: 4.8,
  },
  {
    id: 2,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["resilience", "failure", "success", "motivation"],
    popularity: 4.9,
  },
  {
    id: 3,
    text: "Believe you can and you're halfway there.",
    author: "Theodore Roosevelt",
    category: "Wisdom",
    tags: ["belief", "confidence", "mindset", "potential"],
    popularity: 4.7,
  },
  {
    id: 4,
    text: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    category: "Happiness",
    tags: ["dreams", "future", "belief", "inspiration"],
    popularity: 4.6,
  },
  {
    id: 5,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["patience", "consistency", "progress"],
    popularity: 4.8,
  },
  {
    id: 6,
    text: "The only limit to our realization of tomorrow is our doubts of today.",
    author: "Franklin D. Roosevelt",
    category: "Leadership",
    tags: ["doubt", "potential", "mindset", "future"],
    popularity: 4.5,
  },
  {
    id: 7,
    text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    author: "Aristotle",
    category: "Discipline",
    tags: ["habits", "excellence", "consistency", "action"],
    popularity: 5.0,
  },
  {
    id: 8,
    text: "The journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    category: "Perseverance",
    tags: ["beginnings", "journey", "action", "patience"],
    popularity: 4.9,
  },
  {
    id: 9,
    text: "Act as if what you do makes a difference. It does.",
    author: "William James",
    category: "Courage",
    tags: ["action", "impact", "purpose", "significance"],
    popularity: 4.4,
  },
  {
    id: 10,
    text: "What you get by achieving your goals is not as important as what you become.",
    author: "Zig Ziglar",
    category: "Wisdom",
    tags: ["growth", "journey", "self-improvement", "goals"],
    popularity: 4.6,
  },
  {
    id: 11,
    text: "Strive not to be a success, but rather to be of value.",
    author: "Albert Einstein",
    category: "Leadership",
    tags: ["value", "purpose", "success", "contribution"],
    popularity: 4.9,
  },
  {
    id: 12,
    text: "Happiness is not something ready made. It comes from your own actions.",
    author: "Dalai Lama",
    category: "Happiness",
    tags: ["action", "choice", "joy", "responsibility"],
    popularity: 4.7,
  },
  {
    id: 13,
    text: "To handle yourself, use your head; to handle others, use your heart.",
    author: "Eleanor Roosevelt",
    category: "Leadership",
    tags: ["empathy", "wisdom", "management", "relationships"],
    popularity: 4.5,
  },
  {
    id: 14,
    text: "The best way to predict the future is to create it.",
    author: "Peter Drucker",
    category: "Courage",
    tags: ["action", "future", "creation", "proactive"],
    popularity: 4.8,
  },
  {
    id: 15,
    text: "Discipline is the bridge between goals and accomplishment.",
    author: "Jim Rohn",
    category: "Discipline",
    tags: ["goals", "success", "focus", "execution"],
    popularity: 5.0,
  },
  {
    id: 16,
    text: "Your time is limited, so don't waste it living someone else's life.",
    author: "Steve Jobs",
    category: "Wisdom",
    tags: ["authenticity", "purpose", "time", "individuality"],
    popularity: 4.8,
  },
  {
    id: 17,
    text: "I have not failed. I've just found 10,000 ways that won't work.",
    author: "Thomas A. Edison",
    category: "Perseverance",
    tags: ["failure", "learning", "resilience", "innovation"],
    popularity: 4.9,
  },
  {
    id: 18,
    text: "If you want to lift yourself up, lift up someone else.",
    author: "Booker T. Washington",
    category: "Happiness",
    tags: ["kindness", "service", "community", "empathy"],
    popularity: 4.6,
  },
  {
    id: 19,
    text: "A leader is one who knows the way, goes the way, and shows the way.",
    author: "John C. Maxwell",
    category: "Leadership",
    tags: ["guidance", "example", "vision", "integrity"],
    popularity: 4.7,
  },
  {
    id: 20,
    text: "The mind is everything. What you think you become.",
    author: "Buddha",
    category: "Wisdom",
    tags: ["mindset", "thoughts", "reality", "manifestation"],
    popularity: 5.0,
  },
  {
    id: 21,
    text: "Either you run the day, or the day runs you.",
    author: "Jim Rohn",
    category: "Discipline",
    tags: ["proactivity", "control", "motivation", "time-management"],
    popularity: 4.7,
  },
  {
    id: 22,
    text: "The brave man is not he who does not feel afraid, but he who conquers that fear.",
    author: "Nelson Mandela",
    category: "Courage",
    tags: ["fear", "bravery", "strength", "overcoming"],
    popularity: 4.9,
  },
  {
    id: 23,
    text: "Fall seven times and stand up eight.",
    author: "Japanese Proverb",
    category: "Perseverance",
    tags: ["resilience", "determination", "never-give-up"],
    popularity: 4.8,
  },
  {
    id: 24,
    text: "For every minute you are angry you lose sixty seconds of happiness.",
    author: "Ralph Waldo Emerson",
    category: "Happiness",
    tags: ["anger", "emotion", "choice", "peace"],
    popularity: 4.5,
  },
  {
    id: 25,
    text: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    category: "Discipline",
    tags: ["action", "procrastination", "beginnings", "motivation"],
    popularity: 4.8,
  },
  {
    id: 26,
    text: "In the middle of difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Wisdom",
    tags: ["opportunity", "challenge", "perspective", "adversity"],
    popularity: 4.7,
  },
  {
    id: 27,
    text: "Management is doing things right; leadership is doing the right things.",
    author: "Peter Drucker",
    category: "Leadership",
    tags: ["vision", "management", "effectiveness", "strategy"],
    popularity: 4.6,
  },
  {
    id: 28,
    text: "You miss 100% of the shots you don't take.",
    author: "Wayne Gretzky",
    category: "Courage",
    tags: ["opportunity", "risk", "action", "regret"],
    popularity: 4.9,
  },
  {
    id: 29,
    text: "The harder the conflict, the more glorious the triumph.",
    author: "Thomas Paine",
    category: "Perseverance",
    tags: ["struggle", "victory", "adversity", "reward"],
    popularity: 4.4,
  },
  {
    id: 30,
    text: "The purpose of our lives is to be happy.",
    author: "Dalai Lama",
    category: "Happiness",
    tags: ["purpose", "life", "joy", "meaning"],
    popularity: 4.6,
  },
  {
    id: 31,
    text: "Motivation is what gets you started. Habit is what keeps you going.",
    author: "Jim Rohn",
    category: "Discipline",
    tags: ["motivation", "habits", "consistency", "long-term"],
    popularity: 4.9,
  },
  {
    id: 32,
    text: "Do not wait to strike till the iron is hot; but make it hot by striking.",
    author: "William Butler Yeats",
    category: "Courage",
    tags: ["initiative", "action", "opportunity", "proactivity"],
    popularity: 4.5,
  },
  {
    id: 33,
    text: "Knowing yourself is the beginning of all wisdom.",
    author: "Aristotle",
    category: "Wisdom",
    tags: ["self-awareness", "knowledge", "introspection", "growth"],
    popularity: 4.8,
  },
  {
    id: 34,
    text: "A genuine leader is not a searcher for consensus but a molder of consensus.",
    author: "Martin Luther King Jr.",
    category: "Leadership",
    tags: ["vision", "influence", "change", "consensus"],
    popularity: 4.7,
  },
  {
    id: 35,
    text: "It is never too late to be what you might have been.",
    author: "George Eliot",
    category: "Perseverance",
    tags: ["potential", "change", "hope", "dreams"],
    popularity: 4.6,
  },
  {
    id: 36,
    text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    category: "Perseverance",
    tags: ["resilience", "failure", "strength", "overcoming"],
    popularity: 5.0,
  },
  {
    id: 37,
    text: "The roots of education are bitter, but the fruit is sweet.",
    author: "Aristotle",
    category: "Discipline",
    tags: ["education", "hard-work", "reward", "learning"],
    popularity: 4.5,
  },
  {
    id: 38,
    text: "If you are working on something that you really care about, you don’t have to be pushed.",
    author: "Steve Jobs",
    category: "Perseverance",
    tags: ["passion", "motivation", "purpose", "drive"],
    popularity: 4.8,
  },
  {
    id: 39,
    text: "The only source of knowledge is experience.",
    author: "Albert Einstein",
    category: "Wisdom",
    tags: ["experience", "learning", "knowledge", "practice"],
    popularity: 4.7,
  },
  {
    id: 40,
    text: "The art of leadership is saying no, not yes. It is very easy to say yes.",
    author: "Tony Blair",
    category: "Leadership",
    tags: ["focus", "decision-making", "priorities", "strategy"],
    popularity: 4.2,
  },
  {
    id: 41,
    text: "Life is 10% what happens to us and 90% how we react to it.",
    author: "Charles R. Swindoll",
    category: "Courage",
    tags: ["attitude", "perspective", "control", "reaction"],
    popularity: 4.8,
  },
  {
    id: 42,
    text: "The foolish man seeks happiness in the distance, the wise grows it under his feet.",
    author: "James Oppenheim",
    category: "Happiness",
    tags: ["presence", "gratitude", "wisdom", "perspective"],
    popularity: 4.5,
  },
  {
    id: 43,
    text: "Without self-discipline, success is impossible, period.",
    author: "Lou Holtz",
    category: "Discipline",
    tags: ["success", "focus", "control", "dedication"],
    popularity: 4.6,
  },
  {
    id: 44,
    text: "If you can dream it, you can do it.",
    author: "Walt Disney",
    category: "Perseverance",
    tags: ["dreams", "imagination", "action", "potential"],
    popularity: 4.7,
  },
  {
    id: 45,
    text: "He who has a why to live can bear almost any how.",
    author: "Friedrich Nietzsche",
    category: "Wisdom",
    tags: ["purpose", "meaning", "resilience", "motivation"],
    popularity: 4.9,
  },
  {
    id: 46,
    text: "Become the leader you would follow.",
    author: "Unknown",
    category: "Leadership",
    tags: ["integrity", "example", "self-reflection", "aspiration"],
    popularity: 4.4,
  },
  {
    id: 47,
    text: "Courage is resistance to fear, mastery of fear – not absence of fear.",
    author: "Mark Twain",
    category: "Courage",
    tags: ["fear", "bravery", "mastery", "strength"],
    popularity: 4.8,
  },
  {
    id: 48,
    text: "Happiness is when what you think, what you say, and what you do are in harmony.",
    author: "Mahatma Gandhi",
    category: "Happiness",
    tags: ["integrity", "harmony", "authenticity", "peace"],
    popularity: 4.9,
  },
  {
    id: 49,
    text: "The successful warrior is the average man, with laser-like focus.",
    author: "Bruce Lee",
    category: "Discipline",
    tags: ["focus", "success", "dedication", "consistency"],
    popularity: 4.8,
  },
  {
    id: 50,
    text: "Perseverance is not a long race; it is many short races one after the other.",
    author: "Walter Elliot",
    category: "Perseverance",
    tags: ["consistency", "patience", "progress", "endurance"],
    popularity: 4.5,
  },
  {
    id: 51,
    text: "The wise man is one who knows what he does not know.",
    author: "Lao Tzu",
    category: "Wisdom",
    tags: ["humility", "knowledge", "learning", "self-awareness"],
    popularity: 4.6,
  },
  {
    id: 52,
    text: "The task of the leader is to get their people from where they are to where they have not been.",
    author: "Henry Kissinger",
    category: "Leadership",
    tags: ["vision", "growth", "potential", "guidance"],
    popularity: 4.3,
  },
  {
    id: 53,
    text: "All our dreams can come true, if we have the courage to pursue them.",
    author: "Walt Disney",
    category: "Courage",
    tags: ["dreams", "action", "pursuit", "ambition"],
    popularity: 4.7,
  },
  {
    id: 54,
    text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.",
    author: "Thich Nhat Hanh",
    category: "Happiness",
    tags: ["mindfulness", "presence", "joy", "gratitude"],
    popularity: 4.8,
  },
  {
    id: 55,
    text: "The first and best victory is to conquer self.",
    author: "Plato",
    category: "Discipline",
    tags: ["self-control", "mastery", "victory", "introspection"],
    popularity: 4.7,
  },
  {
    id: 56,
    text: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    author: "Thomas A. Edison",
    category: "Perseverance",
    tags: ["hard-work", "effort", "genius", "dedication"],
    popularity: 4.9,
  },
  {
    id: 57,
    text: "Turn your wounds into wisdom.",
    author: "Oprah Winfrey",
    category: "Wisdom",
    tags: ["resilience", "growth", "learning", "adversity"],
    popularity: 4.6,
  },
  {
    id: 58,
    text: "The greatest leader is not necessarily the one who does the greatest things.",
    author: "Ronald Reagan",
    category: "Leadership",
    tags: ["empowerment", "humility", "influence", "teamwork"],
    popularity: 4.4,
  },
  {
    id: 59,
    text: "I am not afraid of storms, for I am learning how to sail my ship.",
    author: "Louisa May Alcott",
    category: "Courage",
    tags: ["strength", "learning", "challenge", "self-reliance"],
    popularity: 4.7,
  },
  {
    id: 60,
    text: "True happiness is to enjoy the present, without anxious dependence upon the future.",
    author: "Seneca",
    category: "Happiness",
    tags: ["mindfulness", "stoicism", "presence", "peace"],
    popularity: 4.8,
  },
  {
    id: 61,
    text: "With self-discipline most anything is possible.",
    author: "Theodore Roosevelt",
    category: "Discipline",
    tags: ["potential", "self-control", "achievement", "possibility"],
    popularity: 4.6,
  },
  {
    id: 62,
    text: "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
    author: "Ayn Rand",
    category: "Perseverance",
    tags: ["creativity", "motivation", "achievement", "purpose"],
    popularity: 4.3,
  },
  {
    id: 63,
    text: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    category: "Wisdom",
    tags: ["humility", "knowledge", "philosophy", "learning"],
    popularity: 5.0,
  },
  {
    id: 64,
    text: "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.",
    author: "John Quincy Adams",
    category: "Leadership",
    tags: ["inspiration", "influence", "empowerment", "vision"],
    popularity: 4.9,
  },
  {
    id: 65,
    text: "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["communication", "humility", "wisdom", "bravery"],
    popularity: 4.8,
  },
  {
    id: 66,
    text: "The grand essentials to happiness in this life are something to do, something to love, and something to hope for.",
    author: "Joseph Addison",
    category: "Happiness",
    tags: ["purpose", "love", "hope", "fulfillment"],
    popularity: 4.5,
  },
  {
    id: 67,
    text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.",
    author: "Stephen King",
    category: "Discipline",
    tags: ["action", "work-ethic", "creativity", "consistency"],
    popularity: 4.7,
  },
  {
    id: 68,
    text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
    author: "Thomas A. Edison",
    category: "Perseverance",
    tags: ["resilience", "success", "determination", "never-give-up"],
    popularity: 4.9,
  },
  {
    id: 69,
    text: "The unexamined life is not worth living.",
    author: "Socrates",
    category: "Wisdom",
    tags: ["introspection", "philosophy", "self-awareness", "meaning"],
    popularity: 4.8,
  },
  {
    id: 70,
    text: "Leadership is the capacity to translate vision into reality.",
    author: "Warren Bennis",
    category: "Leadership",
    tags: ["vision", "execution", "action", "achievement"],
    popularity: 4.6,
  },
  {
    id: 71,
    text: "It takes courage to grow up and become who you really are.",
    author: "E.E. Cummings",
    category: "Courage",
    tags: ["authenticity", "growth", "identity", "self-discovery"],
    popularity: 4.5,
  },
  {
    id: 72,
    text: "Happiness is a state of activity.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["action", "purpose", "engagement", "fulfillment"],
    popularity: 4.3,
  },
  {
    id: 73,
    text: "Discipline is choosing between what you want now and what you want most.",
    author: "Abraham Lincoln",
    category: "Discipline",
    tags: ["choice", "goals", "sacrifice", "long-term"],
    popularity: 5.0,
  },
  {
    id: 74,
    text: "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.",
    author: "Samuel Beckett",
    category: "Perseverance",
    tags: ["failure", "resilience", "learning", "improvement"],
    popularity: 4.7,
  },
  {
    id: 75,
    text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
    author: "Rumi",
    category: "Wisdom",
    tags: ["change", "self-improvement", "growth", "perspective"],
    popularity: 4.9,
  },
  {
    id: 76,
    text: "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.",
    author: "Jack Welch",
    category: "Leadership",
    tags: ["growth", "mentorship", "empowerment", "success"],
    popularity: 4.7,
  },
  {
    id: 77,
    text: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying 'I will try again tomorrow.'",
    author: "Mary Anne Radmacher",
    category: "Courage",
    tags: ["resilience", "hope", "quiet-strength", "perseverance"],
    popularity: 4.8,
  },
  {
    id: 78,
    text: "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.",
    author: "Socrates",
    category: "Happiness",
    tags: ["minimalism", "contentment", "gratitude", "simplicity"],
    popularity: 4.6,
  },
  {
    id: 79,
    text: "Talent without discipline is like an octopus on roller skates. There's plenty of movement, but you never know if it's going to be forward, backwards, or sideways.",
    author: "H. Jackson Brown, Jr.",
    category: "Discipline",
    tags: ["talent", "focus", "potential", "direction"],
    popularity: 4.5,
  },
  {
    id: 80,
    text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
    author: "Vince Lombardi",
    category: "Perseverance",
    tags: ["willpower", "determination", "success", "mindset"],
    popularity: 4.7,
  },
  {
    id: 81,
    text: "Count your age by friends, not years. Count your life by smiles, not tears.",
    author: "John Lennon",
    category: "Wisdom",
    tags: ["perspective", "happiness", "relationships", "life"],
    popularity: 4.6,
  },
  {
    id: 82,
    text: "A good leader takes a little more than his share of the blame, a little less than his share of the credit.",
    author: "Arnold H. Glasow",
    category: "Leadership",
    tags: ["humility", "responsibility", "teamwork", "accountability"],
    popularity: 4.5,
  },
  {
    id: 83,
    text: "What would you do if you weren't afraid?",
    author: "Spencer Johnson",
    category: "Courage",
    tags: ["fear", "action", "potential", "opportunity"],
    popularity: 4.7,
  },
  {
    id: 84,
    text: "If you want to be happy, be.",
    author: "Leo Tolstoy",
    category: "Happiness",
    tags: ["choice", "simplicity", "mindset", "decision"],
    popularity: 4.4,
  },
  {
    id: 85,
    text: "Success is the sum of small efforts, repeated day in and day out.",
    author: "Robert Collier",
    category: "Discipline",
    tags: ["consistency", "habits", "success", "effort"],
    popularity: 4.8,
  },
  {
    id: 86,
    text: "Through perseverance many people win success out of what seemed destined to be certain failure.",
    author: "Benjamin Disraeli",
    category: "Perseverance",
    tags: ["success", "failure", "resilience", "opportunity"],
    popularity: 4.3,
  },
  {
    id: 87,
    text: "To attain knowledge, add things every day. To attain wisdom, remove things every day.",
    author: "Lao Tzu",
    category: "Wisdom",
    tags: ["simplicity", "focus", "knowledge", "minimalism"],
    popularity: 4.7,
  },
  {
    id: 88,
    text: "The pessimist complains about the wind. The optimist expects it to change. The leader adjusts the sails.",
    author: "John C. Maxwell",
    category: "Leadership",
    tags: ["adaptability", "proactivity", "problem-solving", "optimism"],
    popularity: 4.9,
  },
  {
    id: 89,
    text: "Life shrinks or expands in proportion to one's courage.",
    author: "Anaïs Nin",
    category: "Courage",
    tags: ["growth", "risk", "life", "expansion"],
    popularity: 4.8,
  },
  {
    id: 90,
    text: "The art of being happy lies in the power of extracting happiness from common things.",
    author: "Henry Ward Beecher",
    category: "Happiness",
    tags: ["gratitude", "perspective", "simplicity", "joy"],
    popularity: 4.5,
  },
  {
    id: 91,
    text: "We must all suffer one of two things: the pain of discipline or the pain of regret or disappointment.",
    author: "Jim Rohn",
    category: "Discipline",
    tags: ["choice", "regret", "consequences", "hard-work"],
    popularity: 4.8,
  },
  {
    id: 92,
    text: "It's not that I'm so smart, it's just that I stay with problems longer.",
    author: "Albert Einstein",
    category: "Perseverance",
    tags: ["problem-solving", "patience", "focus", "determination"],
    popularity: 4.9,
  },
  {
    id: 93,
    text: "The path to wisdom is paved with humility.",
    author: "Unknown",
    category: "Wisdom",
    tags: ["humility", "learning", "growth", "self-awareness"],
    popularity: 4.4,
  },
  {
    id: 94,
    text: "Innovation distinguishes between a leader and a follower.",
    author: "Steve Jobs",
    category: "Leadership",
    tags: ["innovation", "creativity", "vision", "progress"],
    popularity: 4.8,
  },
  {
    id: 95,
    text: "You can't be brave if you've only had wonderful things happen to you.",
    author: "Mary Tyler Moore",
    category: "Courage",
    tags: ["adversity", "strength", "resilience", "character"],
    popularity: 4.3,
  },
  {
    id: 96,
    text: "Joy is a net of love by which you can catch souls.",
    author: "Mother Teresa",
    category: "Happiness",
    tags: ["joy", "love", "connection", "kindness"],
    popularity: 4.6,
  },
  {
    id: 97,
    text: "The more you practice, the luckier you get.",
    author: "Gary Player",
    category: "Discipline",
    tags: ["practice", "luck", "hard-work", "preparation"],
    popularity: 4.5,
  },
  {
    id: 98,
    text: "Failure is the opportunity to begin again more intelligently.",
    author: "Henry Ford",
    category: "Perseverance",
    tags: ["failure", "learning", "opportunity", "improvement"],
    popularity: 4.8,
  },
  {
    id: 99,
    text: "Never mistake knowledge for wisdom. One helps you make a living; the other helps you make a life.",
    author: "Sandra Carey",
    category: "Wisdom",
    tags: ["knowledge", "life", "meaning", "perspective"],
    popularity: 4.6,
  },
  {
    id: 100,
    text: "If you would not be forgotten as soon as you are dead, either write things worth reading or do things worth writing.",
    author: "Benjamin Franklin",
    category: "Leadership",
    tags: ["legacy", "impact", "action", "purpose"],
    popularity: 4.7,
  },
  {
    id: 101,
    text: "It is courage, courage, courage, that raises the blood of life to a splendid crimson.",
    author: "George Bernard Shaw",
    category: "Courage",
    tags: ["bravery", "life", "passion", "vitality"],
    popularity: 4.2,
  },
  {
    id: 102,
    text: "There is only one happiness in this life, to love and be loved.",
    author: "George Sand",
    category: "Happiness",
    tags: ["love", "relationships", "connection", "joy"],
    popularity: 4.7,
  },
  {
    id: 103,
    text: "The future depends on what you do today.",
    author: "Mahatma Gandhi",
    category: "Discipline",
    tags: ["action", "future", "responsibility", "today"],
    popularity: 4.9,
  },
  {
    id: 104,
    text: "Success is walking from failure to failure with no loss of enthusiasm.",
    author: "Winston Churchill",
    category: "Perseverance",
    tags: ["enthusiasm", "resilience", "failure", "optimism"],
    popularity: 5.0,
  },
  {
    id: 105,
    text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
    author: "Aristotle",
    category: "Wisdom",
    tags: ["open-mindedness", "critical-thinking", "intellect", "education"],
    popularity: 4.8,
  },
  {
    id: 106,
    text: "Don't tell people how to do things, tell them what to do and let them surprise you with their results.",
    author: "George S. Patton",
    category: "Leadership",
    tags: ["empowerment", "trust", "delegation", "creativity"],
    popularity: 4.6,
  },
  {
    id: 107,
    text: "He who is brave is free.",
    author: "Seneca",
    category: "Courage",
    tags: ["freedom", "bravery", "stoicism", "liberty"],
    popularity: 4.5,
  },
  {
    id: 108,
    text: "The foolish man seeks happiness in the distance; the wise grows it under his feet.",
    author: "James Oppenheim",
    category: "Happiness",
    tags: ["gratitude", "presence", "wisdom", "mindfulness"],
    popularity: 4.4,
  },
  {
    id: 109,
    text: "Excellence is a continuous process and not an accident.",
    author: "A. P. J. Abdul Kalam",
    category: "Discipline",
    tags: ["excellence", "consistency", "process", "improvement"],
    popularity: 4.7,
  },
  {
    id: 110,
    text: "Defeat is not the worst of failures. Not to have tried is the true failure.",
    author: "George Edward Woodberry",
    category: "Perseverance",
    tags: ["regret", "effort", "failure", "trying"],
    popularity: 4.5,
  },
  {
    id: 111,
    text: "Wisdom begins in wonder.",
    author: "Socrates",
    category: "Wisdom",
    tags: ["curiosity", "wonder", "learning", "philosophy"],
    popularity: 4.6,
  },
  {
    id: 112,
    text: "The quality of a leader is reflected in the standards they set for themselves.",
    author: "Ray Kroc",
    category: "Leadership",
    tags: ["standards", "excellence", "integrity", "example"],
    popularity: 4.5,
  },
  {
    id: 113,
    text: "To dare is to lose one's footing momentarily. To not dare is to lose oneself.",
    author: "Soren Kierkegaard",
    category: "Courage",
    tags: ["risk", "growth", "authenticity", "dare"],
    popularity: 4.7,
  },
  {
    id: 114,
    text: "On a deeper level you are already complete. When you realize that, there is a playful, joyous energy behind what you do.",
    author: "Eckhart Tolle",
    category: "Happiness",
    tags: ["completeness", "joy", "presence", "self-acceptance"],
    popularity: 4.6,
  },
  {
    id: 115,
    text: "Lack of discipline leads to frustration and self-loathing.",
    author: "Unknown",
    category: "Discipline",
    tags: ["consequences", "self-respect", "frustration", "control"],
    popularity: 4.1,
  },
  {
    id: 116,
    text: "A river cuts through rock, not because of its power, but because of its persistence.",
    author: "Jim Watkins",
    category: "Perseverance",
    tags: ["persistence", "consistency", "patience", "long-term"],
    popularity: 4.9,
  },
  {
    id: 117,
    text: "The greatest wealth is to live content with little.",
    author: "Plato",
    category: "Wisdom",
    tags: ["contentment", "minimalism", "wealth", "simplicity"],
    popularity: 4.6,
  },
  {
    id: 118,
    text: "Lead me, follow me, or get out of my way.",
    author: "George S. Patton",
    category: "Leadership",
    tags: ["decisiveness", "action", "clarity", "command"],
    popularity: 4.3,
  },
  {
    id: 119,
    text: "Courage is grace under pressure.",
    author: "Ernest Hemingway",
    category: "Courage",
    tags: ["grace", "pressure", "composure", "strength"],
    popularity: 4.8,
  },
  {
    id: 120,
    text: "Success is getting what you want, happiness is wanting what you get.",
    author: "W. P. Kinsella",
    category: "Happiness",
    tags: ["success", "contentment", "gratitude", "perspective"],
    popularity: 4.7,
  },
  {
    id: 121,
    text: "The secret to success is to start from scratch and keep on scratching.",
    author: "Dennis Green",
    category: "Discipline",
    tags: ["hard-work", "persistence", "beginnings", "effort"],
    popularity: 4.2,
  },
  {
    id: 122,
    text: "The oak fought the wind and was broken, the willow bent when it must and survived.",
    author: "Robert Jordan",
    category: "Perseverance",
    tags: ["adaptability", "flexibility", "resilience", "survival"],
    popularity: 4.5,
  },
  {
    id: 123,
    text: "Let go of who you think you’re supposed to be and embrace who you are.",
    author: "Brené Brown",
    category: "Wisdom",
    tags: ["authenticity", "self-acceptance", "vulnerability", "identity"],
    popularity: 4.8,
  },
  {
    id: 124,
    text: "A leader's job is to look into the future and see the organization, not as it is, but as it can become.",
    author: "Unknown",
    category: "Leadership",
    tags: ["vision", "potential", "future", "growth"],
    popularity: 4.4,
  },
  {
    id: 125,
    text: "Fear is a reaction. Courage is a decision.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["fear", "choice", "decision", "mindset"],
    popularity: 4.7,
  },
  {
    id: 126,
    text: "The key to happiness is to be found in the realization that there is no key.",
    author: "Unknown",
    category: "Happiness",
    tags: ["acceptance", "simplicity", "perspective", "joy"],
    popularity: 4.3,
  },
  {
    id: 127,
    text: "Discipline is the soul of an army. It makes small numbers formidable; procures success to the weak, and esteem to all.",
    author: "George Washington",
    category: "Discipline",
    tags: ["strength", "success", "respect", "organization"],
    popularity: 4.6,
  },
  {
    id: 128,
    text: "Energy and persistence conquer all things.",
    author: "Benjamin Franklin",
    category: "Perseverance",
    tags: ["energy", "persistence", "determination", "success"],
    popularity: 4.7,
  },
  {
    id: 129,
    text: "The beginning of wisdom is the definition of terms.",
    author: "Socrates",
    category: "Wisdom",
    tags: ["clarity", "knowledge", "definition", "understanding"],
    popularity: 4.5,
  },
  {
    id: 130,
    text: "The function of leadership is to produce more leaders, not more followers.",
    author: "Ralph Nader",
    category: "Leadership",
    tags: ["empowerment", "mentorship", "growth", "legacy"],
    popularity: 4.8,
  },
  {
    id: 131,
    text: "You have power over your mind - not outside events. Realize this, and you will find strength.",
    author: "Marcus Aurelius",
    category: "Courage",
    tags: ["stoicism", "control", "mindset", "strength"],
    popularity: 5.0,
  },
  {
    id: 132,
    text: "Most folks are about as happy as they make up their minds to be.",
    author: "Abraham Lincoln",
    category: "Happiness",
    tags: ["mindset", "choice", "perspective", "control"],
    popularity: 4.7,
  },
  {
    id: 133,
    text: "It is not enough to be busy. So are the ants. The question is: What are we busy about?",
    author: "Henry David Thoreau",
    category: "Discipline",
    tags: ["purpose", "focus", "productivity", "priorities"],
    popularity: 4.8,
  },
  {
    id: 134,
    text: "Continuous effort - not strength or intelligence - is the key to unlocking our potential.",
    author: "Winston Churchill",
    category: "Perseverance",
    tags: ["effort", "consistency", "potential", "hard-work"],
    popularity: 4.8,
  },
  {
    id: 135,
    text: "Don't be afraid to give up the good to go for the great.",
    author: "John D. Rockefeller",
    category: "Wisdom",
    tags: ["ambition", "growth", "sacrifice", "excellence"],
    popularity: 4.6,
  },
  {
    id: 136,
    text: "The challenge of leadership is to be strong, but not rude; be kind, but not weak; be bold, but not bully; be thoughtful, but not lazy.",
    author: "Jim Rohn",
    category: "Leadership",
    tags: ["balance", "character", "integrity", "nuance"],
    popularity: 4.7,
  },
  {
    id: 137,
    text: "F-E-A-R has two meanings: 'Forget Everything And Run' or 'Face Everything And Rise.' The choice is yours.",
    author: "Zig Ziglar",
    category: "Courage",
    tags: ["fear", "choice", "perspective", "rise"],
    popularity: 4.6,
  },
  {
    id: 138,
    text: "Happiness is a warm puppy.",
    author: "Charles M. Schulz",
    category: "Happiness",
    tags: ["simplicity", "joy", "love", "pets"],
    popularity: 4.3,
  },
  {
    id: 139,
    text: "True discipline is not about punishment. It’s about correcting, guiding, and showing the way.",
    author: "Unknown",
    category: "Discipline",
    tags: ["guidance", "correction", "learning", "growth"],
    popularity: 4.2,
  },
  {
    id: 140,
    text: "If you are going through hell, keep going.",
    author: "Winston Churchill",
    category: "Perseverance",
    tags: ["adversity", "resilience", "determination", "endurance"],
    popularity: 4.9,
  },
  {
    id: 141,
    text: "Holding onto anger is like drinking poison and expecting the other person to die.",
    author: "Buddha",
    category: "Wisdom",
    tags: ["anger", "forgiveness", "letting-go", "peace"],
    popularity: 4.8,
  },
  {
    id: 142,
    text: "Earn your leadership every day.",
    author: "Michael Jordan",
    category: "Leadership",
    tags: ["consistency", "effort", "respect", "dedication"],
    popularity: 4.6,
  },
  {
    id: 143,
    text: "The desire for safety stands against every great and noble enterprise.",
    author: "Tacitus",
    category: "Courage",
    tags: ["risk", "ambition", "safety", "enterprise"],
    popularity: 4.4,
  },
  {
    id: 144,
    text: "The very pursuit of happiness is what makes us unhappy.",
    author: "Unknown",
    category: "Happiness",
    tags: ["paradox", "presence", "acceptance", "mindfulness"],
    popularity: 4.1,
  },
  {
    id: 145,
    text: "The price of greatness is responsibility.",
    author: "Winston Churchill",
    category: "Discipline",
    tags: ["responsibility", "greatness", "accountability", "sacrifice"],
    popularity: 4.7,
  },
  {
    id: 146,
    text: "Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.",
    author: "John Quincy Adams",
    category: "Perseverance",
    tags: ["patience", "obstacles", "magic", "effort"],
    popularity: 4.5,
  },
  {
    id: 147,
    text: "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.",
    author: "Socrates",
    category: "Wisdom",
    tags: ["humility", "understanding", "self-awareness", "learning"],
    popularity: 4.7,
  },
  {
    id: 148,
    text: "To add value to others, one must first value others.",
    author: "John C. Maxwell",
    category: "Leadership",
    tags: ["value", "respect", "empathy", "relationships"],
    popularity: 4.5,
  },
  {
    id: 149,
    text: "Bravery is being the only one who knows you're afraid.",
    author: "Franklin P. Jones",
    category: "Courage",
    tags: ["fear", "bravery", "perception", "strength"],
    popularity: 4.4,
  },
  {
    id: 150,
    text: "For many men, the acquisition of wealth does not end their troubles, it only changes them.",
    author: "Seneca",
    category: "Happiness",
    tags: ["wealth", "problems", "perspective", "stoicism"],
    popularity: 4.6,
  },
  {
    id: 151,
    text: "Mastering others is strength. Mastering yourself is true power.",
    author: "Lao Tzu",
    category: "Discipline",
    tags: ["self-control", "power", "mastery", "strength"],
    popularity: 4.9,
  },
  {
    id: 152,
    text: "It always seems impossible until it's done.",
    author: "Nelson Mandela",
    category: "Perseverance",
    tags: ["possibility", "achievement", "perspective", "hope"],
    popularity: 4.9,
  },
  {
    id: 153,
    text: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.",
    author: "Bruce Lee",
    category: "Wisdom",
    tags: ["learning", "questions", "humility", "perspective"],
    popularity: 4.7,
  },
  {
    id: 154,
    text: "The true test of leadership is how well you function in a crisis.",
    author: "Brian Tracy",
    category: "Leadership",
    tags: ["crisis", "resilience", "composure", "decision-making"],
    popularity: 4.5,
  },
  {
    id: 155,
    text: "A man with outward courage dares to die; a man with inner courage dares to live.",
    author: "Lao Tzu",
    category: "Courage",
    tags: ["life", "inner-strength", "resilience", "living"],
    popularity: 4.6,
  },
  {
    id: 156,
    text: "Sanity and happiness are an impossible combination.",
    author: "Mark Twain",
    category: "Happiness",
    tags: ["humor", "perspective", "life", "reality"],
    popularity: 4.2,
  },
  {
    id: 157,
    text: "If you don't have discipline, you don't have anything.",
    author: "Georges St-Pierre",
    category: "Discipline",
    tags: ["foundation", "success", "control", "essentials"],
    popularity: 4.3,
  },
  {
    id: 158,
    text: "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    author: "Thomas A. Edison",
    category: "Perseverance",
    tags: ["failure", "success", "proximity", "giving-up"],
    popularity: 4.8,
  },
  {
    id: 159,
    text: "Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won't come in.",
    author: "Isaac Asimov",
    category: "Wisdom",
    tags: ["assumptions", "perspective", "open-mindedness", "learning"],
    popularity: 4.7,
  },
  {
    id: 160,
    text: "Leadership is not a position or a title, it is action and example.",
    author: "Unknown",
    category: "Leadership",
    tags: ["action", "example", "influence", "character"],
    popularity: 4.6,
  },
  {
    id: 161,
    text: "What is to give light must endure burning.",
    author: "Viktor Frankl",
    category: "Courage",
    tags: ["sacrifice", "purpose", "suffering", "impact"],
    popularity: 4.8,
  },
  {
    id: 162,
    text: "There is no path to happiness: happiness is the path.",
    author: "Buddha",
    category: "Happiness",
    tags: ["journey", "presence", "mindfulness", "process"],
    popularity: 4.8,
  },
  {
    id: 163,
    text: "A man has to learn that he cannot command things, but that he can command himself.",
    author: "Jack London",
    category: "Discipline",
    tags: ["self-control", "stoicism", "command", "power"],
    popularity: 4.5,
  },
  {
    id: 164,
    text: "Perseverance is failing 19 times and succeeding the 20th.",
    author: "Julie Andrews",
    category: "Perseverance",
    tags: ["failure", "success", "resilience", "numbers"],
    popularity: 4.4,
  },
  {
    id: 165,
    text: "The older I get, the more I listen to people who don't talk much.",
    author: "Germain G. Glidden",
    category: "Wisdom",
    tags: ["listening", "silence", "observation", "experience"],
    popularity: 4.5,
  },
  {
    id: 166,
    text: "No man will make a great leader who wants to do it all himself or get all the credit for doing it.",
    author: "Andrew Carnegie",
    category: "Leadership",
    tags: ["delegation", "humility", "teamwork", "credit"],
    popularity: 4.6,
  },
  {
    id: 167,
    text: "The most courageous act is still to think for yourself. Aloud.",
    author: "Coco Chanel",
    category: "Courage",
    tags: ["individuality", "thinking", "voice", "authenticity"],
    popularity: 4.7,
  },
  {
    id: 168,
    text: "Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.",
    author: "Marcel Proust",
    category: "Happiness",
    tags: ["gratitude", "relationships", "friendship", "joy"],
    popularity: 4.6,
  },
  {
    id: 169,
    text: "The distance between your dreams and reality is called discipline.",
    author: "Unknown",
    category: "Discipline",
    tags: ["dreams", "reality", "action", "goals"],
    popularity: 4.7,
  },
  {
    id: 170,
    text: "I can accept failure, everyone fails at something. But I can't accept not trying.",
    author: "Michael Jordan",
    category: "Perseverance",
    tags: ["failure", "effort", "trying", "regret"],
    popularity: 4.9,
  },
  {
    id: 171,
    text: "We don't see things as they are, we see them as we are.",
    author: "Anaïs Nin",
    category: "Wisdom",
    tags: ["perception", "perspective", "subjectivity", "reality"],
    popularity: 4.8,
  },
  {
    id: 172,
    text: "Leadership is unlocking people's potential to become better.",
    author: "Bill Bradley",
    category: "Leadership",
    tags: ["potential", "growth", "empowerment", "mentorship"],
    popularity: 4.6,
  },
  {
    id: 173,
    text: "Courage is the first of human qualities because it is the quality which guarantees the others.",
    author: "Aristotle",
    category: "Courage",
    tags: ["foundation", "virtue", "strength", "character"],
    popularity: 4.7,
  },
  {
    id: 174,
    text: "The pleasure which we most rarely experience gives us greatest delight.",
    author: "Epictetus",
    category: "Happiness",
    tags: ["pleasure", "rarity", "delight", "appreciation"],
    popularity: 4.2,
  },
  {
    id: 175,
    text: "Self-respect is the fruit of discipline; the sense of dignity grows with the ability to say no to oneself.",
    author: "Abraham Joshua Heschel",
    category: "Discipline",
    tags: ["self-respect", "dignity", "self-control", "choice"],
    popularity: 4.6,
  },
  {
    id: 176,
    text: "Do today what others won't so tomorrow you can do what others can't.",
    author: "Jerry Rice",
    category: "Perseverance",
    tags: ["sacrifice", "hard-work", "future", "reward"],
    popularity: 4.8,
  },
  {
    id: 177,
    text: "When you talk, you are only repeating what you already know. But if you listen, you may learn something new.",
    author: "Dalai Lama",
    category: "Wisdom",
    tags: ["listening", "learning", "communication", "humility"],
    popularity: 4.9,
  },
  {
    id: 178,
    text: "The very essence of leadership is that you have to have a vision.",
    author: "Theodore Hesburgh",
    category: "Leadership",
    tags: ["vision", "purpose", "direction", "future"],
    popularity: 4.5,
  },
  {
    id: 179,
    text: "One isn't born with courage, one develops it.",
    author: "Maya Angelou",
    category: "Courage",
    tags: ["growth", "development", "practice", "strength"],
    popularity: 4.7,
  },
  {
    id: 180,
    text: "There are more things to alarm us than to harm us, and we suffer more often in apprehension than in reality.",
    author: "Seneca",
    category: "Happiness",
    tags: ["anxiety", "fear", "reality", "stoicism"],
    popularity: 4.7,
  },
  {
    id: 181,
    text: "Discipline is remembering what you want.",
    author: "David Campbell",
    category: "Discipline",
    tags: ["focus", "goals", "memory", "clarity"],
    popularity: 4.5,
  },
  {
    id: 182,
    text: "The man who moves a mountain begins by carrying away small stones.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["patience", "consistency", "progress", "small-steps"],
    popularity: 4.8,
  },
  {
    id: 183,
    text: "A man who asks is a fool for five minutes. A man who never asks is a fool for life.",
    author: "Chinese Proverb",
    category: "Wisdom",
    tags: ["questions", "learning", "humility", "curiosity"],
    popularity: 4.6,
  },
  {
    id: 184,
    text: "Average leaders raise the bar on themselves; good leaders raise the bar for others; great leaders inspire others to raise their own bar.",
    author: "Orrin Woodward",
    category: "Leadership",
    tags: ["inspiration", "empowerment", "standards", "growth"],
    popularity: 4.7,
  },
  {
    id: 185,
    text: "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
    author: "Socrates",
    category: "Courage",
    tags: ["change", "focus", "creation", "progress"],
    popularity: 4.8,
  },
  {
    id: 186,
    text: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.",
    author: "Franklin D. Roosevelt",
    category: "Happiness",
    tags: ["achievement", "creativity", "effort", "joy"],
    popularity: 4.5,
  },
  {
    id: 187,
    text: "The pain you feel today is the strength you feel tomorrow.",
    author: "Dwayne Johnson",
    category: "Discipline",
    tags: ["pain", "strength", "growth", "resilience"],
    popularity: 4.7,
  },
  {
    id: 188,
    text: "Victory is always possible for the person who refuses to stop fighting.",
    author: "Napoleon Hill",
    category: "Perseverance",
    tags: ["victory", "determination", "fighting", "never-give-up"],
    popularity: 4.6,
  },
  {
    id: 189,
    text: "The only thing that interferes with my learning is my education.",
    author: "Albert Einstein",
    category: "Wisdom",
    tags: ["learning", "education", "curiosity", "thinking"],
    popularity: 4.6,
  },
  {
    id: 190,
    text: "A commander's primary function is to create and preserve a state of mind in his troops reflected by the term 'morale'.",
    author: "George C. Marshall",
    category: "Leadership",
    tags: ["morale", "psychology", "team", "influence"],
    popularity: 4.3,
  },
  {
    id: 191,
    text: "Courage is found in unlikely places.",
    author: "J.R.R. Tolkien",
    category: "Courage",
    tags: ["bravery", "humility", "unexpected", "strength"],
    popularity: 4.5,
  },
  {
    id: 192,
    text: "Resolve to keep happy, and your joy and you shall form an invincible host against difficulties.",
    author: "Helen Keller",
    category: "Happiness",
    tags: ["resolve", "joy", "resilience", "mindset"],
    popularity: 4.6,
  },
  {
    id: 193,
    text: "It's a luxury to be understood.",
    author: "Ralph Waldo Emerson",
    category: "Wisdom",
    tags: ["understanding", "communication", "empathy", "connection"],
    popularity: 4.4,
  },
  {
    id: 194,
    text: "If you don't stick to your values when they're being tested, they're not values: they're hobbies.",
    author: "Jon Stewart",
    category: "Discipline",
    tags: ["values", "integrity", "consistency", "character"],
    popularity: 4.8,
  },
  {
    id: 195,
    text: "You may have to fight a battle more than once to win it.",
    author: "Margaret Thatcher",
    category: "Perseverance",
    tags: ["resilience", "battle", "victory", "repetition"],
    popularity: 4.5,
  },
  {
    id: 196,
    text: "An army of sheep led by a lion is better than an army of lions led by a sheep.",
    author: "Alexander the Great",
    category: "Leadership",
    tags: ["strength", "example", "influence", "capability"],
    popularity: 4.7,
  },
  {
    id: 197,
    text: "What man actually needs is not a tensionless state but rather the striving and struggling for a worthwhile goal.",
    author: "Viktor Frankl",
    category: "Courage",
    tags: ["purpose", "struggle", "meaning", "goals"],
    popularity: 4.7,
  },
  {
    id: 198,
    text: "The secret of being happy is accepting where you are in life and making the most out of every day.",
    author: "Unknown",
    category: "Happiness",
    tags: ["acceptance", "presence", "mindfulness", "gratitude"],
    popularity: 4.5,
  },
  {
    id: 199,
    text: "A journey of a thousand miles must begin with a single step.",
    author: "Lao Tzu",
    category: "Discipline",
    tags: ["beginnings", "action", "journey", "motivation"],
    popularity: 4.9,
  },
  {
    id: 200,
    text: "The world breaks everyone, and afterward, some are strong at the broken places.",
    author: "Ernest Hemingway",
    category: "Perseverance",
    tags: ["resilience", "strength", "adversity", "healing"],
    popularity: 4.8,
  },
];
