import type { Quote } from "@/types";

export const quotes: Quote[] = [
  {
    id: 1,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 2,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 3,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 4,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 5,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 6,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 7,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 8,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 9,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 10,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 11,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 12,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 13,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 14,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 15,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 16,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 17,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 18,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 19,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 20,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 21,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 22,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 23,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 24,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 25,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 26,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 27,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 28,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 29,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 30,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 31,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 32,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 33,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 34,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 35,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 36,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 37,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 38,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 39,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 40,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 41,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 42,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 43,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 44,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 45,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 46,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 47,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 48,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 49,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 50,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 51,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 52,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 53,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 54,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 55,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 56,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 57,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 58,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 59,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 60,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 61,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 62,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 63,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 64,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 65,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 66,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 67,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 68,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 69,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 70,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 71,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 72,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 73,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 74,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 75,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 76,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 77,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 78,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 79,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 80,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 81,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 82,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 83,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 84,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 85,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 86,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 87,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 88,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 89,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 90,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 91,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 92,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 93,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 94,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 95,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 96,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 97,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 98,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 99,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 100,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 101,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 102,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 103,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 104,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 105,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 106,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 107,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 108,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 109,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 110,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 111,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 112,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 113,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 114,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 115,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 116,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 117,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 118,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 119,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 120,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 121,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 122,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 123,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 124,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 125,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 126,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 127,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 128,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 129,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 130,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 131,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 132,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 133,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 134,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 135,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 136,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 137,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 138,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 139,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 140,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 141,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 142,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 143,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 144,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 145,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 146,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 147,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 148,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 149,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 150,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 151,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 152,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 153,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 154,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 155,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 156,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 157,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 158,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 159,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 160,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 161,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 162,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 163,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 164,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 165,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 166,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 167,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 168,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 169,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 170,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 171,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 172,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 173,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 174,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 175,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 176,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 177,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 178,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 179,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 180,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 181,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 182,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 183,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 184,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 185,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 186,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 187,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 188,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 189,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 190,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 191,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 192,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 193,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 194,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 195,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
  {
    id: 196,
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    tags: ["work", "passion", "greatness"],
    popularity: 4.9,
  },
  {
    id: 197,
    text: "In the middle of every difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "Motivation",
    tags: ["opportunity", "difficulty", "growth"],
    popularity: 4.8,
  },
  {
    id: 198,
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["progress", "patience", "determination"],
    popularity: 4.7,
  },
  {
    id: 199,
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["self", "choice", "joy"],
    popularity: 4.6,
  },
  {
    id: 200,
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["success", "failure", "courage"],
    popularity: 4.9,
  },
];
