import type { Twister } from "@/types";

export const twisters: Twister[] = [
  {
    id: 1,
    text: "Speak clearly and deliberately.",
    difficulty: "Easy",
    category: "Communication Tip",
    tags: ["clarity", "pacing"],
  },
  {
    id: 2,
    text: "Maintain confident eye contact.",
    difficulty: "Easy",
    category: "Communication Tip",
    tags: ["confidence", "engagement"],
  },
  {
    id: 3,
    text: "Red leather, yellow leather.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["l", "r", "agility"],
  },
  {
    id: 4,
    text: "Which witch is which?",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["w", "ch"],
  },
  {
    id: 5,
    text: "Toy boat. Try boat. Toy boat.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["t", "b", "vowels"],
  },
  {
    id: 6,
    text: "She sees cheese.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "sh", "ch"],
  },
  {
    id: 7,
    text: "Pause for emphasis.",
    difficulty: "Easy",
    category: "Communication Tip",
    tags: ["pacing", "impact"],
  },
  {
    id: 8,
    text: "Unique New York.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["n", "y"],
  },
  {
    id: 9,
    text: "Flash message.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["fl-blend", "s", "sh"],
  },
  {
    id: 10,
    text: "Breathe deeply before you speak.",
    difficulty: "Easy",
    category: "Communication Tip",
    tags: ["confidence", "calmness"],
  },
  {
    id: 11,
    text: "He threw three free throws.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["th", "r"],
  },
  {
    id: 12,
    text: "The blue bluebird blinks.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "l-blend"],
  },
  {
    id: 13,
    text: "Truly rural.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["r", "l"],
  },
  {
    id: 14,
    text: "Think thin thoughts.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["th", "voiceless-th"],
  },
  {
    id: 15,
    text: "Use simple language.",
    difficulty: "Easy",
    category: "Communication Tip",
    tags: ["clarity", "simplicity"],
  },
  {
    id: 16,
    text: "Six sticky skeletons.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "sk-blend"],
  },
  {
    id: 17,
    text: "Fresh fried fish, fish fresh fried.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "r", "sh"],
  },
  {
    id: 18,
    text: "A proper copper coffee pot.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["p", "k"],
  },
  {
    id: 19,
    text: "A noisy noise annoys an oyster.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["n", "vowels"],
  },
  {
    id: 20,
    text: "Voiced 'th': this, that, then.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["th", "voiced-th"],
  },
  {
    id: 21,
    text: "The vet wet the vest.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["v", "w"],
  },
  {
    id: 22,
    text: "Vary your vocal pitch.",
    difficulty: "Easy",
    category: "Communication Tip",
    tags: ["engagement", "intonation"],
  },
  {
    id: 23,
    text: "Double bubble gum bubbles double.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "d", "l"],
  },
  {
    id: 24,
    text: "A gentle judge judges justly.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["j", "g"],
  },
  {
    id: 25,
    text: "Specific Pacific.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "p", "k"],
  },
  {
    id: 26,
    text: "Rolling red wagons.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["r", "w"],
  },
  {
    id: 27,
    text: "The myth of Miss Muffet.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["m", "th"],
  },
  {
    id: 28,
    text: "Show, don't just tell.",
    difficulty: "Easy",
    category: "Communication Tip",
    tags: ["storytelling", "impact"],
  },
  {
    id: 29,
    text: "The thirty-three thieves.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["th", "r"],
  },
  {
    id: 30,
    text: "Good blood, bad blood.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "d", "g"],
  },
  {
    id: 31,
    text: "Black back bat.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "k"],
  },
  {
    id: 32,
    text: "A bragging baker baked black bread.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "r-blend"],
  },
  {
    id: 33,
    text: "Differentiate: ship / sheep / cheap.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["minimal-pairs", "vowels", "sh"],
  },
  {
    id: 34,
    text: "Will you, William?",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["w", "l"],
  },
  {
    id: 35,
    text: "Pirates private property.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["p", "r"],
  },
  {
    id: 36,
    text: "He has to have his.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["h", "s", "z"],
  },
  {
    id: 37,
    text: "Freshly fried flying fish.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "r-blend", "l-blend"],
  },
  {
    id: 38,
    text: "Round the rugged rock.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["r", "g"],
  },
  {
    id: 39,
    text: "The queen in green screamed.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["q", "gr-blend", "scr-blend"],
  },
  {
    id: 40,
    text: "Eddie edited it.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["d", "t", "vowels"],
  },
  {
    id: 41,
    text: "An ape hates grape cakes.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["p", "gr-blend", "k"],
  },
  {
    id: 42,
    text: "Eleven benevolent elephants.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["l", "v", "n"],
  },
  {
    id: 43,
    text: "Cheap ship trips.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["ch", "sh", "tr-blend"],
  },
  {
    id: 44,
    text: "Do drop in at the Dilly-Dally Pub.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["d", "p", "b"],
  },
  {
    id: 45,
    text: "Is this your wish?",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["s", "sh", "th"],
  },
  {
    id: 46,
    text: "His selfish fish swims swiftly.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "f", "sw-blend"],
  },
  {
    id: 47,
    text: "A yellow yo-yo is a youthful joy.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["y", "j"],
  },
  {
    id: 48,
    text: "End with a clear call to action.",
    difficulty: "Easy",
    category: "Communication Tip",
    tags: ["clarity", "persuasion"],
  },
  {
    id: 49,
    text: "Gobbling gargoyles gobbled gobbling goblins.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["g", "b", "l"],
  },
  {
    id: 50,
    text: "Stupid superstition.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "t", "p"],
  },
  {
    id: 51,
    text: "I was born on a pirate ship.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["p", "r", "b"],
  },
  {
    id: 52,
    text: "Knapsack straps.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["k", "s", "tr-blend"],
  },
  {
    id: 53,
    text: "Literally literary.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["l", "t", "r"],
  },
  {
    id: 54,
    text: "Drew Dodd’s dad’s dog’s dead.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["d", "consonants"],
  },
  {
    id: 55,
    text: "Differentiate: fan / van / ban.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["minimal-pairs", "f", "v"],
  },
  {
    id: 56,
    text: "Scissors sizzle, thistles sizzle.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "z", "th"],
  },
  {
    id: 57,
    text: "Three short swords sell swiftly.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "th", "r"],
  },
  {
    id: 58,
    text: "Crisp crusts crackle crunchily.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["cr-blend", "k"],
  },
  {
    id: 59,
    text: "Twelve twins twirled twelve twigs.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["tw-blend", "l"],
  },
  {
    id: 60,
    text: "Six sharp smart sharks.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "sh", "sm-blend"],
  },
  {
    id: 61,
    text: "Voiceless 'th': thin, thick, thank.",
    difficulty: "Easy",
    category: "Pronunciation Exercise",
    tags: ["th", "voiceless-th"],
  },
  {
    id: 62,
    text: "Green glass globes glow greenly.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["g", "l-blend", "gr-blend"],
  },
  {
    id: 63,
    text: "Seth at sunset stays stiffly.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "th", "st-blend"],
  },
  {
    id: 64,
    text: "Rubber baby buggy bumpers.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "r"],
  },
  {
    id: 65,
    text: "World Wide Web.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["w", "r", "l"],
  },
  {
    id: 66,
    text: "Preshrunk silk shirts.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["sh", "r", "s"],
  },
  {
    id: 67,
    text: "A shapeless sash sags slowly.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "sh", "sl-blend"],
  },
  {
    id: 68,
    text: "Quick kiss. Quicker kiss.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["q", "k", "s"],
  },
  {
    id: 69,
    text: "Practice active listening skills daily.",
    difficulty: "Easy",
    category: "Communication Tip",
    tags: ["listening", "engagement"],
  },
  {
    id: 70,
    text: "Red lorry, yellow lorry.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["r", "l"],
  },
  {
    id: 71,
    text: "The bird turned third.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["r", "th", "vowels"],
  },
  {
    id: 72,
    text: "Is it a chair or a share?",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["ch", "sh", "minimal-pairs"],
  },
  {
    id: 73,
    text: "Less lists lose luster.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["l", "s", "t"],
  },
  {
    id: 74,
    text: "Which wristwatches are Swiss wristwatches?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["w", "s", "ch"],
  },
  {
    id: 75,
    text: "Seventy-seven benevolent elephants.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "v", "l"],
  },
  {
    id: 76,
    text: "Listen actively before you respond.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["listening", "respect"],
  },
  {
    id: 77,
    text: "The Irish wristwatch is Swiss.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["r", "sh", "s"],
  },
  {
    id: 78,
    text: "She sells seashells by the seashore.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sh"],
  },
  {
    id: 79,
    text: "A snake sneaks to seek a snack.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["s", "sn-blend", "k"],
  },
  {
    id: 80,
    text: "Use gestures to enhance your message.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["body-language", "engagement"],
  },
  {
    id: 81,
    text: "I saw a kitten eating chicken in the kitchen.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "ch", "t"],
  },
  {
    id: 82,
    text: "The tip of the tongue, the teeth, the lips.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["articulation", "t", "th"],
  },
  {
    id: 83,
    text: "Match your tone to your message.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["intonation", "clarity"],
  },
  {
    id: 84,
    text: "How can a clam cram in a clean cream can?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "l-blend", "r-blend"],
  },
  {
    id: 85,
    text: "Repeat 'pah-tah-kah' quickly for jaw agility.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["articulation", "agility"],
  },
  {
    id: 86,
    text: "A big black bug bit a big black bear.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["b", "g"],
  },
  {
    id: 87,
    text: "The rain in Spain stays mainly in the plain.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["vowels", "diphthongs"],
  },
  {
    id: 88,
    text: "Avoid using filler words like 'um' and 'ah'.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["clarity", "confidence", "filler-words"],
  },
  {
    id: 89,
    text: "A loyal warrior will rarely worry why we rule.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["l", "r", "w"],
  },
  {
    id: 90,
    text: "Say 'oo-ee-oo-ee-ah' to stretch your mouth.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["vowels", "warm-up", "agility"],
  },
  {
    id: 91,
    text: "I scream, you scream, we all scream for ice cream.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "scr-blend", "k"],
  },
  {
    id: 92,
    text: "Four furious friends fought for the phone.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["f", "r"],
  },
  {
    id: 93,
    text: "Structure your thoughts before speaking.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["clarity", "structure"],
  },
  {
    id: 94,
    text: "That is the wrong thong.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["th", "r", "ng"],
  },
  {
    id: 95,
    text: "The aluminum linoleum is on the podium.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["l", "m", "n"],
  },
  {
    id: 96,
    text: "Can you can a can as a canner can can a can?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "n"],
  },
  {
    id: 97,
    text: "A skunk sat on a stump and thunk the stump stunk.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "k", "nk-blend"],
  },
  {
    id: 98,
    text: "A genuine smile can build instant rapport.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["rapport", "body-language"],
  },
  {
    id: 99,
    text: "A quick witted cricket critic chirped.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["q", "k", "r"],
  },
  {
    id: 100,
    text: "Focus on the crisp 't' sound in 'truly rural'.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["t", "r", "l"],
  },
  {
    id: 101,
    text: "He is a purely rural, truly plural ruler.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["r", "l"],
  },
  {
    id: 102,
    text: "We wander while we wait.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["w", "l"],
  },
  {
    id: 103,
    text: "Differentiate the vowel sound in 'cat' vs 'cot'.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["vowels", "minimal-pairs"],
  },
  {
    id: 104,
    text: "An open posture conveys confidence and approachability.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["body-language", "confidence"],
  },
  {
    id: 105,
    text: "Strange strategic statistics.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "t", "r"],
  },
  {
    id: 106,
    text: "Practice the light 'l' in 'lily' vs the dark 'l' in 'full'.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["l", "articulation"],
  },
  {
    id: 107,
    text: "Fred fed Ted bread, and Ted fed Fred bread.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["f", "t", "d"],
  },
  {
    id: 108,
    text: "The ochre ogre ordered an oak organ.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["o", "g", "r"],
  },
  {
    id: 109,
    text: "Mirroring body language subtly can build a connection.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["rapport", "body-language"],
  },
  {
    id: 110,
    text: "I saw Susie sitting in a shoeshine shop.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sh"],
  },
  {
    id: 111,
    text: "Place the pen on the pin.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["e", "i", "minimal-pairs"],
  },
  {
    id: 112,
    text: "Summarize key points to ensure understanding.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["clarity", "listening"],
  },
  {
    id: 113,
    text: "Denise sees the fleece, Denise sees the fleas.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "z", "f"],
  },
  {
    id: 114,
    text: "Feel the buzz on your lips for the 'v' sound.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["v", "articulation"],
  },
  {
    id: 115,
    text: "A synonym for cinnamon is a cinnamon synonym.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "n", "m"],
  },
  {
    id: 116,
    text: "Fuzzy Wuzzy was a bear, Fuzzy Wuzzy had no hair.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["z", "f", "w"],
  },
  {
    id: 117,
    text: "Ask open-ended questions to encourage conversation.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["engagement", "conversation"],
  },
  {
    id: 118,
    text: "This is the sixth zebra snoozing soundly.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "z", "th"],
  },
  {
    id: 119,
    text: "Feel the air puff for 'p' but not for 'b'.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["p", "b", "articulation"],
  },
  {
    id: 120,
    text: "Enunciate the final consonant of each word.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["clarity", "enunciation"],
  },
  {
    id: 121,
    text: "A lazy lying lion is lying on the lawn.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["l", "n"],
  },
  {
    id: 122,
    text: "Stretch the vowel in 'see' but keep the vowel in 'sit' short.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["vowels", "minimal-pairs", "duration"],
  },
  {
    id: 123,
    text: "The big bad Bill borrowed Ben's bright blue blazer.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["b", "l", "r"],
  },
  {
    id: 124,
    text: "We surely shall see the sun shine soon.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sh"],
  },
  {
    id: 125,
    text: "Project your voice from your diaphragm for power.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["projection", "voice"],
  },
  {
    id: 126,
    text: "The chums chopped chips of cheap chocolate.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["ch", "p"],
  },
  {
    id: 127,
    text: "Round and round the rugged rocks the ragged rascal ran.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["r", "g", "k"],
  },
  {
    id: 128,
    text: "I need to leave now, so I will live.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["vowels", "minimal-pairs", "l"],
  },
  {
    id: 129,
    text: "Adapt your communication style to your audience.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["audience", "adaptation"],
  },
  {
    id: 130,
    text: "If Stu chews shoes, should Stu choose the shoes he chews?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "ch", "sh"],
  },
  {
    id: 131,
    text: "The cheerful cherubs chanted charmingly.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["ch", "r"],
  },
  {
    id: 132,
    text: "When receiving feedback, listen without becoming defensive.",
    difficulty: "Medium",
    category: "Communication Tip",
    tags: ["feedback", "listening"],
  },
  {
    id: 133,
    text: "Vain Vincent vowed vengeance very vehemently.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["v", "n"],
  },
  {
    id: 134,
    text: "The 'ng' sound in 'singing' should resonate in your nasal cavity.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["ng", "nasals", "articulation"],
  },
  {
    id: 135,
    text: "The cat catcher can't catch caught cats.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "t", "ch"],
  },
  {
    id: 136,
    text: "If you understand, say 'understand'. If you don't understand, say 'don't understand'.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["d", "s", "n"],
  },
  {
    id: 137,
    text: "Distinguish between 'w' and 'wh' in 'witch' and 'which'.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["w", "wh", "minimal-pairs"],
  },
  {
    id: 138,
    text: "Mix a box of mixed biscuits with a boxed biscuit mixer.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["b", "k", "s"],
  },
  {
    id: 139,
    text: "There's a sandwich on the sand which was sent by a sane witch.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "w", "ch"],
  },
  {
    id: 140,
    text: "The bottom of the butter bucket is the buttered bucket bottom.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["b", "t", "d"],
  },
  {
    id: 141,
    text: "I like to light a night-light on a light night like tonight.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["l", "n", "t"],
  },
  {
    id: 142,
    text: "Round your lips for 'sh' and smile for 's'.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["sh", "s", "articulation"],
  },
  {
    id: 143,
    text: "If a dog chews shoes, whose shoes does he choose?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["ch", "sh", "z"],
  },
  {
    id: 144,
    text: "Zealously, zebras zigzagged in the zone.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["z", "g"],
  },
  {
    id: 145,
    text: "On a lazy laser raiser lies a laser ray eraser.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["l", "z", "r"],
  },
  {
    id: 146,
    text: "Exaggerate the 'm' sound by humming: 'Mmm-more mmm-money.'",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["m", "nasals", "resonance"],
  },
  {
    id: 147,
    text: "Six sleek swans swam swiftly southwards.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sw-blend", "l"],
  },
  {
    id: 148,
    text: "No need to light a night-light on a light night like tonight.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["n", "l", "t"],
  },
  {
    id: 149,
    text: "The shrewd shrew sold Sarah seven silver silk sashes.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sh", "r"],
  },
  {
    id: 150,
    text: "Is this the thing? Yes, this is the thing.",
    difficulty: "Medium",
    category: "Pronunciation Exercise",
    tags: ["th", "s", "ng"],
  },
  {
    id: 151,
    text: "The sixth sick sheik's sixth sheep's sick.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "k", "sh"],
  },
  {
    id: 152,
    text: "Tell a compelling story to make your data memorable.",
    difficulty: "Hard",
    category: "Communication Tip",
    tags: ["storytelling", "persuasion"],
  },
  {
    id: 153,
    text: "The rural juror surely pluralizes the lure.",
    difficulty: "Hard",
    category: "Pronunciation Exercise",
    tags: ["r", "l", "zh"],
  },
  {
    id: 154,
    text: "Lesser leather never weathered wetter weather better.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["l", "th", "w"],
  },
  {
    id: 155,
    text: "The 'rule of three' makes your points more satisfying and memorable.",
    difficulty: "Hard",
    category: "Communication Tip",
    tags: ["structure", "rhetoric"],
  },
  {
    id: 156,
    text: "Pad kid poured curd pulled cod.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["p", "k", "d"],
  },
  {
    id: 157,
    text: "Read this list of words aloud: through, though, tough, bough, cough.",
    difficulty: "Hard",
    category: "Pronunciation Exercise",
    tags: ["vowels", "spelling", "exceptions"],
  },
  {
    id: 158,
    text: "I wish to wash my Irish wristwatch.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["w", "sh", "r"],
  },
  {
    id: 159,
    text: "Begin with a powerful hook to capture your audience's attention immediately.",
    difficulty: "Hard",
    category: "Communication Tip",
    tags: ["public-speaking", "engagement", "hooks"],
  },
  {
    id: 160,
    text: "Near an ear, a nearer ear, a nearly eerie ear.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["vowels", "r"],
  },
  {
    id: 161,
    text: "Practice the unstressed schwa sound in words like 'about', 'sofa', 'banana'.",
    difficulty: "Hard",
    category: "Pronunciation Exercise",
    tags: ["schwa", "stress", "vowels"],
  },
  {
    id: 162,
    text: "The great Greek grape growers grow great Greek grapes.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["g", "r"],
  },
  {
    id: 163,
    text: "Use silence strategically; it can be more powerful than words.",
    difficulty: "Hard",
    category: "Communication Tip",
    tags: ["pacing", "confidence", "impact"],
  },
  {
    id: 164,
    text: "Sounding by sound is a sound method of sounding sounds.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "n", "d"],
  },
  {
    id: 165,
    text: "Pronounce the stress difference: 'affect' (verb) vs 'effect' (noun).",
    difficulty: "Hard",
    category: "Pronunciation Exercise",
    tags: ["stress", "minimal-pairs", "grammar"],
  },
  {
    id: 166,
    text: "One-one was a race horse; two-two was one too.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["w", "t", "r"],
  },
  {
    id: 167,
    text: "Rephrase what you heard to confirm your understanding: 'So, what you're saying is...'",
    difficulty: "Hard",
    category: "Communication Tip",
    tags: ["active-listening", "clarity"],
  },
  {
    id: 168,
    text: "To make a clear 'k' sound, touch the back of your tongue to your soft palate.",
    difficulty: "Hard",
    category: "Pronunciation Exercise",
    tags: ["k", "articulation", "placement"],
  },
  {
    id: 169,
    text: "Articulate the 'sts' cluster in 'tastes,' 'tests,' and 'ghosts.'",
    difficulty: "Hard",
    category: "Pronunciation Exercise",
    tags: ["consonant-clusters", "s", "t"],
  },
  {
    id: 170,
    text: "Instead of 'but,' try using 'and' to create a more collaborative tone.",
    difficulty: "Hard",
    category: "Communication Tip",
    tags: ["word-choice", "collaboration"],
  },
  {
    id: 171,
    text: "Record yourself speaking to identify areas for improvement.",
    difficulty: "Hard",
    category: "Communication Tip",
    tags: ["self-awareness", "practice"],
  },
  {
    id: 172,
    text: "Practice dropping the jaw for the 'ah' sound in 'father', 'hot', 'stop'.",
    difficulty: "Hard",
    category: "Pronunciation Exercise",
    tags: ["vowels", "articulation", "jaw-tension"],
  },
  {
    id: 173,
    text: "Peter Piper picked a peck of pickled peppers.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["p", "k"],
  },
  {
    id: 174,
    text: "Betty Botter bought some butter but she said the butter’s bitter.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["b", "t", "r"],
  },
  {
    id: 175,
    text: "Any noise annoys an oyster, but a noisy noise annoys an oyster more.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["n", "s", "vowels"],
  },
  {
    id: 176,
    text: "The thirty-three thieves thought that they thrilled the throne throughout Thursday.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "r"],
  },
  {
    id: 177,
    text: "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["w", "ch", "k"],
  },
  {
    id: 178,
    text: "I slit the sheet, the sheet I slit, and on the slitted sheet I sit.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "l", "sh"],
  },
  {
    id: 179,
    text: "I thought a thought, but the thought I thought wasn't the thought I thought I thought.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "t"],
  },
  {
    id: 180,
    text: "Of all the felt I ever felt, I never felt a piece of felt which felt as fine as that felt felt.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["f", "l", "t"],
  },
  {
    id: 181,
    text: "Wayne went to Wales to watch walruses.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["w", "l", "s"],
  },
  {
    id: 182,
    text: "Imagine an imaginary menagerie manager managing an imaginary menagerie.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["m", "n", "j"],
  },
  {
    id: 183,
    text: "A fat cat sat on the mat and ate a fat rat.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["a", "t", "k"],
  },
  {
    id: 184,
    text: "These thousand tricky tongue twisters trip thrillingly off the tongue.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "t", "r"],
  },
  {
    id: 185,
    text: "Shy Shelley says she shall sew sheets.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["sh", "s", "l"],
  },
  {
    id: 186,
    text: "How many cookies could a good cook cook if a good cook could cook cookies?",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["k", "g", "d"],
  },
  {
    id: 187,
    text: "A pleasant place to place a plaice is a place where a plaice is pleased to be placed.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["p", "l", "s"],
  },
  {
    id: 188,
    text: "If you notice this notice, you will notice that this notice is not worth noticing.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["n", "t", "s"],
  },
  {
    id: 189,
    text: "Pick a partner and practice passing, for practice makes perfect.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["p", "r", "k"],
  },
  {
    id: 190,
    text: "While we were walking, we were watching window washers wash Washington's windows.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["w", "sh", "s"],
  },
  {
    id: 191,
    text: "A Finnish fisher named Fisher failed to fish any fish one Friday afternoon.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["f", "sh", "r"],
  },
  {
    id: 192,
    text: "Rory the warrior and Roger the worrier were reared wrongly in a rural brewery.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["r", "w", "l"],
  },
  {
    id: 193,
    text: "The seething sea ceaseth and thus the seething sea sufficeth us.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "th", "z"],
  },
  {
    id: 194,
    text: "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["b", "r", "d"],
  },
  {
    id: 195,
    text: "Theophilus Thistle, the successful thistle sifter, in sifting a sieve full of unsifted thistles, thrust three thousand thistles through the thick of his thumb.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "s", "f"],
  },
  {
    id: 196,
    text: "Send toast to ten tense stout saints' ten tall tents.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["t", "s", "n"],
  },
  {
    id: 197,
    text: "A gazillion gigantic grapes gushed gradually, giving Gwendolyn glee.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["g", "z", "l"],
  },
  {
    id: 198,
    text: "To sit in solemn silence in a dull, dark dock, in a pestilential prison, with a life-long lock.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "l", "d"],
  },
  {
    id: 199,
    text: "She threw sharp, shiny, silver stars.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["sh", "s", "r"],
  },
  {
    id: 200,
    text: "What a terrible tongue twister.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["t", "r", "w"],
  },
];
