import type { Grade9Question } from "@/types";

const grade9Kiswahili: Grade9Question[] = [
  {
    id: 1,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Andika wingi wa sentensi: 'Mtoto mdogo amekuja.'",
    answer: "watoto wadogo wamekuja",
    acceptedAnswers: ["watoto wadogo wamekuja", "watoto wadogo wamekuja."],
    explanation: "Katika ngeli ya A-WA: 'mtoto' inakuwa 'watoto', 'mdogo' inakuwa 'wadogo', na 'amekuja' inakuwa 'wamekuja'.",
    marks: 2,
  },
  {
    id: 2,
    subject: "Kiswahili",
    topic: "Fasihi",
    question: "Methali 'Asiyefunzwa na mamae hufunzwa na ulimwengu' inasisitiza umuhimu wa nini nyumbani?",
    answer: "malezi",
    acceptedAnswers: ["malezi", "malezi mazuri", "mafunzo", "kufunzwa"],
    explanation: "Methali hii inamaanisha Mtu ambaye hapati malezi mazuri nyumbani ataishia kujifunza maisha kwa njia ngumu duniani.",
    marks: 2,
  },
  {
    id: 3,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Neno linalotumika kutaja watu, vitu, mahali, au hali linaitwa nini?",
    answer: "nomino",
    acceptedAnswers: ["nomino"],
    explanation: "Aina za nomino ni kama: nomino za pekee (Nairobi), za kawaida (meza), na za dhahania (upendo).",
    marks: 1,
  },
  {
    id: 4,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Tumia kitenzi 'soma' katika nafsi ya kwanza (Mimi), wakati ujao.",
    answer: "nitasoma",
    acceptedAnswers: ["nitasoma", "mimi nitasoma", "nitasoma kitabu"],
    explanation: "Wakati ujao hutumia kiambishi '-ta-' kabla ya mzizi wa kitenzi.",
    marks: 1,
  },
  {
    id: 5,
    subject: "Kiswahili",
    topic: "Msamiati",
    question: "Kinyume cha neno 'mzuri' ni nini?",
    answer: "mbaya",
    acceptedAnswers: ["mbaya"],
    explanation: "Kinyume ni neno lenye maana inayopingana na neno lingine.",
    marks: 1,
  },
  {
    id: 6,
    subject: "Kiswahili",
    topic: "Fasihi",
    question: "Kazi ya fasihi andishi iliyo ndefu kuliko hadithi fupi na ina wahusika wengi inaitwaje?",
    answer: "riwaya",
    acceptedAnswers: ["riwaya", "tamthilia"],
    explanation: "Zote ni kazi za fasihi andishi lakini zinatofautiana katika urefu na upana wa maudhui.",
    marks: 1,
  },
  {
    id: 7,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Sehemu ya neno inayowekwa mbele ya mzizi inaitwaje?",
    answer: "kiambishi awali",
    acceptedAnswers: ["kiambishi awali", "kiambishi", "viambishi awali"],
    explanation: "Viambishi awali vinabeba taarifa kuhusu nafsi, wakati, na ukanushi. Mfano: 'a-na-som-a'.",
    marks: 2,
  },
  {
    id: 8,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Toa wingi wa neno 'kitabu'.",
    answer: "vitabu",
    acceptedAnswers: ["vitabu"],
    explanation: "Liko katika Ngeli ya KI-VI. Linaanza na 'ki-' umoja na 'vi-' wingi.",
    marks: 1,
  },
  {
    id: 9,
    subject: "Kiswahili",
    topic: "Ufahamu",
    question: "Nahau 'piga kelele' ina maana ya kufanya nini?",
    answer: "kupiga mayowe",
    acceptedAnswers: ["kupiga mayowe", "kupiga ukelele", "kufanya sauti kuu"],
    explanation: "Nahau ni msemo ambao maana yake haieleweki kimojawapo kwa kuangalia maneno yake.",
    marks: 1,
  },
  {
    id: 10,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Badilisha sentensi hii kuwa hali ya ukanushi: 'Amefika shuleni.'",
    answer: "hajafika shuleni",
    acceptedAnswers: ["hajafika shuleni", "hajafika shuleni."],
    explanation: "'A-me-' inabadilika kuwa 'ha-ja-' katika ukanushi wa wakati timilifu.",
    marks: 2,
  },
  {
    id: 11,
    subject: "Kiswahili",
    topic: "Msamiati",
    question: "Maneno yenye maana sawa, kama furaha na shangwe, huitwa?",
    answer: "visawe",
    acceptedAnswers: ["visawe", "kisawe"],
    explanation: "Visawe husaidia kuepuka kurudia maneno katika maandishi. Vinyume vinapingana.",
    marks: 1,
  },
  {
    id: 12,
    subject: "Kiswahili",
    topic: "Fasihi",
    question: "Mstari mmoja katika shairi huitwaje?",
    answer: "mshororo",
    acceptedAnswers: ["mshororo"],
    explanation: "Ushairi wa Kiswahili una kanuni kama mizani, vina, beti, na mishororo.",
    marks: 1,
  },
  {
    id: 13,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Maneno yanayoeleza kitendo, hali, au kuwepo (k.m. soma, cheza) huitwa?",
    answer: "vitenzi",
    acceptedAnswers: ["vitenzi", "kitenzi"],
    explanation: "Kuna aina tatu: Kitenzi kikuu, kisaidizi na kishirikishi.",
    marks: 1,
  },
  {
    id: 14,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Andika katika usemi wa taarifa: Mama alisema, \"Nipikieni chakula.\"",
    answer: "mama alisema wampikia chakula",
    acceptedAnswers: ["mama alisema wampikia chakula", "mama alisema wampikie chakula", "mama aliwaambia wampikie chakula"],
    explanation: "Katika usemi wa taarifa, alama za mtajo huondolewa, na kitenzi hubadilishwa.",
    marks: 2,
  },
  {
    id: 15,
    subject: "Kiswahili",
    topic: "Msamiati",
    question: "Neno 'shule' lina asili ya lugha gani?",
    answer: "kijerumani",
    acceptedAnswers: ["kijerumani", "kijerumani."],
    explanation: "Kiswahili kimekopa maneno kutoka lugha nyingi kama Kiarabu na Kiingereza.",
    marks: 1,
  },
  {
    id: 16,
    subject: "Kiswahili",
    topic: "Fasihi",
    question: "Tashbihi na sitiari ni aina za mbinu ipi ya lugha inayoongeza uzuri?",
    answer: "tamathali za usemi",
    acceptedAnswers: ["tamathali za usemi", "tamathali ya usemi"],
    explanation: "Ni mbinu inayotumia maneno kwa njia isiyo ya kawaida.",
    marks: 1,
  },
  {
    id: 17,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Neno linalofafanua kitenzi (k.m. 'haraka' katika 'alikimbia haraka') linaitwa nini?",
    answer: "kielezi",
    acceptedAnswers: ["kielezi", "vielezi"],
    explanation: "Vielezi vina aina kama wakati, mahali, namna, na kiasi.",
    marks: 1,
  },
  {
    id: 18,
    subject: "Kiswahili",
    topic: "Ufahamu",
    question: "Mti mkubwa huanguka na _____ kikubwa. (Kamilisha methali)",
    answer: "kishindo",
    acceptedAnswers: ["kishindo"],
    explanation: "Methali hii inamaanisha mtu mashuhuri anapokufa habari zake husikika kila mahali.",
    marks: 1,
  },
  {
    id: 19,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Onyesha mzizi wa neno 'wanachezana'.",
    answer: "chez",
    acceptedAnswers: ["chez", "-chez-"],
    explanation: "Viambishi vingine: wa-(nafsi), -na-(wakati), -an-(tendo), -a(kiishio).",
    marks: 1,
  },
  {
    id: 20,
    subject: "Kiswahili",
    topic: "Ufahamu",
    question: "Piga moyo _____ (nahau inayomaanisha kujitia ujasiri).",
    answer: "konde",
    acceptedAnswers: ["konde"],
    explanation: "Hii ni nahau inayotumika kueleza hali ya kujitia nguvu wakati wa magumu.",
    marks: 1,
  },
  {
    id: 21,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Sentensi inayoonyesha wazo moja pekee inaitwa sentensi gani?",
    answer: "sahili",
    acceptedAnswers: ["sahili", "sentensi sahili"],
    explanation: "Aina nyingine ni ambatano na changamano, kulingana na vishazi.",
    marks: 1,
  },
  {
    id: 22,
    subject: "Kiswahili",
    topic: "Fasihi",
    question: "Wazo kuu au ujumbe ambao mwandishi anataka kuufikisha kwenye kazi ya fasihi unaitwaje?",
    answer: "dhamira",
    acceptedAnswers: ["dhamira", "dhamira kuu", "ujumbe"],
    explanation: "Kazi mojawapo inaweza kuwa na dhamira kuu na dhamira ndogo ndogo.",
    marks: 1,
  },
  {
    id: 23,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Katika sentensi 'Chakula kilipikwa na Juma', kitenzi kiko katika hali gani?",
    answer: "kutendewa",
    acceptedAnswers: ["kutendewa", "hali ya kutendewa"],
    explanation: "Katika hali ya kutendewa, yambwa (chakula) inakuwa kiima, kitenzi kinapata kiambishi '-w-'.",
    marks: 1,
  },
  {
    id: 24,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Kishazi kisichoweza kujisimamia kama sentensi kamili kinaitwaje?",
    answer: "kishazi tegemezi",
    acceptedAnswers: ["kishazi tegemezi", "tegemezi"],
    explanation: "Kishazi huru kinajitegemea. Kishazi tegemezi hutumia viunganishi kama 'ambaye', 'ingawa'.",
    marks: 1,
  },
  {
    id: 25,
    subject: "Kiswahili",
    topic: "Ufahamu",
    question: "Tegua: 'Kuku wangu anataga miiba'.",
    answer: "mananasi",
    acceptedAnswers: ["mananasi", "nanasi"],
    explanation: "Vitendawili ni sehemu muhimu ya fasihi simulizi.",
    marks: 1,
  },
  {
    id: 26,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Kiambishi kinachoonyesha hali ya kuendelea (k.m. a-ki-soma) ni kiambishi kipi?",
    answer: "ki",
    acceptedAnswers: ["ki", "-ki-", "kiambishi ki"],
    explanation: "Pia hutumika kuonyesha masharti ama hali ya wakati mmoja nyuma.",
    marks: 1,
  },
  {
    id: 27,
    subject: "Kiswahili",
    topic: "Fasihi",
    question: "Ni fasihi ipi ambayo husimuliwa kwa mdomo kutoka kizazi hadi kizazi?",
    answer: "fasihi simulizi",
    acceptedAnswers: ["fasihi simulizi", "simulizi"],
    explanation: "Fasihi andishi huandikwa. Simulizi ni kongwe zaidi na hujumuisha nyimbo na methali.",
    marks: 1,
  },
  {
    id: 28,
    subject: "Kiswahili",
    topic: "Msamiati",
    question: "Maneno yenye maana zaidi ya moja, kama neno 'kata', huitwa?",
    answer: "polisemia",
    acceptedAnswers: ["polisemia", "vitawe"],
    explanation: "'Kata' yaweza kuwa kutenganisha kwa kisu, au eneo la utawala.",
    marks: 1,
  },
  {
    id: 29,
    subject: "Kiswahili",
    topic: "Sarufi",
    question: "Katika kuchanganua sentensi, Mwanafunzi mzuri alisoma kitabu, 'Mwanafunzi mzuri' ni sehemu gani?",
    answer: "kiima",
    acceptedAnswers: ["kiima"],
    explanation: "Uchanganuzi hugawanya sentensi kwa kiima (kikundi nomino) na kiarifu (kikundi tenzi).",
    marks: 1,
  },
  {
    id: 30,
    subject: "Kiswahili",
    topic: "Msamiati",
    question: "Maneno yanayotamkwa sawa lakini maana yake tofauti (k.m. 'taa' ya gari na 'taa' ya bahari) ni?",
    answer: "homofonii",
    acceptedAnswers: ["homofonii", "viada"],
    explanation: "Muktadha unaosaidia kuelewa tofauti kati ya maneno kama haya.",
    marks: 1,
  },
];

export default grade9Kiswahili;
