import type { Grade9Question } from "@/types";

const grade9History: Grade9Question[] = [
  {
    id: 1,
    subject: "History",
    topic: "Early Man",
    question: "Name three stages of early human evolution (in any order).",
    answer: "australopithecus, homo habilis, homo erectus",
    acceptedAnswers: [
      "australopithecus, homo habilis, homo erectus",
      "homo habilis, homo erectus, australopithecus",
      "homo erectus, australopithecus, homo habilis",
      "australopithecus, homo erectus, homo habilis",
      "homo sapiens, homo erectus, homo habilis",
    ],
    explanation: "Human evolution took place over millions of years in Africa, showing increased brain size, bipedalism, and tool-making ability.",
    marks: 2,
  },
  {
    id: 2,
    subject: "History",
    topic: "Government",
    question: "What is the system of government where the people have the power to elect their leaders called?",
    answer: "democracy",
    acceptedAnswers: ["democracy", "a democracy"],
    explanation: "Features include free and fair elections, rule of law, protection of human rights, and freedom of speech.",
    marks: 1,
  },
  {
    id: 3,
    subject: "History",
    topic: "Colonialism",
    question: "Name three European countries that colonized parts of Africa. (List separated by commas)",
    answer: "Britain, France, Germany",
    acceptedAnswers: [
      "britain, france, germany",
      "britain, france, and germany",
      "germany, britain, france",
      "portugal, belgium, italy",
      "britain, portugal, france",
    ],
    explanation: "The Berlin Conference formalized the 'Scramble for Africa' dividing the continent among European powers.",
    marks: 2,
  },
  {
    id: 4,
    subject: "History",
    topic: "Kenyan History",
    question: "In what year did Kenya gain independence from Britain?",
    answer: "1963",
    acceptedAnswers: ["1963", "12th december 1963", "december 12 1963", "12 dec 1963"],
    explanation: "Jomo Kenyatta was the first president. The struggle involved various leaders and the Mau Mau uprising.",
    marks: 1,
  },
  {
    id: 5,
    subject: "History",
    topic: "Trade",
    question: "Which historic trade network connected North Africa with West Africa across the desert?",
    answer: "trans-saharan trade",
    acceptedAnswers: ["trans-saharan trade", "trans saharan trade", "the trans-saharan trade", "trans saharan"],
    explanation: "Common goods traded included gold, salt, ivory, and slaves, mostly using camels as transport.",
    marks: 1,
  },
  {
    id: 6,
    subject: "History",
    topic: "World Wars",
    question: "The assassination of which Archduke sparked World War I?",
    answer: "franz ferdinand",
    acceptedAnswers: ["franz ferdinand", "archduke franz ferdinand"],
    explanation: "WWI lasted from 1914 to 1918. Other causes included militarism, alliances, imperialism, and nationalism.",
    marks: 1,
  },
  {
    id: 7,
    subject: "History",
    topic: "African Kingdoms",
    question: "Which pre-colonial African kingdom was located in modern-day Ethiopia/Eritrea?",
    answer: "aksum",
    acceptedAnswers: ["aksum", "kingdom of aksum", "axum", "kingdom of axum"],
    explanation: "Africa had many advanced civilizations with complex political systems, architecture, and cultural achievements.",
    marks: 1,
  },
  {
    id: 8,
    subject: "History",
    topic: "Constitution",
    question: "What is the supreme law of a country that outlines the structure of government and civil rights called?",
    answer: "constitution",
    acceptedAnswers: ["constitution", "a constitution", "the constitution"],
    explanation: "Kenya's current constitution was promulgated on 27th August 2010.",
    marks: 1,
  },
  {
    id: 9,
    subject: "History",
    topic: "Colonialism",
    question: "The artificial drawing of boundaries by European powers that divided ethnic groups in Africa is an effect of _____.",
    answer: "colonialism",
    acceptedAnswers: ["colonialism", "colonization"],
    explanation: "Other effects include loss of African land, racial discrimination, and destruction of traditional governance.",
    marks: 1,
  },
  {
    id: 10,
    subject: "History",
    topic: "Human Rights",
    question: "What term describes the fundamental freedoms that every person is naturally entitled to?",
    answer: "human rights",
    acceptedAnswers: ["human rights"],
    explanation: "Examples include right to life and education. The Universal Declaration of Human Rights was adopted in 1948.",
    marks: 1,
  },
  {
    id: 11,
    subject: "History",
    topic: "Nationalism",
    question: "What is the term for the desire of a people to govern themselves and preserve their identity?",
    answer: "nationalism",
    acceptedAnswers: ["nationalism", "african nationalism"],
    explanation: "It led Africans to form political parties to demand independence. Key leaders include Jomo Kenyatta and Kwame Nkrumah.",
    marks: 1,
  },
  {
    id: 12,
    subject: "History",
    topic: "Kenyan History",
    question: "Which armed rebellion by Kenyan Africans against British colonial rule took place from 1952-1960?",
    answer: "mau mau",
    acceptedAnswers: ["mau mau", "mau mau uprising", "the mau mau rebellion", "mau mau rebellion"],
    explanation: "Key figures included Dedan Kimathi and Waruhiu Itote. They fought for land and freedom.",
    marks: 1,
  },
  {
    id: 13,
    subject: "History",
    topic: "Trade",
    question: "Which trade network led to the development of Swahili culture and language on the East African coast?",
    answer: "indian ocean trade",
    acceptedAnswers: ["indian ocean trade", "the indian ocean trade"],
    explanation: "It connected East Africa, Arabia, India, and China. Coastal towns like Mombasa became major trade centers.",
    marks: 1,
  },
  {
    id: 14,
    subject: "History",
    topic: "Government",
    question: "The principle that divides government into Executive, Legislature, and Judiciary to prevent abuse of power is called _____ of powers.",
    answer: "separation",
    acceptedAnswers: ["separation", "separation of powers"],
    explanation: "This concept was developed by Montesquieu, introducing checks and balances.",
    marks: 1,
  },
  {
    id: 15,
    subject: "History",
    topic: "World Wars",
    question: "The formation of which international organization in 1945 accelerated decolonization in Africa?",
    answer: "united nations",
    acceptedAnswers: ["united nations", "the united nations", "un", "the un"],
    explanation: "After WWII, the UN promoted self-determination for colonized peoples.",
    marks: 1,
  },
  {
    id: 16,
    subject: "History",
    topic: "Early Man",
    question: "Which continent is referred to as the 'Cradle of Humankind' because the earliest human fossils were found there?",
    answer: "africa",
    acceptedAnswers: ["africa"],
    explanation: "Key discoveries include fossils at Olduvai Gorge and Koobi Fora.",
    marks: 1,
  },
  {
    id: 17,
    subject: "History",
    topic: "Kenyan History",
    question: "Which arm of the Kenyan government is responsible for making laws?",
    answer: "legislature",
    acceptedAnswers: ["legislature", "the legislature", "parliament"],
    explanation: "The other two arms are the Executive (implements laws) and Judiciary (interprets laws).",
    marks: 1,
  },
  {
    id: 18,
    subject: "History",
    topic: "African Kingdoms",
    question: "Which ancient African kingdom is famous for building massive stone pyramids as tombs for pharaohs?",
    answer: "egypt",
    acceptedAnswers: ["egypt", "kingdom of egypt", "ancient egypt"],
    explanation: "They demonstrated advanced engineering, mathematics, medicine, and hieroglyphic writing.",
    marks: 1,
  },
  {
    id: 19,
    subject: "History",
    topic: "Colonialism",
    question: "In what European city was the 1884-1885 conference held that set the rules for the colonization of Africa?",
    answer: "berlin",
    acceptedAnswers: ["berlin", "the berlin conference"],
    explanation: "No African leaders were invited. Boundaries were drawn without considering ethnic groups.",
    marks: 1,
  },
  {
    id: 20,
    subject: "History",
    topic: "Government",
    question: "What is the transfer of power and resources from the national government to lower levels (counties) called?",
    answer: "devolution",
    acceptedAnswers: ["devolution"],
    explanation: "In Kenya, devolution introduced 47 county governments to bring services closer to the people.",
    marks: 1,
  },
  {
    id: 21,
    subject: "History",
    topic: "Trade",
    question: "Which ocean did the slave trade cross from Africa to the Americas?",
    answer: "atlantic",
    acceptedAnswers: ["atlantic", "atlantic ocean", "trans-atlantic"],
    explanation: "The Trans-Atlantic slave trade caused massive depopulation and family breakdowns in Africa.",
    marks: 1,
  },
  {
    id: 22,
    subject: "History",
    topic: "Nationalism",
    question: "What organization was formed in 1963 to promote unity among African states (replaced by AU in 2002)?",
    answer: "oau",
    acceptedAnswers: ["oau", "organisation of african unity", "organization of african unity"],
    explanation: "It supported decolonization and coordinated political and economic cooperation.",
    marks: 1,
  },
  {
    id: 23,
    subject: "History",
    topic: "Kenyan History",
    question: "A famous group of six Kenyan nationalists, including Jomo Kenyatta, tried in 1952 are known as the _____ Six.",
    answer: "kapenguria",
    acceptedAnswers: ["kapenguria", "kapenguria six"],
    explanation: "The trial was widely seen as politically motivated to suppress the Mau Mau movement.",
    marks: 1,
  },
  {
    id: 24,
    subject: "History",
    topic: "Human Rights",
    question: "Which Kenyan commission investigates human rights violations and educates the public? (Abbreviation)",
    answer: "knhrc",
    acceptedAnswers: ["knhrc", "kenya national human rights commission"],
    explanation: "It is an independent body established under Chapter 15 of the Constitution.",
    marks: 1,
  },
  {
    id: 25,
    subject: "History",
    topic: "Government",
    question: "What system of government shares power between a central national government and regional/state governments?",
    answer: "federal",
    acceptedAnswers: ["federal", "federal system"],
    explanation: "In a unitary system, power is concentrated centrally. The USA is federal, while Kenya is quasi-federal due to devolution.",
    marks: 1,
  },
  {
    id: 26,
    subject: "History",
    topic: "Early Man",
    question: "During which 'Age' did early man primarily use tools made of rock?",
    answer: "stone age",
    acceptedAnswers: ["stone age", "stone", "the stone age"],
    explanation: "The Stone Age is divided into Old (crude tools), Middle, and New (polished tools).",
    marks: 1,
  },
  {
    id: 27,
    subject: "History",
    topic: "World Wars",
    question: "What does 'UN' stand for?",
    answer: "united nations",
    acceptedAnswers: ["united nations", "the united nations"],
    explanation: "Formed in 1945 to maintain international peace and security and foster social dev.",
    marks: 1,
  },
  {
    id: 28,
    subject: "History",
    topic: "Kenyan History",
    question: "Chapter 4 of the Kenyan Constitution, which lists the fundamental freedoms of every person, is called the Bill of _____.",
    answer: "rights",
    acceptedAnswers: ["rights", "bill of rights"],
    explanation: "It includes the right to life, equality, privacy, and freedom of expression.",
    marks: 1,
  },
  {
    id: 29,
    subject: "History",
    topic: "Colonialism",
    question: "Which method of colonial rule did the British primarily use, involving traditional African leaders as intermediaries?",
    answer: "indirect rule",
    acceptedAnswers: ["indirect rule", "indirect"],
    explanation: "The French used direct rule and a policy of assimilation.",
    marks: 1,
  },
  {
    id: 30,
    subject: "History",
    topic: "Trade",
    question: "What is the direct exchange of goods for other goods without using money called?",
    answer: "barter trade",
    acceptedAnswers: ["barter", "barter trade", "bartering"],
    explanation: "A disadvantage is the difficulty in finding someone with a matching want (double coincidence of wants).",
    marks: 1,
  },
];

export default grade9History;
