import type { Grade9Question } from "@/types";

const grade9ComputerStudies: Grade9Question[] = [
  {
    id: 1,
    subject: "Computer Studies",
    topic: "Introduction",
    question: "What is an electronic device that accepts data, processes it, and produces information called?",
    answer: "computer",
    acceptedAnswers: ["computer", "a computer"],
    explanation: "Computers follow a cycle: Input → Processing → Output → Storage. They have transformed every aspect of modern life.",
    marks: 1,
  },
  {
    id: 2,
    subject: "Computer Studies",
    topic: "Hardware",
    question: "What term refers to the physical, tangible components of a computer (e.g., monitor, keyboard)?",
    answer: "hardware",
    acceptedAnswers: ["hardware", "computer hardware"],
    explanation: "Hardware cannot function without software, and software needs hardware to run on. Together they make the computer functional.",
    marks: 1,
  },
  {
    id: 3,
    subject: "Computer Studies",
    topic: "Hardware",
    question: "Which input device is primarily used to type text, numbers, and commands into the computer?",
    answer: "keyboard",
    acceptedAnswers: ["keyboard", "a keyboard", "the keyboard"],
    explanation: "Input devices allow users to enter data and instructions. Other input devices include mice, scanners, touchscreens, and microphones.",
    marks: 1,
  },
  {
    id: 4,
    subject: "Computer Studies",
    topic: "Hardware",
    question: "Which output device displays visual output to the user?",
    answer: "monitor",
    acceptedAnswers: ["monitor", "a monitor", "screen", "the monitor", "display"],
    explanation: "Output devices present processed data to the user. Others include printers (hard copy) and speakers (audio).",
    marks: 1,
  },
  {
    id: 5,
    subject: "Computer Studies",
    topic: "Software",
    question: "What type of system software manages computer hardware and resources, such as Windows or Linux?",
    answer: "operating system",
    acceptedAnswers: ["operating system", "os", "an operating system", "the operating system"],
    explanation: "The OS acts as an intermediary between the user and hardware. Functions include file and memory management.",
    marks: 1,
  },
  {
    id: 6,
    subject: "Computer Studies",
    topic: "Data Processing",
    question: "Raw, unprocessed facts and figures are called data. What is data called after it has been processed to become meaningful?",
    answer: "information",
    acceptedAnswers: ["information"],
    explanation: "The computer processes data into information through sorting, calculating, and organizing. Information is useful for decision-making.",
    marks: 1,
  },
  {
    id: 7,
    subject: "Computer Studies",
    topic: "Storage",
    question: "Is a Hard Disk Drive (HDD) considered primary or secondary storage?",
    answer: "secondary",
    acceptedAnswers: ["secondary", "secondary storage"],
    explanation: "Primary storage (RAM, ROM) is directly accessed by the CPU. Secondary storage (HDD, SSD, USB) stores data permanently.",
    marks: 1,
  },
  {
    id: 8,
    subject: "Computer Studies",
    topic: "Networks",
    question: "What does the acronym LAN stand for?",
    answer: "local area network",
    acceptedAnswers: ["local area network"],
    explanation: "A LAN covers a small area (school, office). A WAN (Wide Area Network) covers a large area (cities, countries).",
    marks: 1,
  },
  {
    id: 9,
    subject: "Computer Studies",
    topic: "Internet",
    question: "What is the global network of interconnected computers called?",
    answer: "internet",
    acceptedAnswers: ["internet", "the internet", "world wide web", "www"],
    explanation: "The internet is used for communication, research, and e-commerce. It was developed from ARPANET in the 1960s.",
    marks: 1,
  },
  {
    id: 10,
    subject: "Computer Studies",
    topic: "Security",
    question: "What is a malicious program that replicates itself and can damage files or disrupt system operations called?",
    answer: "virus",
    acceptedAnswers: ["virus", "computer virus", "a virus", "malware"],
    explanation: "Prevention includes using antivirus software and avoiding unknown attachments.",
    marks: 1,
  },
  {
    id: 11,
    subject: "Computer Studies",
    topic: "Software",
    question: "Software designed to perform specific user tasks (like Microsoft Word or Google Chrome) is called _____ software.",
    answer: "application",
    acceptedAnswers: ["application", "application software", "app", "apps"],
    explanation: "System software manages the computer, while application software performs tasks for the user.",
    marks: 1,
  },
  {
    id: 12,
    subject: "Computer Studies",
    topic: "Data Processing",
    question: "In the data processing cycle, what step comes immediately after 'Input'?",
    answer: "processing",
    acceptedAnswers: ["processing"],
    explanation: "The cycle is: Input → Processing → Output → Storage (and Feedback).",
    marks: 1,
  },
  {
    id: 13,
    subject: "Computer Studies",
    topic: "Hardware",
    question: "What acronym represents the 'brain' of the computer where processing takes place?",
    answer: "cpu",
    acceptedAnswers: ["cpu", "central processing unit"],
    explanation: "The CPU consists of the Arithmetic Logic Unit (ALU), Control Unit (CU), and registers.",
    marks: 1,
  },
  {
    id: 14,
    subject: "Computer Studies",
    topic: "Number Systems",
    question: "Convert the binary number 1010 to decimal.",
    answer: "10",
    acceptedAnswers: ["10", "ten"],
    explanation: "Binary uses base 2. 1010 = (1×8) + (0×4) + (1×2) + (0×1) = 10.",
    marks: 2,
  },
  {
    id: 15,
    subject: "Computer Studies",
    topic: "Security",
    question: "What is the term for using digital devices to harass, threaten, or embarrass someone online?",
    answer: "cyberbullying",
    acceptedAnswers: ["cyberbullying", "cyber bullying", "online bullying"],
    explanation: "To deal with it, block the bully and report them to a trusted adult or the platform.",
    marks: 1,
  },
  {
    id: 16,
    subject: "Computer Studies",
    topic: "Internet",
    question: "A software program like Google or Bing that retrieves information from the internet based on keywords is called a _____ engine.",
    answer: "search",
    acceptedAnswers: ["search", "search engine"],
    explanation: "Search engines use algorithms to index and rank web pages.",
    marks: 1,
  },
  {
    id: 17,
    subject: "Computer Studies",
    topic: "Software",
    question: "System software manages hardware. What type of software is installed by users for specific tasks like playing games or typing?",
    answer: "application software",
    acceptedAnswers: ["application software", "application", "app", "apps"],
    explanation: "System software runs in the background. Application software is for specific user tasks.",
    marks: 1,
  },
  {
    id: 18,
    subject: "Computer Studies",
    topic: "Storage",
    question: "Which type of primary memory is volatile, meaning data is lost when the power is turned off?",
    answer: "ram",
    acceptedAnswers: ["ram", "random access memory"],
    explanation: "ROM (Read Only Memory) is non-volatile; data is permanent and retained when power is off.",
    marks: 1,
  },
  {
    id: 19,
    subject: "Computer Studies",
    topic: "Networks",
    question: "What wireless networking technology allows devices to connect to the internet using radio waves?",
    answer: "wi-fi",
    acceptedAnswers: ["wi-fi", "wifi", "wireless fidelity"],
    explanation: "Devices connect through a wireless router, providing convenience and mobility.",
    marks: 1,
  },
  {
    id: 20,
    subject: "Computer Studies",
    topic: "Ethics",
    question: "What is the illegal copying, distribution, or use of copyrighted software without proper licensing called?",
    answer: "software piracy",
    acceptedAnswers: ["software piracy", "piracy"],
    explanation: "It violates intellectual property rights and is a criminal offense in many countries.",
    marks: 1,
  },
  {
    id: 21,
    subject: "Computer Studies",
    topic: "Data Processing",
    question: "What type of software tool organizes data in rows and columns for calculations (e.g., Microsoft Excel)?",
    answer: "spreadsheet",
    acceptedAnswers: ["spreadsheet", "spreadsheets"],
    explanation: "Spreadsheets use cells and support formulas, functions, and charting.",
    marks: 1,
  },
  {
    id: 22,
    subject: "Computer Studies",
    topic: "Hardware",
    question: "External hardware connected to the computer to extend its functionality (like a printer or mouse) is called a _____ device.",
    answer: "peripheral",
    acceptedAnswers: ["peripheral", "peripheral device", "peripherals"],
    explanation: "Peripherals communicate with the CPU through ports and cables.",
    marks: 1,
  },
  {
    id: 23,
    subject: "Computer Studies",
    topic: "Internet",
    question: "What does the 'e' in e-mail stand for?",
    answer: "electronic",
    acceptedAnswers: ["electronic"],
    explanation: "Email provides instant digital messaging and the ability to send attachments.",
    marks: 1,
  },
  {
    id: 24,
    subject: "Computer Studies",
    topic: "Security",
    question: "What is a secret string of characters used to authenticate a user's identity called?",
    answer: "password",
    acceptedAnswers: ["password", "a password"],
    explanation: "Strong passwords contain mixed cases, numbers, and symbols.",
    marks: 1,
  },
  {
    id: 25,
    subject: "Computer Studies",
    topic: "Number Systems",
    question: "Convert the decimal number 15 to binary.",
    answer: "1111",
    acceptedAnswers: ["1111"],
    explanation: "15÷2=7 R1, 7÷2=3 R1, 3÷2=1 R1, 1÷2=0 R1. Remainders read bottom to top: 1111.",
    marks: 2,
  },
  {
    id: 26,
    subject: "Computer Studies",
    topic: "Software",
    question: "Microsoft Word is an example of what type of software application?",
    answer: "word processor",
    acceptedAnswers: ["word processor", "word processing", "word processing software"],
    explanation: "Word processors are used for creating, editing, and formatting text documents.",
    marks: 1,
  },
  {
    id: 27,
    subject: "Computer Studies",
    topic: "Networks",
    question: "What are the rules governing data transmission over a network called?",
    answer: "protocols",
    acceptedAnswers: ["protocols", "protocol"],
    explanation: "An example is TCP/IP. Data communication involves a sender, receiver, message, medium, and protocol.",
    marks: 1,
  },
  {
    id: 28,
    subject: "Computer Studies",
    topic: "Ethics",
    question: "Moral guidelines for the responsible use of computers are known as computer _____.",
    answer: "ethics",
    acceptedAnswers: ["ethics"],
    explanation: "Examples include respecting privacy, avoiding plagiarism, and not hacking.",
    marks: 1,
  },
  {
    id: 29,
    subject: "Computer Studies",
    topic: "Hardware",
    question: "Which type of storage drive is faster and more durable because it uses flash memory chips instead of spinning disks?",
    answer: "ssd",
    acceptedAnswers: ["ssd", "solid state drive", "solid-state drive"],
    explanation: "An HDD (Hard Disk Drive) uses spinning magnetic disks, making it slower but cheaper.",
    marks: 1,
  },
  {
    id: 30,
    subject: "Computer Studies",
    topic: "Internet",
    question: "Storing and accessing data and programs over the internet instead of on your computer's local hard drive is called _____ computing.",
    answer: "cloud",
    acceptedAnswers: ["cloud", "cloud computing"],
    explanation: "Examples include Google Drive and Dropbox. It enables access from anywhere.",
    marks: 1,
  },
];

export default grade9ComputerStudies;
