import type { Grade9Question } from "@/types";

const grade9Physics: Grade9Question[] = [
  {
    id: 1,
    subject: "Physics",
    topic: "Forces",
    question: "What is the SI unit of force?",
    answer: "newton",
    acceptedAnswers: ["newton", "n", "newtons"],
    explanation: "Force is a push or pull. It is a vector quantity, measured using a spring balance or force meter.",
    marks: 1,
  },
  {
    id: 2,
    subject: "Physics",
    topic: "Energy",
    question: "Which law states that energy cannot be created or destroyed, only transformed from one form to another?",
    answer: "law of conservation of energy",
    acceptedAnswers: [
      "law of conservation of energy",
      "conservation of energy",
      "the law of conservation of energy",
    ],
    explanation: "The total energy in a closed system remains constant.",
    marks: 2,
  },
  {
    id: 3,
    subject: "Physics",
    topic: "Electricity",
    question: "In what type of circuit are components connected end to end in one path, such that the current is the same throughout?",
    answer: "series",
    acceptedAnswers: ["series", "series circuit"],
    explanation: "In a parallel circuit, components are connected in separate branches, so voltage is the same across each branch.",
    marks: 1,
  },
  {
    id: 4,
    subject: "Physics",
    topic: "Motion",
    question: "A car travels 150 km in 3 hours. Calculate its average speed in km/h.",
    answer: "50",
    acceptedAnswers: ["50", "50 km/h", "50km/h"],
    explanation: "Speed = Distance ÷ Time = 150 km ÷ 3 h = 50 km/h.",
    marks: 2,
  },
  {
    id: 5,
    subject: "Physics",
    topic: "Heat",
    question: "Name the three methods of heat transfer. (List separated by commas)",
    answer: "conduction, convection, radiation",
    acceptedAnswers: [
      "conduction, convection, radiation",
      "convection, conduction, radiation",
      "radiation, convection, conduction",
      "conduction, radiation, convection",
      "conduction, convection, and radiation",
    ],
    explanation: "Conduction (solids), convection (fluids), and radiation (electromagnetic waves).",
    marks: 3,
  },
  {
    id: 6,
    subject: "Physics",
    topic: "Light",
    question: "According to the laws of reflection, the angle of incidence equals the angle of _____.",
    answer: "reflection",
    acceptedAnswers: ["reflection"],
    explanation: "The incident ray, reflected ray, and the normal all lie in the same plane.",
    marks: 1,
  },
  {
    id: 7,
    subject: "Physics",
    topic: "Forces",
    question: "What physical quantity represents the amount of matter in an object and is constant everywhere?",
    answer: "mass",
    acceptedAnswers: ["mass"],
    explanation: "Weight is the force of gravity on an object and varies with location (W = mg).",
    marks: 1,
  },
  {
    id: 8,
    subject: "Physics",
    topic: "Waves",
    question: "What wave property represents the maximum displacement of particles from their rest position?",
    answer: "amplitude",
    acceptedAnswers: ["amplitude"],
    explanation: "Wavelength is the distance between identical points. Frequency is waves per second.",
    marks: 1,
  },
  {
    id: 9,
    subject: "Physics",
    topic: "Electricity",
    question: "What formula expresses Ohm's Law relationship between voltage V, current I, and resistance R?",
    answer: "v = ir",
    acceptedAnswers: ["v = ir", "v=ir", "i = v/r", "i=v/r", "r = v/i", "r=v/i"],
    explanation: "Ohm's Law states current is directly proportional to voltage, provided temperature is constant.",
    marks: 2,
  },
  {
    id: 10,
    subject: "Physics",
    topic: "Pressure",
    question: "What is the SI unit of pressure?",
    answer: "pascal",
    acceptedAnswers: ["pascal", "pa", "n/m2", "n/m²", "newtons per square meter"],
    explanation: "Pressure is force acting per unit area (P = F/A). 1 Pa = 1 N/m².",
    marks: 1,
  },
  {
    id: 11,
    subject: "Physics",
    topic: "Motion",
    question: "A car increases its velocity from 10 m/s to 30 m/s in 5 seconds. Calculate the acceleration in m/s².",
    answer: "4",
    acceptedAnswers: ["4", "4 m/s2", "4m/s2", "4 m/s²", "4m/s²"],
    explanation: "Acceleration = (final velocity - initial velocity) / time = (30-10)/5 = 20/5 = 4 m/s².",
    marks: 2,
  },
  {
    id: 12,
    subject: "Physics",
    topic: "Energy",
    question: "What form of energy is associated with motion?",
    answer: "kinetic",
    acceptedAnswers: ["kinetic", "kinetic energy"],
    explanation: "Other forms include potential, thermal, light, electrical, sound, and chemical.",
    marks: 1,
  },
  {
    id: 13,
    subject: "Physics",
    topic: "Forces",
    question: "Which of Newton's laws is also called the law of inertia?",
    answer: "first law",
    acceptedAnswers: ["first law", "newton's first law", "first", "1st", "1st law", "newton's 1st law"],
    explanation: "An object at rest stays at rest, and an object in motion stays in motion unless acted upon by a force.",
    marks: 1,
  },
  {
    id: 14,
    subject: "Physics",
    topic: "Light",
    question: "What is the bending of light as it passes from one medium to another of different density called?",
    answer: "refraction",
    acceptedAnswers: ["refraction", "refraction of light"],
    explanation: "Light bends because its speed changes when moving between media.",
    marks: 1,
  },
  {
    id: 15,
    subject: "Physics",
    topic: "Magnetism",
    question: "Name two magnetic materials. (Format: x, y)",
    answer: "iron, steel",
    acceptedAnswers: [
      "iron, steel", "iron, cobalt", "iron, nickel",
      "steel, iron", "cobalt, iron", "nickel, iron",
      "steel, cobalt", "nickel, steel", "iron and steel",
    ],
    explanation: "Magnets attract magnetic materials like iron, steel, nickel, and cobalt.",
    marks: 2,
  },
  {
    id: 16,
    subject: "Physics",
    topic: "Electricity",
    question: "Calculate the resistance in ohms of a conductor if a voltage of 12V produces a current of 3A.",
    answer: "4",
    acceptedAnswers: ["4", "4 ohms", "4Ω", "4 ohm", "two"],
    explanation: "R = V/I = 12/3 = 4 ohms.",
    marks: 2,
  },
  {
    id: 17,
    subject: "Physics",
    topic: "Heat",
    question: "What is the heat required to raise the temperature of 1 kg of a substance by 1°C called? (Specific _____ capacity)",
    answer: "heat",
    acceptedAnswers: ["heat", "specific heat", "specific heat capacity"],
    explanation: "Formula: Q = mcΔT. Water has a high specific heat capacity.",
    marks: 1,
  },
  {
    id: 18,
    subject: "Physics",
    topic: "Waves",
    question: "In which type of wave do particles vibrate parallel to the direction of energy transfer (e.g., sound waves)?",
    answer: "longitudinal",
    acceptedAnswers: ["longitudinal", "longitudinal wave", "longitudinal waves"],
    explanation: "In transverse waves, particles vibrate perpendicular to energy transfer.",
    marks: 1,
  },
  {
    id: 19,
    subject: "Physics",
    topic: "Pressure",
    question: "A sharp knife cuts better than a blunt one because it has a smaller contact area, producing greater _____.",
    answer: "pressure",
    acceptedAnswers: ["pressure"],
    explanation: "Since Pressure = Force/Area, a smaller area produces greater pressure with the same force.",
    marks: 1,
  },
  {
    id: 20,
    subject: "Physics",
    topic: "Forces",
    question: "What is the force that opposes motion between surfaces in contact called?",
    answer: "friction",
    acceptedAnswers: ["friction"],
    explanation: "It enables walking but causes wear and tear. It converts kinetic energy to heat.",
    marks: 1,
  },
  {
    id: 21,
    subject: "Physics",
    topic: "Energy",
    question: "Calculate the kinetic energy of a 2 kg ball moving at 5 m/s. (Enter amount in Joules)",
    answer: "25",
    acceptedAnswers: ["25", "25j", "25 j", "25 joules"],
    explanation: "KE = ½mv² = ½ × 2 × 5² = ½ × 2 × 25 = 25 J.",
    marks: 2,
  },
  {
    id: 22,
    subject: "Physics",
    topic: "Light",
    question: "What is the acronym used for the seven colors of the visible spectrum in order?",
    answer: "roygbiv",
    acceptedAnswers: ["roygbiv"],
    explanation: "Red, Orange, Yellow, Green, Blue, Indigo, Violet. White light from the sun is composed of these.",
    marks: 1,
  },
  {
    id: 23,
    subject: "Physics",
    topic: "Electricity",
    question: "What safety device in an electrical circuit melts and breaks the circuit when current exceeds a safe level?",
    answer: "fuse",
    acceptedAnswers: ["fuse", "a fuse"],
    explanation: "Fuses are rated in amperes and protect appliances from damage or fire.",
    marks: 1,
  },
  {
    id: 24,
    subject: "Physics",
    topic: "Motion",
    question: "Speed is a scalar quantity. What is the corresponding vector quantity (rate of change of displacement)?",
    answer: "velocity",
    acceptedAnswers: ["velocity"],
    explanation: "Velocity has both magnitude and direction.",
    marks: 1,
  },
  {
    id: 25,
    subject: "Physics",
    topic: "Magnetism",
    question: "What is a temporary magnet made by passing electric current through a coil of wire wound around an iron core called?",
    answer: "electromagnet",
    acceptedAnswers: ["electromagnet", "an electromagnet"],
    explanation: "They are used in electric bells and cranes for lifting magnetic waste.",
    marks: 1,
  },
  {
    id: 26,
    subject: "Physics",
    topic: "Forces",
    question: "According to Newton's Third Law, for every action, there is an equal and _____ reaction.",
    answer: "opposite",
    acceptedAnswers: ["opposite"],
    explanation: "For example, when a rocket expels gas downward, the gas pushes the rocket upward.",
    marks: 1,
  },
  {
    id: 27,
    subject: "Physics",
    topic: "Heat",
    question: "What is the specific temperature at which a solid changes to a liquid called?",
    answer: "melting point",
    acceptedAnswers: ["melting point", "the melting point"],
    explanation: "During a change of state, the temperature remains constant.",
    marks: 1,
  },
  {
    id: 28,
    subject: "Physics",
    topic: "Waves",
    question: "What is the speed in m/s of a wave with frequency 50 Hz and wavelength 2 m?",
    answer: "100",
    acceptedAnswers: ["100", "100 m/s", "100m/s"],
    explanation: "The wave equation v = fλ relates the speed, frequency, and wavelength.",
    marks: 2,
  },
  {
    id: 29,
    subject: "Physics",
    topic: "Energy",
    question: "Energy sources that are naturally replenished and will not run out (e.g., solar, wind) are called _____ energy.",
    answer: "renewable",
    acceptedAnswers: ["renewable"],
    explanation: "Other renewable sources include hydroelectric, geothermal, and biomass.",
    marks: 1,
  },
  {
    id: 30,
    subject: "Physics",
    topic: "Electricity",
    question: "What is the flow of electric charge (electrons) through a conductor called?",
    answer: "current",
    acceptedAnswers: ["current", "electric current"],
    explanation: "Its SI unit is the Ampere (A). It is measured using an ammeter.",
    marks: 1,
  },
];

export default grade9Physics;
