import type { Grade9Question } from "@/types";

const grade9Biology: Grade9Question[] = [
  {
    id: 1,
    subject: "Biology",
    topic: "Cell Biology",
    question: "Name three organelles found in a plant cell but not in an animal cell. (List separated by commas)",
    answer: "cell wall, chloroplasts, large central vacuole",
    acceptedAnswers: [
      "cell wall, chloroplasts, large central vacuole",
      "cell wall, chloroplasts, and large central vacuole",
      "cell wall, chloroplasts, vacuole",
      "chloroplasts, cell wall, large central vacuole",
      "vacuole, cell wall, chloroplasts",
      "cell wall, vacuole, chloroplasts",
    ],
    explanation: "Plant cells have a rigid cell wall for support, chloroplasts for photosynthesis, and a large central vacuole for storage and maintaining turgor pressure.",
    marks: 3,
  },
  {
    id: 2,
    subject: "Biology",
    topic: "Cell Biology",
    question: "Which cell organelle is the site of cellular respiration and produces energy (ATP)?",
    answer: "mitochondria",
    acceptedAnswers: [
      "mitochondria",
      "mitochondrion",
      "the mitochondria",
    ],
    explanation: "They break down glucose in the presence of oxygen to release energy. They are often called the 'powerhouse of the cell'.",
    marks: 2,
  },
  {
    id: 3,
    subject: "Biology",
    topic: "Nutrition",
    question: "What is the term for the process by which green plants make their own food using sunlight?",
    answer: "photosynthesis",
    acceptedAnswers: [
      "photosynthesis",
    ],
    explanation: "Photosynthesis is the process by which green plants make food using carbon dioxide, water, sunlight, and chlorophyll.",
    marks: 3,
  },
  {
    id: 4,
    subject: "Biology",
    topic: "Transport",
    question: "What is the movement of water molecules from a region of higher water concentration to lower water concentration through a semi-permeable membrane called?",
    answer: "osmosis",
    acceptedAnswers: [
      "osmosis",
    ],
    explanation: "It is a special type of diffusion that involves only water molecules. It is important in maintaining cell turgor in plants.",
    marks: 2,
  },
  {
    id: 5,
    subject: "Biology",
    topic: "Respiration",
    question: "Which type of respiration requires oxygen to break down glucose?",
    answer: "aerobic",
    acceptedAnswers: [
      "aerobic",
      "aerobic respiration",
    ],
    explanation: "Aerobic respiration requires oxygen and produces CO₂, water, and more energy. Anaerobic respiration does not require oxygen and produces less energy.",
    marks: 3,
  },
  {
    id: 6,
    subject: "Biology",
    topic: "Genetics",
    question: "What is a segment of DNA that codes for a specific protein or trait called?",
    answer: "gene",
    acceptedAnswers: [
      "gene",
      "a gene",
    ],
    explanation: "Humans have 46 chromosomes (23 pairs). Each chromosome contains hundreds to thousands of genes.",
    marks: 2,
  },
  {
    id: 7,
    subject: "Biology",
    topic: "Ecology",
    question: "What term describes a community of living organisms interacting with their non-living environment?",
    answer: "ecosystem",
    acceptedAnswers: [
      "ecosystem",
      "an ecosystem",
    ],
    explanation: "Components of an ecosystem are biotic (living) and abiotic (non-living). Biotic factors include plants, animals, and microorganisms. Abiotic factors include temperature, water, light, and soil.",
    marks: 2,
  },
  {
    id: 8,
    subject: "Biology",
    topic: "Human Body",
    question: "Name the two lower chambers of the human heart.",
    answer: "right and left ventricles",
    acceptedAnswers: [
      "right and left ventricles",
      "right ventricle and left ventricle",
      "left and right ventricles",
      "ventricles",
      "left ventricle, right ventricle",
    ],
    explanation: "The heart has four chambers: right atrium, left atrium, right ventricle, and left ventricle. The atria receive blood while the ventricles pump blood out.",
    marks: 2,
  },
  {
    id: 9,
    subject: "Biology",
    topic: "Classification",
    question: "In biological classification, what is the level just below 'Kingdom'?",
    answer: "phylum",
    acceptedAnswers: [
      "phylum",
    ],
    explanation: "The seven levels of classification are Kingdom, Phylum, Class, Order, Family, Genus, Species.",
    marks: 3,
  },
  {
    id: 10,
    subject: "Biology",
    topic: "Nutrition",
    question: "What are biological catalysts that speed up chemical reactions in living organisms called?",
    answer: "enzymes",
    acceptedAnswers: [
      "enzymes",
      "enzyme",
    ],
    explanation: "Enzymes are specific — each enzyme acts on a particular substrate. They work best at optimum temperature and pH.",
    marks: 3,
  },
  {
    id: 11,
    subject: "Biology",
    topic: "Transport",
    question: "What protein in red blood cells binds to oxygen for transport?",
    answer: "haemoglobin",
    acceptedAnswers: [
      "haemoglobin",
      "hemoglobin",
    ],
    explanation: "Red blood cells are biconcave in shape to increase surface area for gas exchange. They have no nucleus to allow more space for haemoglobin.",
    marks: 2,
  },
  {
    id: 12,
    subject: "Biology",
    topic: "Reproduction",
    question: "What is the transfer of pollen from the anther to the stigma called?",
    answer: "pollination",
    acceptedAnswers: [
      "pollination",
    ],
    explanation: "Pollination must occur before fertilization (the fusion of the male gamete with the female gamete). Pollination can be by wind, insects, or other agents.",
    marks: 3,
  },
  {
    id: 13,
    subject: "Biology",
    topic: "Cell Biology",
    question: "What is the movement of particles from a region of higher concentration to a region of lower concentration called?",
    answer: "diffusion",
    acceptedAnswers: [
      "diffusion",
      "simple diffusion",
    ],
    explanation: "Diffusion is a passive process — it does not require energy. It continues until equilibrium is reached.",
    marks: 2,
  },
  {
    id: 14,
    subject: "Biology",
    topic: "Ecology",
    question: "What represents the linear flow of energy from one organism to another in an ecosystem?",
    answer: "food chain",
    acceptedAnswers: [
      "food chain",
      "a food chain",
    ],
    explanation: "Example: Grass -> Grasshopper -> Frog -> Snake -> Eagle. Energy decreases at each trophic level.",
    marks: 2,
  },
  {
    id: 15,
    subject: "Biology",
    topic: "Human Body",
    question: "Which type of blood vessel carries blood away from the heart?",
    answer: "artery",
    acceptedAnswers: [
      "artery",
      "arteries",
    ],
    explanation: "Arteries carry oxygenated blood away from the heart (except the pulmonary artery). They have thick walls to withstand high pressure.",
    marks: 3,
  },
  {
    id: 16,
    subject: "Biology",
    topic: "Genetics",
    question: "Which type of allele is only expressed when two copies are present (homozygous)?",
    answer: "recessive",
    acceptedAnswers: [
      "recessive",
      "recessive allele",
    ],
    explanation: "A dominant allele is one whose trait is expressed when even one copy is present.",
    marks: 2,
  },
  {
    id: 17,
    subject: "Biology",
    topic: "Excretion",
    question: "What is the main excretory organ in humans that filters blood to produce urine?",
    answer: "kidney",
    acceptedAnswers: [
      "kidney",
      "kidneys",
      "the kidney",
    ],
    explanation: "It removes urea and excess salts (and excess water) from the blood.",
    marks: 2,
  },
  {
    id: 18,
    subject: "Biology",
    topic: "Nutrition",
    question: "Which nutrient makes up about 70% of the human body and acts as a solvent for chemical reactions?",
    answer: "water",
    acceptedAnswers: [
      "water",
    ],
    explanation: "Water is essential for virtually all biological processes, including transport and temperature regulation.",
    marks: 2,
  },
  {
    id: 19,
    subject: "Biology",
    topic: "Ecology",
    question: "What effect describes the trapping of heat by gases like CO₂ and methane in the Earth's atmosphere?",
    answer: "greenhouse effect",
    acceptedAnswers: [
      "greenhouse effect",
      "the greenhouse effect",
    ],
    explanation: "Increased emissions from human activities have enhanced this effect, leading to climate change.",
    marks: 2,
  },
  {
    id: 20,
    subject: "Biology",
    topic: "Human Body",
    question: "Which blood cells defend the body against diseases and infections?",
    answer: "white blood cells",
    acceptedAnswers: [
      "white blood cells",
      "wbc",
      "leukocytes",
    ],
    explanation: "They engulf pathogens (phagocytosis) and produce antibodies.",
    marks: 2,
  },
  {
    id: 21,
    subject: "Biology",
    topic: "Transport",
    question: "What is the loss of water vapor from plant leaves through stomata called?",
    answer: "transpiration",
    acceptedAnswers: [
      "transpiration",
    ],
    explanation: "It helps in drawing water up from the roots and cooling the plant.",
    marks: 2,
  },
  {
    id: 22,
    subject: "Biology",
    topic: "Respiration",
    question: "What is the main product (energy molecule) of cellular respiration?",
    answer: "atp",
    acceptedAnswers: [
      "atp",
      "adenosine triphosphate",
      "energy",
    ],
    explanation: "Aerobic respiration occurs in the mitochondria and releases 38 ATP molecules per glucose molecule.",
    marks: 2,
  },
  {
    id: 23,
    subject: "Biology",
    topic: "Reproduction",
    question: "What is the scientific term for the male gamete in humans?",
    answer: "sperm",
    acceptedAnswers: [
      "sperm",
      "sperm cell",
      "spermatozoa",
    ],
    explanation: "Gametes are haploid cells. The fusion of a sperm and an ovum forms a diploid zygote.",
    marks: 1,
  },
  {
    id: 24,
    subject: "Biology",
    topic: "Ecology",
    question: "What term describes the variety of different species of plants, animals, and microorganisms in an ecosystem?",
    answer: "biodiversity",
    acceptedAnswers: [
      "biodiversity",
      "biological diversity",
    ],
    explanation: "Biodiversity is important for ecosystem stability, food chains, medicine, and maintaining the balance of nature.",
    marks: 1,
  },
  {
    id: 25,
    subject: "Biology",
    topic: "Human Body",
    question: "Finger-like projections on the inner wall of the small intestine that increase surface area are called?",
    answer: "villi",
    acceptedAnswers: [
      "villi",
      "microvilli",
    ],
    explanation: "The small intestine completes digestion and absorbs nutrients into the blood through villi.",
    marks: 2,
  },
  {
    id: 26,
    subject: "Biology",
    topic: "Cell Biology",
    question: "Which type of cell division produces four non-identical haploid cells (gametes) for reproduction?",
    answer: "meiosis",
    acceptedAnswers: [
      "meiosis",
    ],
    explanation: "Mitosis produces two identical diploid cells for growth/repair. Meiosis introduces genetic variation.",
    marks: 3,
  },
  {
    id: 27,
    subject: "Biology",
    topic: "Nutrition",
    question: "Which disease is caused by Vitamin C deficiency?",
    answer: "scurvy",
    acceptedAnswers: [
      "scurvy",
    ],
    explanation: "A balanced diet contains all nutrients in correct proportions, preventing deficiency diseases like rickets (Vitamin D) and anaemia (Iron).",
    marks: 2,
  },
  {
    id: 28,
    subject: "Biology",
    topic: "Genetics",
    question: "The process by which organisms with traits better suited to their environment survive and reproduce is called _____ selection.",
    answer: "natural",
    acceptedAnswers: [
      "natural",
      "natural selection",
    ],
    explanation: "Proposed by Charles Darwin, 'survival of the fittest' means those best adapted to the environment are more likely to survive.",
    marks: 2,
  },
  {
    id: 29,
    subject: "Biology",
    topic: "Human Body",
    question: "What two organs make up the central nervous system? (Format: x and y)",
    answer: "brain and spinal cord",
    acceptedAnswers: [
      "brain and spinal cord",
      "brain, spinal cord",
      "brain and the spinal cord",
      "spinal cord and brain",
    ],
    explanation: "The central nervous system (CNS) coordinates and controls body activities.",
    marks: 1,
  },
  {
    id: 30,
    subject: "Biology",
    topic: "Ecology",
    question: "What process in the water cycle involves water turning from a liquid to a gas?",
    answer: "evaporation",
    acceptedAnswers: [
      "evaporation",
    ],
    explanation: "The water cycle also involves condensation (gas to liquid) and precipitation (falling as rain/snow).",
    marks: 2,
  },
];

export default grade9Biology;
