import type { Grade9Question } from "@/types";

const grade9BusinessStudies: Grade9Question[] = [
  {
    id: 1,
    subject: "Business Studies",
    topic: "Business Basics",
    question: "What is any activity carried out to produce or provide goods and services to satisfy human needs for profit called?",
    answer: "business",
    acceptedAnswers: ["business", "a business"],
    explanation: "Business activities involve production, distribution, and exchange of goods and services. They can be classified as trade, industry, or commerce.",
    marks: 2,
  },
  {
    id: 2,
    subject: "Business Studies",
    topic: "Entrepreneurship",
    question: "What do you call a person who starts and runs a business, taking on financial risks in hope of profit?",
    answer: "entrepreneur",
    acceptedAnswers: ["entrepreneur", "an entrepreneur"],
    explanation: "Entrepreneurs identify opportunities, organize resources, and innovate. Qualities include creativity, risk-taking, and good decision-making.",
    marks: 1,
  },
  {
    id: 3,
    subject: "Business Studies",
    topic: "Trade",
    question: "Which type of trade involves buying goods in large quantities from producers and selling in smaller quantities to retailers?",
    answer: "wholesale",
    acceptedAnswers: ["wholesale", "wholesale trade"],
    explanation: "Wholesalers act as middlemen between producers and retailers. They provide storage, break bulk, and extend credit to retailers.",
    marks: 1,
  },
  {
    id: 4,
    subject: "Business Studies",
    topic: "Office Practice",
    question: "What is a place where business, administrative, or clerical work is carried out called?",
    answer: "office",
    acceptedAnswers: ["office", "an office"],
    explanation: "The office is the nerve center of any organization. It facilitates communication, data management, and coordination of activities.",
    marks: 1,
  },
  {
    id: 5,
    subject: "Business Studies",
    topic: "Banking",
    question: "Name the service where people keep their money safely in a bank (e.g. savings and current).",
    answer: "deposits",
    acceptedAnswers: ["deposits", "accepting deposits", "deposit"],
    explanation: "Other services include giving loans and advances, money transfer services, safe deposit boxes, and foreign exchange.",
    marks: 1,
  },
  {
    id: 6,
    subject: "Business Studies",
    topic: "Communication",
    question: "What is the process of exchanging information between a sender and receiver called?",
    answer: "communication",
    acceptedAnswers: ["communication"],
    explanation: "Effective communication requires a clear message, appropriate channel, and feedback. Barriers include language differences and noise.",
    marks: 1,
  },
  {
    id: 7,
    subject: "Business Studies",
    topic: "Demand and Supply",
    question: "According to the law of demand, as the price of a good increases, what happens to the quantity demanded?",
    answer: "decreases",
    acceptedAnswers: ["decreases", "it decreases", "goes down", "falls"],
    explanation: "This creates a downward-sloping demand curve. Exceptions include Giffen goods and prestige goods where demand may increase with price.",
    marks: 1,
  },
  {
    id: 8,
    subject: "Business Studies",
    topic: "Insurance",
    question: "What is the regular payment made to an insurance company called?",
    answer: "premium",
    acceptedAnswers: ["premium", "a premium", "premiums"],
    explanation: "Insurance works on the principle of pooling risks. Common types include life, motor, fire, and medical insurance.",
    marks: 1,
  },
  {
    id: 9,
    subject: "Business Studies",
    topic: "Business Basics",
    question: "Name the factor of production that represents human effort.",
    answer: "labour",
    acceptedAnswers: ["labour", "labor"],
    explanation: "The four factors are Land, Labour, Capital, and Entrepreneurship. Each factor earns a reward: land earns rent, labour earns wages.",
    marks: 1,
  },
  {
    id: 10,
    subject: "Business Studies",
    topic: "Accounting",
    question: "What is a financial plan showing expected income and expenditure over a given period called?",
    answer: "budget",
    acceptedAnswers: ["budget", "a budget"],
    explanation: "Budgets help in planning, controlling spending, and ensuring resources are allocated efficiently.",
    marks: 1,
  },
  {
    id: 11,
    subject: "Business Studies",
    topic: "Trade",
    question: "What document is sent by the seller to the buyer showing details of goods sold (description, quantity, price)?",
    answer: "invoice",
    acceptedAnswers: ["invoice", "an invoice"],
    explanation: "An invoice helps in preparing accounts, requesting payment, and resolving disputes.",
    marks: 1,
  },
  {
    id: 12,
    subject: "Business Studies",
    topic: "Entrepreneurship",
    question: "What is the written document that outlines the goals, strategies, and operations of a new or existing business?",
    answer: "business plan",
    acceptedAnswers: ["business plan", "a business plan"],
    explanation: "A business plan is essential for securing funding, guiding operations, and measuring progress.",
    marks: 1,
  },
  {
    id: 13,
    subject: "Business Studies",
    topic: "Banking",
    question: "Which type of bank account does not usually earn interest but allows unlimited deposits and withdrawals using cheques?",
    answer: "current account",
    acceptedAnswers: ["current account", "current", "a current account"],
    explanation: "Current accounts are used by businesses for daily transactions. Savings accounts are used by individuals to save money over time.",
    marks: 1,
  },
  {
    id: 14,
    subject: "Business Studies",
    topic: "Demand and Supply",
    question: "According to the law of supply, as the price of a good increases, what happens to the quantity supplied?",
    answer: "increases",
    acceptedAnswers: ["increases", "it increases", "goes up", "rises"],
    explanation: "Higher prices incentivize producers to supply more. This creates an upward-sloping supply curve.",
    marks: 1,
  },
  {
    id: 15,
    subject: "Business Studies",
    topic: "Transport",
    question: "Which mode of transport is the fastest for long distances?",
    answer: "air",
    acceptedAnswers: ["air", "air transport", "airplane", "aeroplane", "planes"],
    explanation: "The choice of transport depends on cost, speed, distance, type of goods, and urgency.",
    marks: 1,
  },
  {
    id: 16,
    subject: "Business Studies",
    topic: "Business Basics",
    question: "What term describes the desires for goods and services that are necessary for survival or comfort?",
    answer: "human wants",
    acceptedAnswers: ["human wants", "wants", "needs and wants"],
    explanation: "Human wants are unlimited while resources are scarce. This creates the economic problem of choice and drives business activity.",
    marks: 1,
  },
  {
    id: 17,
    subject: "Business Studies",
    topic: "Office Practice",
    question: "What is the systematic arrangement and storage of documents for easy retrieval called?",
    answer: "filing",
    acceptedAnswers: ["filing"],
    explanation: "Good filing ensures documents are safe, organized, and easily accessible. Methods include alphabetical, numerical, and chronological.",
    marks: 1,
  },
  {
    id: 18,
    subject: "Business Studies",
    topic: "Accounting",
    question: "What is the financial gain when total revenue exceeds total costs?",
    answer: "profit",
    acceptedAnswers: ["profit", "a profit", "net profit"],
    explanation: "Profit is the main objective of most businesses. Profit = Total Revenue - Total Costs.",
    marks: 1,
  },
  {
    id: 19,
    subject: "Business Studies",
    topic: "Insurance",
    question: "Which insurance principle states that both parties must be completely honest and disclose all relevant facts?",
    answer: "utmost good faith",
    acceptedAnswers: ["utmost good faith", "good faith"],
    explanation: "Other principles include insurable interest (must have a stake in what is insured) and indemnity (compensation should restore, not enrich).",
    marks: 1,
  },
  {
    id: 20,
    subject: "Business Studies",
    topic: "Business Basics",
    question: "Intangible activities performed to satisfy human wants (e.g., teaching, medical care) are called?",
    answer: "services",
    acceptedAnswers: ["services", "a service", "service"],
    explanation: "Goods are tangible products that can be seen and touched. Goods can be stored while services are consumed as they are produced.",
    marks: 1,
  },
  {
    id: 21,
    subject: "Business Studies",
    topic: "Communication",
    question: "What is the most common electronic method used to send written messages instantly over the internet?",
    answer: "email",
    acceptedAnswers: ["email", "e-mail", "electronic mail"],
    explanation: "Technology has revolutionized business communication, making it faster and more efficient.",
    marks: 1,
  },
  {
    id: 22,
    subject: "Business Studies",
    topic: "Trade",
    question: "What is the buying and selling of goods and services over the internet called?",
    answer: "e-commerce",
    acceptedAnswers: ["e-commerce", "ecommerce", "electronic commerce", "online shopping"],
    explanation: "Examples include online shops like Jumia and Amazon. E-commerce offers convenience and wider market reach.",
    marks: 1,
  },
  {
    id: 23,
    subject: "Business Studies",
    topic: "Entrepreneurship",
    question: "A business owned and run by one person is called a _____ proprietorship.",
    answer: "sole",
    acceptedAnswers: ["sole", "sole trader"],
    explanation: "It is easy to start and the owner keeps all profits, but it has unlimited liability.",
    marks: 1,
  },
  {
    id: 24,
    subject: "Business Studies",
    topic: "Accounting",
    question: "What is a written acknowledgment that payment has been received?",
    answer: "receipt",
    acceptedAnswers: ["receipt", "a receipt"],
    explanation: "Receipts help prevent disputes, track expenses, and maintain accurate financial records.",
    marks: 1,
  },
  {
    id: 25,
    subject: "Business Studies",
    topic: "Demand and Supply",
    question: "What is the general and sustained increase in the prices of goods and services over time called?",
    answer: "inflation",
    acceptedAnswers: ["inflation"],
    explanation: "Inflation reduces purchasing power. Central banks try to control inflation through monetary policy.",
    marks: 1,
  },
  {
    id: 26,
    subject: "Business Studies",
    topic: "Banking",
    question: "What is the use of mobile phones to access banking services (checking balance, transfers, payments) called?",
    answer: "mobile banking",
    acceptedAnswers: ["mobile banking", "m-banking"],
    explanation: "M-Pesa in Kenya revolutionized mobile banking. It allows millions to access financial services conveniently.",
    marks: 1,
  },
  {
    id: 27,
    subject: "Business Studies",
    topic: "Business Basics",
    question: "The value of the next best alternative forgone when a choice is made is called the _____ cost.",
    answer: "opportunity",
    acceptedAnswers: ["opportunity", "opportunity cost"],
    explanation: "Since resources are scarce, every choice has an opportunity cost.",
    marks: 1,
  },
  {
    id: 28,
    subject: "Business Studies",
    topic: "Trade",
    question: "What are goods and services sold to other countries called?",
    answer: "exports",
    acceptedAnswers: ["exports", "export"],
    explanation: "Imports are goods and services bought from other countries. The difference is the balance of trade.",
    marks: 1,
  },
  {
    id: 29,
    subject: "Business Studies",
    topic: "Office Practice",
    question: "What is a brief written message used for internal communication within an organization?",
    answer: "memo",
    acceptedAnswers: ["memo", "memorandum", "a memo"],
    explanation: "Memos are less formal than business letters and are addressed to employees or departments within the same organization.",
    marks: 1,
  },
  {
    id: 30,
    subject: "Business Studies",
    topic: "Accounting",
    question: "What financial statement shows a business's assets, liabilities, and owner's equity at a specific point in time?",
    answer: "balance sheet",
    acceptedAnswers: ["balance sheet", "a balance sheet"],
    explanation: "Assets = Liabilities + Owner's Equity. It provides a snapshot of what the business owns and owes.",
    marks: 1,
  },
];

export default grade9BusinessStudies;
