import type { Grade9Question } from "@/types";

const grade9Chemistry: Grade9Question[] = [
  {
    id: 1,
    subject: "Chemistry",
    topic: "Matter",
    question: "Name the three states of matter. (List separated by commas)",
    answer: "solid, liquid, gas",
    acceptedAnswers: [
      "solid, liquid, gas",
      "solid, liquid, and gas",
      "gas, liquid, solid",
      "liquid, solid, gas",
      "gas, solid, liquid",
      "solid liquid gas",
    ],
    explanation: "The state of matter depends on the arrangement and movement of particles. Heating causes particles to gain energy and change state.",
    marks: 3,
  },
  {
    id: 2,
    subject: "Chemistry",
    topic: "Atomic Structure",
    question: "Name the three subatomic particles found in an atom. (List separated by commas)",
    answer: "proton, neutron, electron",
    acceptedAnswers: [
      "proton, neutron, electron",
      "protons, neutrons, electrons",
      "proton, electron, neutron",
      "electron, proton, neutron",
      "protons, electrons, neutrons",
      "electrons, protons, neutrons",
      "proton, neutron, and electron",
    ],
    explanation: "Protons and neutrons are found in the nucleus, while electrons orbit the nucleus in shells.",
    marks: 3,
  },
  {
    id: 3,
    subject: "Chemistry",
    topic: "Chemical Reactions",
    question: "What type of change is usually irreversible and results in new substances being formed?",
    answer: "chemical change",
    acceptedAnswers: ["chemical", "chemical change", "a chemical change"],
    explanation: "In chemical changes, bonds between atoms are broken and new bonds are formed. Physical changes only affect the appearance.",
    marks: 2,
  },
  {
    id: 4,
    subject: "Chemistry",
    topic: "Acids and Bases",
    question: "What is the exact pH value of a neutral substance like pure water?",
    answer: "7",
    acceptedAnswers: ["7", "seven", "ph 7", "ph7"],
    explanation: "The pH scale ranges from 0 to 14. Below 7 is acidic, above 7 is alkaline/basic, and exactly 7 is neutral.",
    marks: 1,
  },
  {
    id: 5,
    subject: "Chemistry",
    topic: "Periodic Table",
    question: "What number represents the amount of protons in the nucleus of an atom of an element?",
    answer: "atomic number",
    acceptedAnswers: ["atomic number", "the atomic number", "proton number"],
    explanation: "The atomic number determines the identity of an element and its position in the periodic table.",
    marks: 1,
  },
  {
    id: 6,
    subject: "Chemistry",
    topic: "Chemical Bonding",
    question: "What type of bond is formed when one atom transfers electrons to another atom?",
    answer: "ionic",
    acceptedAnswers: ["ionic", "ionic bond", "an ionic bond", "electrovalent", "electrovalent bond"],
    explanation: "Ionic bonds typically form between metals and non-metals.",
    marks: 2,
  },
  {
    id: 7,
    subject: "Chemistry",
    topic: "Mixtures",
    question: "Which separation technique would you use to separate an insoluble solid (like sand) from a liquid?",
    answer: "filtration",
    acceptedAnswers: ["filtration", "filtering"],
    explanation: "To separate salt and sand: add water to dissolve salt, use filtration to separate sand, and evaporation to recover the salt.",
    marks: 1,
  },
  {
    id: 8,
    subject: "Chemistry",
    topic: "Acids and Bases",
    question: "Name the two products formed when an acid reacts with a base (neutralization). (Format: x and y)",
    answer: "salt and water",
    acceptedAnswers: ["salt and water", "water and salt", "a salt and water"],
    explanation: "Neutralization: Acid + Base → Salt + Water. For example: HCl + NaOH → NaCl + H₂O.",
    marks: 2,
  },
  {
    id: 9,
    subject: "Chemistry",
    topic: "Chemical Reactions",
    question: "Balance the equation: H₂ + O₂ → H₂O (Provide the completely balanced equation)",
    answer: "2H2 + O2 -> 2H2O",
    acceptedAnswers: [
      "2H2 + O2 -> 2H2O",
      "2H2 + O2 = 2H2O",
      "2H₂ + O₂ → 2H₂O",
      "2H₂ + O₂ -> 2H₂O",
      "2h2 + o2 -> 2h2o",
    ],
    explanation: "In the balanced equation, there are 4 hydrogen atoms and 2 oxygen atoms on each side. Balancing ensures the law of conservation of mass is obeyed.",
    marks: 2,
  },
  {
    id: 10,
    subject: "Chemistry",
    topic: "Metals",
    question: "What term describes the property of metals that allows them to be hammered or rolled into sheets?",
    answer: "malleable",
    acceptedAnswers: ["malleable", "malleability"],
    explanation: "Other properties include being ductile (drawn into wires), good conductors of heat/electricity, and having a shiny appearance.",
    marks: 1,
  },
  {
    id: 11,
    subject: "Chemistry",
    topic: "Water",
    question: "What color does blue cobalt chloride paper turn in the presence of water?",
    answer: "pink",
    acceptedAnswers: ["pink"],
    explanation: "Anhydrous cobalt chloride is blue; when it absorbs water, it becomes hydrated and turns pink.",
    marks: 1,
  },
  {
    id: 12,
    subject: "Chemistry",
    topic: "Gases",
    question: "What happens to the appearance of limewater when carbon dioxide is bubbled through it?",
    answer: "turns milky",
    acceptedAnswers: [
      "turns milky", "it turns milky", "milky",
      "turns cloudy", "cloudy", "chalky white",
      "turns chalky white", "white precipitate",
    ],
    explanation: "CO₂ reacts with Ca(OH)₂ to form an insoluble calcium carbonate (CaCO₃) white precipitate.",
    marks: 2,
  },
  {
    id: 13,
    subject: "Chemistry",
    topic: "Atomic Structure",
    question: "What is the electron arrangement of a sodium atom (atomic number 11)? (Format: x, y, z)",
    answer: "2, 8, 1",
    acceptedAnswers: ["2, 8, 1", "2,8,1", "2.8.1", "2 8 1"],
    explanation: "The first shell holds a maximum of 2 electrons, the second holds 8, and the third can hold up to 8 in simple models.",
    marks: 2,
  },
  {
    id: 14,
    subject: "Chemistry",
    topic: "Chemical Bonding",
    question: "What type of bond is formed when two atoms share one or more pairs of electrons?",
    answer: "covalent",
    acceptedAnswers: ["covalent", "covalent bond", "a covalent bond"],
    explanation: "Covalent bonds typically form between non-metal atoms (e.g., in water H₂O).",
    marks: 2,
  },
  {
    id: 15,
    subject: "Chemistry",
    topic: "Acids and Bases",
    question: "What color does blue litmus paper turn in the presence of an acid?",
    answer: "red",
    acceptedAnswers: ["red", "turns red", "it turns red"],
    explanation: "Litmus is red in acid and blue in base.",
    marks: 1,
  },
  {
    id: 16,
    subject: "Chemistry",
    topic: "Chemical Reactions",
    question: "What type of reaction releases heat energy to the surroundings?",
    answer: "exothermic",
    acceptedAnswers: ["exothermic", "exothermic reaction", "an exothermic reaction"],
    explanation: "In exothermic reactions, the temperature of the surroundings increases. The opposite is endothermic reactions, which absorb heat.",
    marks: 2,
  },
  {
    id: 17,
    subject: "Chemistry",
    topic: "Periodic Table",
    question: "What are the highly reactive metals in Group 1 of the periodic table called?",
    answer: "alkali metals",
    acceptedAnswers: ["alkali metals", "alkali", "alkali metal"],
    explanation: "Alkali metals (like Lithium and Sodium) have one electron in their outer shell and react vigorously with water.",
    marks: 2,
  },
  {
    id: 18,
    subject: "Chemistry",
    topic: "Gases",
    question: "What happens to a glowing splint when it is inserted into a test tube of oxygen gas?",
    answer: "relights",
    acceptedAnswers: ["relights", "it relights", "reignites", "it reignites", "bursts into flame"],
    explanation: "Oxygen supports combustion. A glowing splint provides a small ember that reignites in concentrated oxygen.",
    marks: 2,
  },
  {
    id: 19,
    subject: "Chemistry",
    topic: "Mixtures",
    question: "What substance is formed when two or more elements are chemically bonded in fixed proportions?",
    answer: "compound",
    acceptedAnswers: ["compound", "a compound"],
    explanation: "A mixture is physically combined and has variable composition, while a compound is chemically bonded.",
    marks: 1,
  },
  {
    id: 20,
    subject: "Chemistry",
    topic: "Metals",
    question: "Which of these metals is the most reactive: Iron, Potassium, Copper, Zinc?",
    answer: "potassium",
    acceptedAnswers: ["potassium", "k"],
    explanation: "The reactivity series ranks metals by how readily they react. Potassium reacts violently with water.",
    marks: 1,
  },
  {
    id: 21,
    subject: "Chemistry",
    topic: "Water",
    question: "Water that contains dissolved calcium or magnesium compounds and forms scum with soap is called _____ water.",
    answer: "hard",
    acceptedAnswers: ["hard", "hard water"],
    explanation: "It wastes soap and makes cleaning difficult. It can also cause limescale buildup.",
    marks: 1,
  },
  {
    id: 22,
    subject: "Chemistry",
    topic: "Chemical Reactions",
    question: "What is a substance that speeds up a chemical reaction without being used up itself called?",
    answer: "catalyst",
    acceptedAnswers: ["catalyst", "a catalyst"],
    explanation: "Catalysts work by providing an alternative reaction pathway with lower activation energy.",
    marks: 2,
  },
  {
    id: 23,
    subject: "Chemistry",
    topic: "Acids and Bases",
    question: "Which gas is produced when an acid reacts with a metal?",
    answer: "hydrogen",
    acceptedAnswers: ["hydrogen", "hydrogen gas", "h2", "h2 gas"],
    explanation: "Acid + Metal → Salt + Hydrogen. For example: Zinc + Hydrochloric acid → Zinc chloride + Hydrogen.",
    marks: 1,
  },
  {
    id: 24,
    subject: "Chemistry",
    topic: "Matter",
    question: "What is the change of state directly from a solid to a gas without passing through the liquid state called?",
    answer: "sublimation",
    acceptedAnswers: ["sublimation"],
    explanation: "Example: Dry ice (solid CO₂) sublimes at room temperature. The reverse is called deposition.",
    marks: 2,
  },
  {
    id: 25,
    subject: "Chemistry",
    topic: "Chemical Reactions",
    question: "Which law states that matter cannot be created or destroyed in a chemical reaction?",
    answer: "law of conservation of mass",
    acceptedAnswers: [
      "law of conservation of mass",
      "conservation of mass",
      "the law of conservation of mass",
    ],
    explanation: "The total mass of reactants equals the total mass of products. This is why chemical equations must be balanced.",
    marks: 2,
  },
  {
    id: 26,
    subject: "Chemistry",
    topic: "Gases",
    question: "Which gas burns with a signature squeaky 'pop' sound when a lit splint is brought near it?",
    answer: "hydrogen",
    acceptedAnswers: ["hydrogen", "hydrogen gas", "h2"],
    explanation: "The 'pop' sound occurs because hydrogen reacts explosively with oxygen to form water.",
    marks: 1,
  },
  {
    id: 27,
    subject: "Chemistry",
    topic: "Metals",
    question: "What do we call a mixture of two or more metals (or a metal and a non-metal), like steel?",
    answer: "alloy",
    acceptedAnswers: ["alloy", "an alloy", "alloys"],
    explanation: "Alloys are often harder and more durable than pure metals because atoms of different sizes disrupt the regular arrangement.",
    marks: 1,
  },
  {
    id: 28,
    subject: "Chemistry",
    topic: "Atomic Structure",
    question: "What term refers to atoms of the same element that have the same number of protons but different numbers of neutrons?",
    answer: "isotope",
    acceptedAnswers: ["isotope", "isotopes"],
    explanation: "For example, Carbon-12 and Carbon-14 are isotopes of carbon.",
    marks: 2,
  },
  {
    id: 29,
    subject: "Chemistry",
    topic: "Chemical Reactions",
    question: "In terms of electrons, what does oxidation mean?",
    answer: "loss of electrons",
    acceptedAnswers: ["loss of electrons", "loss", "losing electrons"],
    explanation: "Remember OIL RIG: Oxidation Is Loss, Reduction Is Gain (of electrons). Oxidation can also mean the gain of oxygen.",
    marks: 1,
  },
  {
    id: 30,
    subject: "Chemistry",
    topic: "Periodic Table",
    question: "Elements in the same group of the periodic table have similar chemical properties because they have the same number of _____ in their outer shell.",
    answer: "electrons",
    acceptedAnswers: ["electrons", "valence electrons"],
    explanation: "For example, all Group 1 elements have 1 outer electron and are reactive metals.",
    marks: 1,
  },
];

export default grade9Chemistry;
