import type { Grade9Question } from "@/types";

const grade9Mathematics: Grade9Question[] = [
  {
    id: 1,
    subject: "Mathematics",
    topic: "Algebra",
    question: "Solve for x: 2x + 5 = 17",
    answer: "6",
    acceptedAnswers: ["6", "x=6", "x = 6"],
    explanation: "Subtract 5 from both sides: 2x = 12. Divide both sides by 2: x = 6.",
    marks: 2,
  },
  {
    id: 2,
    subject: "Mathematics",
    topic: "Algebra",
    question: "Factorize completely: x² - 9",
    answer: "(x+3)(x-3)",
    acceptedAnswers: ["(x+3)(x-3)", "(x + 3)(x - 3)", "(x-3)(x+3)", "(x - 3)(x + 3)"],
    explanation: "This is a difference of two squares. a² - b² = (a + b)(a - b). Here a = x and b = 3.",
    marks: 2,
  },
  {
    id: 3,
    subject: "Mathematics",
    topic: "Geometry",
    question: "Calculate the area of a triangle with base 10 cm and height 6 cm. (Just enter the number and units, e.g., 50 cm2)",
    answer: "30 cm2",
    acceptedAnswers: ["30", "30 cm2", "30cm2", "30 cm²", "30cm²", "30 square cm", "30 sq cm"],
    explanation: "Area of a triangle = ½ × base × height = ½ × 10 × 6 = 30 cm².",
    marks: 2,
  },
  {
    id: 4,
    subject: "Mathematics",
    topic: "Algebra",
    question: "Simplify: 3(2x - 4) + 5x",
    answer: "11x - 12",
    acceptedAnswers: ["11x - 12", "11x-12", "-12 + 11x", "-12+11x"],
    explanation: "Expand: 6x - 12 + 5x = 11x - 12.",
    marks: 2,
  },
  {
    id: 5,
    subject: "Mathematics",
    topic: "Number Systems",
    question: "Express 0.75 as a fraction in its simplest form. (Format: a/b)",
    answer: "3/4",
    acceptedAnswers: ["3/4", "¾"],
    explanation: "0.75 = 75/100. Dividing both numerator and denominator by 25 gives ¾.",
    marks: 1,
  },
  {
    id: 6,
    subject: "Mathematics",
    topic: "Geometry",
    question: "Find the circumference of a circle with diameter 14 cm. (Use π = 22/7)",
    answer: "44",
    acceptedAnswers: ["44", "44 cm", "44cm"],
    explanation: "Circumference = πd = (22/7) × 14 = 44 cm.",
    marks: 2,
  },
  {
    id: 7,
    subject: "Mathematics",
    topic: "Algebra",
    question: "Solve the simultaneous equations: x + y = 10 and x - y = 4 (Format: x, y)",
    answer: "7, 3",
    acceptedAnswers: ["7, 3", "7,3", "x=7, y=3", "x = 7, y = 3", "x=7,y=3"],
    explanation: "Adding the two equations: 2x = 14, so x = 7. Substituting back: 7 + y = 10, so y = 3.",
    marks: 3,
  },
  {
    id: 8,
    subject: "Mathematics",
    topic: "Statistics",
    question: "Find the mean of: 12, 15, 18, 21, 24",
    answer: "18",
    acceptedAnswers: ["18"],
    explanation: "Mean = (12 + 15 + 18 + 21 + 24) ÷ 5 = 90 ÷ 5 = 18.",
    marks: 2,
  },
  {
    id: 9,
    subject: "Mathematics",
    topic: "Geometry",
    question: "Calculate the volume of a cuboid with length 8 cm, width 5 cm, and height 3 cm.",
    answer: "120",
    acceptedAnswers: ["120", "120 cm3", "120cm3", "120 cm³", "120cm³", "120 cubic cm"],
    explanation: "Volume = length × width × height = 8 × 5 × 3 = 120 cm³.",
    marks: 2,
  },
  {
    id: 10,
    subject: "Mathematics",
    topic: "Number Systems",
    question: "What is the LCM of 12 and 18?",
    answer: "36",
    acceptedAnswers: ["36"],
    explanation: "12 = 2² × 3 and 18 = 2 × 3². LCM = 2² × 3² = 4 × 9 = 36.",
    marks: 2,
  },
  {
    id: 11,
    subject: "Mathematics",
    topic: "Algebra",
    question: "Solve for x: x² - 5x + 6 = 0 (Format: smaller, larger)",
    answer: "2, 3",
    acceptedAnswers: ["2, 3", "2,3", "x=2, x=3", "x=2,x=3", "x = 2 or x = 3", "2 or 3"],
    explanation: "Factorize: (x - 2)(x - 3) = 0. Therefore x = 2 or x = 3.",
    marks: 3,
  },
  {
    id: 12,
    subject: "Mathematics",
    topic: "Geometry",
    question: "Find the value of angle x if it is supplementary to 125°.",
    answer: "55",
    acceptedAnswers: ["55", "55°", "55 degrees"],
    explanation: "Supplementary angles add up to 180°. Therefore x = 180° - 125° = 55°.",
    marks: 1,
  },
  {
    id: 13,
    subject: "Mathematics",
    topic: "Ratio and Proportion",
    question: "Divide 450 in the ratio 2:3:4. (Format: a, b, c)",
    answer: "100, 150, 200",
    acceptedAnswers: ["100, 150, 200", "100,150,200"],
    explanation: "Total parts = 2 + 3 + 4 = 9. Each part = 450/9 = 50. So: 2×50=100, 3×50=150, 4×50=200.",
    marks: 3,
  },
  {
    id: 14,
    subject: "Mathematics",
    topic: "Percentages",
    question: "A shirt costs Ksh 800. After a 15% discount, what is the selling price? (Enter number only)",
    answer: "680",
    acceptedAnswers: ["680", "ksh 680", "ksh680"],
    explanation: "Discount = 15/100 × 800 = Ksh 120. Selling price = 800 - 120 = Ksh 680.",
    marks: 2,
  },
  {
    id: 15,
    subject: "Mathematics",
    topic: "Algebra",
    question: "Make 'r' the subject of the formula: A = πr² (Format: r = √(A/π) or similar)",
    answer: "r = √(A/π)",
    acceptedAnswers: ["r = √(A/π)", "r=√(A/π)", "r = sqrt(A/π)", "r=sqrt(A/π)", "√(A/π)"],
    explanation: "Divide both sides by π: r² = A/π. Take the square root: r = √(A/π).",
    marks: 2,
  },
  {
    id: 16,
    subject: "Mathematics",
    topic: "Trigonometry",
    question: "In a right-angled triangle, if the opposite side is 3 cm and the hypotenuse is 5 cm, find sin θ. (Decimal format)",
    answer: "0.6",
    acceptedAnswers: ["0.6", "3/5"],
    explanation: "sin θ = opposite/hypotenuse = 3/5 = 0.6.",
    marks: 2,
  },
  {
    id: 17,
    subject: "Mathematics",
    topic: "Indices",
    question: "Simplify: 2³ × 2⁴",
    answer: "128",
    acceptedAnswers: ["128", "2^7", "2^7 = 128"],
    explanation: "When multiplying with the same base, add the indices: 2³ × 2⁴ = 2⁷ = 128.",
    marks: 2,
  },
  {
    id: 18,
    subject: "Mathematics",
    topic: "Linear Equations",
    question: "Find the gradient of the line passing through points (2, 3) and (6, 11).",
    answer: "2",
    acceptedAnswers: ["2", "two"],
    explanation: "Gradient = (y₂ - y₁)/(x₂ - x₁) = (11 - 3)/(6 - 2) = 8/4 = 2.",
    marks: 2,
  },
  {
    id: 19,
    subject: "Mathematics",
    topic: "Geometry",
    question: "Find the area of a circle with radius 7 cm. (Use π = 22/7)",
    answer: "154",
    acceptedAnswers: ["154", "154 cm2", "154cm2", "154 cm²", "154cm²"],
    explanation: "Area = πr² = (22/7) × 7² = (22/7) × 49 = 154 cm².",
    marks: 2,
  },
  {
    id: 20,
    subject: "Mathematics",
    topic: "Sequences",
    question: "Find the 10th term of the arithmetic sequence: 3, 7, 11, 15, ...",
    answer: "39",
    acceptedAnswers: ["39"],
    explanation: "First term (a) = 3, common difference (d) = 4. Tₙ = a + (n-1)d = 3 + (10-1)×4 = 3 + 36 = 39.",
    marks: 2,
  },
  {
    id: 21,
    subject: "Mathematics",
    topic: "Number Systems",
    question: "Convert the decimal number 25 to binary.",
    answer: "11001",
    acceptedAnswers: ["11001"],
    explanation: "25 ÷ 2 = 12 R1, 12 ÷ 2 = 6 R0, 6 ÷ 2 = 3 R0, 3 ÷ 2 = 1 R1, 1 ÷ 2 = 0 R1. Remainders read bottom to top: 11001.",
    marks: 2,
  },
  {
    id: 22,
    subject: "Mathematics",
    topic: "Algebra",
    question: "Expand and simplify: (x + 3)(x - 2)",
    answer: "x^2 + x - 6",
    acceptedAnswers: ["x^2 + x - 6", "x² + x - 6", "x^2+x-6", "x²+x-6"],
    explanation: "Using FOIL: x² - 2x + 3x - 6 = x² + x - 6.",
    marks: 2,
  },
  {
    id: 23,
    subject: "Mathematics",
    topic: "Mensuration",
    question: "A rectangular tank measures 2 m by 1.5 m by 1 m. How many litres of water can it hold?",
    answer: "3000",
    acceptedAnswers: ["3000", "3000 litres", "3000l", "3000 liters"],
    explanation: "Volume = 2 × 1.5 × 1 = 3 m³. Since 1 m³ = 1000 litres, the tank holds 3000 litres.",
    marks: 3,
  },
  {
    id: 24,
    subject: "Mathematics",
    topic: "Statistics",
    question: "Find the median of: 7, 3, 9, 1, 5, 11, 8",
    answer: "7",
    acceptedAnswers: ["7"],
    explanation: "Arrange in order: 1, 3, 5, 7, 8, 9, 11. The middle value is 7.",
    marks: 2,
  },
  {
    id: 25,
    subject: "Mathematics",
    topic: "Inequalities",
    question: "Solve the inequality: 3x - 7 > 8",
    answer: "x > 5",
    acceptedAnswers: ["x > 5", "x>5"],
    explanation: "Add 7 to both sides: 3x > 15. Divide by 3: x > 5.",
    marks: 2,
  },
  {
    id: 26,
    subject: "Mathematics",
    topic: "Geometry",
    question: "What is the sum of interior angles of a hexagon (in degrees)?",
    answer: "720",
    acceptedAnswers: ["720", "720°", "720 degrees"],
    explanation: "Sum of interior angles = (n - 2) × 180° = (6 - 2) × 180° = 720°.",
    marks: 2,
  },
  {
    id: 27,
    subject: "Mathematics",
    topic: "Profit and Loss",
    question: "A trader bought goods for Ksh 2000 and sold them for Ksh 2500. Calculate the percentage profit.",
    answer: "25",
    acceptedAnswers: ["25", "25%", "25 percent"],
    explanation: "Profit = 2500 - 2000 = 500. Percentage profit = (500/2000) × 100 = 25%.",
    marks: 2,
  },
  {
    id: 28,
    subject: "Mathematics",
    topic: "Matrices",
    question: "Find the determinant of the 2x2 matrix with top row (2 3) and bottom row (1 4).",
    answer: "5",
    acceptedAnswers: ["5"],
    explanation: "Determinant = (ad - bc) = (2 × 4) - (3 × 1) = 8 - 3 = 5.",
    marks: 2,
  },
  {
    id: 29,
    subject: "Mathematics",
    topic: "Surds",
    question: "Simplify: √50 (Format: a√b)",
    answer: "5√2",
    acceptedAnswers: ["5√2", "5sqrt(2)", "5sqrt2"],
    explanation: "√50 = √(25 × 2) = √25 × √2 = 5√2.",
    marks: 2,
  },
  {
    id: 30,
    subject: "Mathematics",
    topic: "Coordinate Geometry",
    question: "Find the midpoint of the line segment joining points A(2, 6) and B(8, 10). (Format: x, y)",
    answer: "5, 8",
    acceptedAnswers: ["5, 8", "(5, 8)", "(5,8)", "5,8"],
    explanation: "Midpoint = ((x₁+x₂)/2, (y₁+y₂)/2) = ((2+8)/2, (6+10)/2) = (5, 8).",
    marks: 2,
  },
];

export default grade9Mathematics;
