import type { Grade9Question } from "@/types";

const grade9English: Grade9Question[] = [
  {
    id: 1,
    subject: "English",
    topic: "Grammar",
    question: "Rewrite the following sentence in passive voice: 'The cat chased the mouse.'",
    answer: "The mouse was chased by the cat.",
    acceptedAnswers: [
      "The mouse was chased by the cat.",
      "The mouse was chased by the cat",
    ],
    explanation: "In passive voice, the object becomes the subject. The verb changes to 'was/were + past participle', and the original subject becomes the agent introduced by 'by'.",
    marks: 2,
  },
  {
    id: 2,
    subject: "English",
    topic: "Vocabulary",
    question: "What does the word 'benevolent' mean? (Answer in one or two words)",
    answer: "kind or well-meaning",
    acceptedAnswers: [
      "kind", "kindly", "well-meaning", "well meaning",
      "generous", "kind-hearted", "kindhearted",
      "charitable", "benevolent means kind",
      "benevolent means kindly",
    ],
    explanation: "'Benevolent' comes from Latin 'bene' (well) and 'volent' (wishing). It describes someone who is generous and kind-hearted.",
    marks: 1,
  },
  {
    id: 3,
    subject: "English",
    topic: "Comprehension",
    question: "A simile uses which two words to make a comparison?",
    answer: "like or as",
    acceptedAnswers: [
      "like or as", "like and as", "as or like", "as and like",
      "like, as", "as, like",
      "like/as", "as/like",
    ],
    explanation: "A simile compares two things using 'like' or 'as' (e.g., 'She runs like the wind'). A metaphor makes a direct comparison without these words.",
    marks: 1,
  },
  {
    id: 4,
    subject: "English",
    topic: "Grammar",
    question: "Correct the error in this sentence: 'The group of students were excited about the trip.'",
    answer: "The group of students was excited about the trip.",
    acceptedAnswers: [
      "The group of students was excited about the trip.",
      "The group of students was excited about the trip",
    ],
    explanation: "'Group' is a collective noun and takes a singular verb 'was' when referring to the group as a single unit.",
    marks: 1,
  },
  {
    id: 5,
    subject: "English",
    topic: "Writing",
    question: "What are the three main parts of an essay? (List them separated by commas)",
    answer: "Introduction, body, and conclusion",
    acceptedAnswers: [
      "introduction, body, and conclusion",
      "introduction, body, conclusion",
      "introduction body and conclusion",
      "introduction body conclusion",
    ],
    explanation: "The introduction presents the topic and thesis statement, the body develops the arguments with supporting details, and the conclusion summarizes the main points.",
    marks: 2,
  },
  {
    id: 6,
    subject: "English",
    topic: "Grammar",
    question: "Change the following sentence to reported speech: 'I will come tomorrow,' said John.",
    answer: "John said that he would come the following day.",
    acceptedAnswers: [
      "John said that he would come the following day.",
      "John said that he would come the following day",
      "John said he would come the following day.",
      "John said he would come the following day",
      "John said that he would come the next day.",
      "John said that he would come the next day",
      "John said he would come the next day.",
      "John said he would come the next day",
    ],
    explanation: "In reported speech: 'I' changes to 'he', 'will' changes to 'would', 'tomorrow' changes to 'the following day'/'the next day', and quotation marks are removed.",
    marks: 2,
  },
  {
    id: 7,
    subject: "English",
    topic: "Vocabulary",
    question: "Give an antonym (opposite) of the word 'generous'. (One word)",
    answer: "stingy",
    acceptedAnswers: [
      "stingy", "miserly", "selfish", "greedy", "mean", "tight",
      "ungenerous", "cheap", "tightfisted", "tight-fisted",
    ],
    explanation: "An antonym is a word with the opposite meaning. 'Generous' means giving freely, while 'stingy' means unwilling to give or spend.",
    marks: 1,
  },
  {
    id: 8,
    subject: "English",
    topic: "Literature",
    question: "What is the term for the main character in a story around whom the plot revolves?",
    answer: "protagonist",
    acceptedAnswers: [
      "protagonist", "the protagonist", "a protagonist",
      "main character", "the main character",
      "hero", "the hero",
    ],
    explanation: "The protagonist is central to the narrative and often faces a conflict or challenge. They are sometimes called the 'hero' though they don't always have heroic qualities.",
    marks: 1,
  },
  {
    id: 9,
    subject: "English",
    topic: "Grammar",
    question: "Identify the type of sentence: 'What a beautiful sunset!'",
    answer: "Exclamatory sentence",
    acceptedAnswers: [
      "exclamatory sentence", "exclamatory", "an exclamatory sentence",
      "exclamation", "exclamatory sentence.",
    ],
    explanation: "An exclamatory sentence expresses strong emotion or surprise and ends with an exclamation mark. Other types include declarative, interrogative, and imperative sentences.",
    marks: 1,
  },
  {
    id: 10,
    subject: "English",
    topic: "Comprehension",
    question: "The sentence that introduces the main idea of a paragraph is called a _____ sentence.",
    answer: "topic",
    acceptedAnswers: ["topic", "topic sentence"],
    explanation: "The topic sentence is usually the first sentence in a paragraph. It helps organize writing by clearly stating the paragraph's focus and guiding the reader.",
    marks: 1,
  },
  {
    id: 11,
    subject: "English",
    topic: "Grammar",
    question: "Rewrite using a relative pronoun: 'The boy won the race. He is my friend.'",
    answer: "The boy who won the race is my friend.",
    acceptedAnswers: [
      "The boy who won the race is my friend.",
      "The boy who won the race is my friend",
      "The boy that won the race is my friend.",
      "The boy that won the race is my friend",
    ],
    explanation: "The relative pronoun 'who' (or 'that') is used to join the two sentences, referring back to 'the boy' and providing additional information.",
    marks: 2,
  },
  {
    id: 12,
    subject: "English",
    topic: "Vocabulary",
    question: "'Affect' is usually a _____ (part of speech), and 'effect' is usually a _____. (Answer format: verb, noun)",
    answer: "verb, noun",
    acceptedAnswers: [
      "verb, noun", "verb and noun", "verb noun",
      "a verb, a noun", "a verb and a noun",
      "verb; noun",
    ],
    explanation: "'Affect' is usually a verb meaning to influence. 'Effect' is usually a noun meaning a result. Remember: Affect = Action (verb), Effect = End result (noun).",
    marks: 1,
  },
  {
    id: 13,
    subject: "English",
    topic: "Literature",
    question: "What figure of speech is used when the outcome is the opposite of what is expected? (One word)",
    answer: "irony",
    acceptedAnswers: ["irony", "ironic", "situational irony"],
    explanation: "There are three types: verbal irony (saying the opposite of what you mean), situational irony (events turn out opposite to expectations), and dramatic irony (the audience knows something the characters don't).",
    marks: 1,
  },
  {
    id: 14,
    subject: "English",
    topic: "Grammar",
    question: "Add the correct punctuation: 'its a beautiful day isnt it'",
    answer: "It's a beautiful day, isn't it?",
    acceptedAnswers: [
      "It's a beautiful day, isn't it?",
      "It's a beautiful day, isn't it",
    ],
    explanation: "'It's' needs an apostrophe (contraction of 'it is'), a comma separates the statement from the tag question, 'isn't' needs an apostrophe, and the sentence ends with a question mark.",
    marks: 2,
  },
  {
    id: 15,
    subject: "English",
    topic: "Writing",
    question: "The sentence that expresses the main argument or claim of an essay, usually found at the end of the introduction, is called a _____ statement.",
    answer: "thesis",
    acceptedAnswers: ["thesis", "thesis statement", "a thesis statement", "a thesis"],
    explanation: "A strong thesis statement is specific, arguable, and gives the reader a clear idea of what the essay will discuss. It serves as a roadmap for the entire essay.",
    marks: 1,
  },
  {
    id: 16,
    subject: "English",
    topic: "Grammar",
    question: "Identify the part of speech of 'QUICKLY' in: 'The tall man QUICKLY ran across the field.'",
    answer: "adverb",
    acceptedAnswers: ["adverb", "an adverb"],
    explanation: "Adverbs modify verbs (quickly modifies ran). Adjectives describe nouns, and prepositions show relationships between words.",
    marks: 1,
  },
  {
    id: 17,
    subject: "English",
    topic: "Comprehension",
    question: "Is this statement a fact or an opinion? 'Kenya is the most beautiful country in the world.'",
    answer: "opinion",
    acceptedAnswers: ["opinion", "an opinion", "it is an opinion"],
    explanation: "Facts are objective and verifiable, while opinions are subjective and based on personal feelings, beliefs, or judgments. 'Most beautiful' is a subjective claim.",
    marks: 1,
  },
  {
    id: 18,
    subject: "English",
    topic: "Literature",
    question: "What figure of speech involves the repetition of the same consonant sound at the beginning of nearby words? (e.g., 'Peter Piper picked a peck')",
    answer: "alliteration",
    acceptedAnswers: ["alliteration"],
    explanation: "Alliteration is a sound device used in poetry and prose to create rhythm, mood, and emphasis. The repeated sounds must be at the beginning of words.",
    marks: 1,
  },
  {
    id: 19,
    subject: "English",
    topic: "Grammar",
    question: "Rewrite in the future continuous tense: 'She reads a book.'",
    answer: "She will be reading a book.",
    acceptedAnswers: [
      "She will be reading a book.",
      "She will be reading a book",
    ],
    explanation: "The future continuous tense is formed with 'will be' + present participle (-ing form). It describes an action that will be in progress at a future time.",
    marks: 1,
  },
  {
    id: 20,
    subject: "English",
    topic: "Vocabulary",
    question: "Words that sound the same but have different meanings and spellings are called _____. (e.g., 'flour' and 'flower')",
    answer: "homophones",
    acceptedAnswers: ["homophones", "homophone", "a homophone"],
    explanation: "Homophones can cause confusion in writing. Understanding their meanings helps avoid errors. 'Homo' means same, 'phone' means sound.",
    marks: 1,
  },
  {
    id: 21,
    subject: "English",
    topic: "Grammar",
    question: "Transform into a question: 'They have completed the assignment.'",
    answer: "Have they completed the assignment?",
    acceptedAnswers: [
      "Have they completed the assignment?",
      "Have they completed the assignment",
    ],
    explanation: "To form a question from a statement with an auxiliary verb, invert the subject and the auxiliary verb. 'They have' becomes 'Have they'.",
    marks: 1,
  },
  {
    id: 22,
    subject: "English",
    topic: "Writing",
    question: "A type of essay that tells a story, usually from personal experience, with a beginning, middle, and end is called a _____ essay.",
    answer: "narrative",
    acceptedAnswers: ["narrative", "narrative essay", "a narrative essay", "a narrative"],
    explanation: "Narrative essays use descriptive language, dialogue, and a logical sequence of events. They often convey a lesson or moral through the story told.",
    marks: 1,
  },
  {
    id: 23,
    subject: "English",
    topic: "Literature",
    question: "The time and place where a story takes place is called the _____.",
    answer: "setting",
    acceptedAnswers: ["setting", "the setting"],
    explanation: "The setting helps establish the mood, provides context, and influences the characters' behavior and the plot's development.",
    marks: 1,
  },
  {
    id: 24,
    subject: "English",
    topic: "Grammar",
    question: "Join using 'although': 'It was raining. We went to school.'",
    answer: "Although it was raining, we went to school.",
    acceptedAnswers: [
      "Although it was raining, we went to school.",
      "Although it was raining, we went to school",
      "Although it was raining we went to school.",
      "Although it was raining we went to school",
      "We went to school although it was raining.",
      "We went to school although it was raining",
      "We went to school, although it was raining.",
      "We went to school, although it was raining",
    ],
    explanation: "'Although' is a subordinating conjunction used to show contrast. It introduces a dependent clause that contrasts with the main clause.",
    marks: 1,
  },
  {
    id: 25,
    subject: "English",
    topic: "Vocabulary",
    question: "What does the prefix 'un-' mean? (One word)",
    answer: "not",
    acceptedAnswers: ["not", "opposite", "opposite of", "not or opposite of"],
    explanation: "Prefixes are added to the beginning of words to change their meaning. 'Un-' is one of the most common English prefixes, creating negative or opposite meanings (e.g., unhappy, unable, unkind).",
    marks: 1,
  },
  {
    id: 26,
    subject: "English",
    topic: "Comprehension",
    question: "Which reading technique involves looking quickly through a text to find specific information — skimming or scanning?",
    answer: "scanning",
    acceptedAnswers: ["scanning"],
    explanation: "Skimming is reading quickly to get the general idea. Scanning is looking quickly through a text to find specific information like names, dates, or keywords.",
    marks: 1,
  },
  {
    id: 27,
    subject: "English",
    topic: "Grammar",
    question: "Give the comparative form of the adjective 'beautiful'.",
    answer: "more beautiful",
    acceptedAnswers: ["more beautiful"],
    explanation: "Longer adjectives (usually 3+ syllables) form comparatives with 'more' rather than adding '-er'. The superlative form is 'most beautiful'.",
    marks: 1,
  },
  {
    id: 28,
    subject: "English",
    topic: "Literature",
    question: "What figure of speech involves words that imitate natural sounds? (e.g., 'buzz', 'splash', 'hiss')",
    answer: "onomatopoeia",
    acceptedAnswers: ["onomatopoeia", "onomatopeia"],
    explanation: "Onomatopoeia makes writing more vivid and sensory by using words whose pronunciation suggests their meaning. It's common in poetry and descriptive prose.",
    marks: 1,
  },
  {
    id: 29,
    subject: "English",
    topic: "Grammar",
    question: "Rewrite using the correct form: 'If I was you, I would study harder.'",
    answer: "If I were you, I would study harder.",
    acceptedAnswers: [
      "If I were you, I would study harder.",
      "If I were you, I would study harder",
      "If I were you I would study harder.",
      "If I were you I would study harder",
    ],
    explanation: "This is a conditional sentence expressing an unreal/hypothetical situation. The subjunctive mood requires 'were' instead of 'was' for all subjects.",
    marks: 1,
  },
  {
    id: 30,
    subject: "English",
    topic: "Grammar",
    question: "What type of conjunction is 'although' — coordinating, subordinating, or correlative?",
    answer: "subordinating",
    acceptedAnswers: ["subordinating", "subordinating conjunction", "a subordinating conjunction"],
    explanation: "Subordinating conjunctions (because, although, when) join dependent to independent clauses. Coordinating (and, but, or) join equal elements. Correlative (either...or, neither...nor) work in pairs.",
    marks: 1,
  },
];

export default grade9English;
