import type { Grade9Question } from "@/types";

const grade9Geography: Grade9Question[] = [
  {
    id: 1,
    subject: "Geography",
    topic: "Map Reading",
    question: "Which is drawn on a larger scale showing more detail: a map or a plan?",
    answer: "plan",
    acceptedAnswers: ["plan", "a plan"],
    explanation: "A map represents a large area on a small scale, while a plan represents a small area on a large scale.",
    marks: 1,
  },
  {
    id: 2,
    subject: "Geography",
    topic: "Weather",
    question: "What is the term for the average weather conditions of a place over a long period (usually 30+ years)?",
    answer: "climate",
    acceptedAnswers: ["climate"],
    explanation: "Weather changes daily; climate is stable. Climate determines vegetation and agriculture.",
    marks: 1,
  },
  {
    id: 3,
    subject: "Geography",
    topic: "Physical Geography",
    question: "What is the lowest layer of Earth's atmosphere, where weather occurs?",
    answer: "troposphere",
    acceptedAnswers: ["troposphere", "the troposphere"],
    explanation: "The layers from the surface are Troposphere, Stratosphere, Mesosphere, Thermosphere.",
    marks: 1,
  },
  {
    id: 4,
    subject: "Geography",
    topic: "Plate Tectonics",
    question: "What is the point on the Earth's surface directly above the underground focus of an earthquake?",
    answer: "epicenter",
    acceptedAnswers: ["epicenter", "the epicenter", "epicentre"],
    explanation: "Earthquakes are caused by sudden releases of energy from tectonic plate collision.",
    marks: 1,
  },
  {
    id: 5,
    subject: "Geography",
    topic: "Rivers",
    question: "Name a feature formed by river erosion that has steep sides shaped like a letter of the alphabet.",
    answer: "v-shaped valley",
    acceptedAnswers: ["v-shaped valley", "v shaped valley", "v-shaped valleys"],
    explanation: "Rivers erode through hydraulic action, abrasion, attrition, and solution. Gorges and waterfalls are also erosional.",
    marks: 1,
  },
  {
    id: 6,
    subject: "Geography",
    topic: "Population",
    question: "What measurement is calculated by dividing total population by total land area?",
    answer: "population density",
    acceptedAnswers: ["population density", "density"],
    explanation: "It represents the number of people living per unit area of land, usually per km².",
    marks: 1,
  },
  {
    id: 7,
    subject: "Geography",
    topic: "Vegetation",
    question: "What dense forest biome is found near the equator with high rainfall and tall canopy trees?",
    answer: "tropical rainforest",
    acceptedAnswers: ["tropical rainforest", "rainforest"],
    explanation: "These forests have a hot and wet climate year-round and high biodiversity.",
    marks: 1,
  },
  {
    id: 8,
    subject: "Geography",
    topic: "Map Reading",
    question: "On a compass, what is the bearing in degrees for East?",
    answer: "90",
    acceptedAnswers: ["90", "90 degrees", "090", "090 degrees", "90°", "090°"],
    explanation: "Bearings are measured clockwise from north (0°/360°). East = 090°, South = 180°, West = 270°.",
    marks: 1,
  },
  {
    id: 9,
    subject: "Geography",
    topic: "Climate",
    question: "What is the gradual increase in the Earth's average temperature called?",
    answer: "global warming",
    acceptedAnswers: ["global warming", "climate change"],
    explanation: "It is caused by deforestation and the burning of fossil fuels that increase greenhouse gases.",
    marks: 1,
  },
  {
    id: 10,
    subject: "Geography",
    topic: "Physical Geography",
    question: "In the water cycle, what is the process where water vapor cools and forms clouds?",
    answer: "condensation",
    acceptedAnswers: ["condensation"],
    explanation: "The other main steps are evaporation, precipitation, and collection.",
    marks: 1,
  },
  {
    id: 11,
    subject: "Geography",
    topic: "Soils",
    question: "Which type of soil is a mixture of sand, silt, and clay, and is considered the best for farming?",
    answer: "loam",
    acceptedAnswers: ["loam", "loam soil", "loamy", "loamy soil"],
    explanation: "Loam retains moisture while also draining well. Sandy soil drains too quickly, and clay retains too much water.",
    marks: 1,
  },
  {
    id: 12,
    subject: "Geography",
    topic: "Rivers",
    question: "What landform is created at the mouth of a river when it deposits sediment as it enters the sea?",
    answer: "delta",
    acceptedAnswers: ["delta", "a delta"],
    explanation: "Deposition occurs when a river loses energy. Floodplains and meanders are also associated with river deposition.",
    marks: 1,
  },
  {
    id: 13,
    subject: "Geography",
    topic: "Population",
    question: "Does flat land and fertile soil lead to high or low population density?",
    answer: "high",
    acceptedAnswers: ["high", "high population density", "higher"],
    explanation: "Favorable conditions attract settlement, while harsh environments are sparsely populated.",
    marks: 1,
  },
  {
    id: 14,
    subject: "Geography",
    topic: "Plate Tectonics",
    question: "What is an opening in the Earth's crust through which molten rock, ash, and gases erupt?",
    answer: "volcano",
    acceptedAnswers: ["volcano", "a volcano"],
    explanation: "Mt. Longonot is an active volcano in Kenya. Kenya is in the volcanic Great Rift Valley.",
    marks: 1,
  },
  {
    id: 15,
    subject: "Geography",
    topic: "Map Reading",
    question: "What is a line on a map joining points of equal altitude/elevation above sea level?",
    answer: "contour line",
    acceptedAnswers: ["contour line", "contour", "contours", "contour lines"],
    explanation: "Closely spaced lines indicate steep slopes; widely spaced lines indicate gentle slopes.",
    marks: 1,
  },
  {
    id: 16,
    subject: "Geography",
    topic: "Weather",
    question: "Which instrument is used to measure wind speed?",
    answer: "anemometer",
    acceptedAnswers: ["anemometer", "an anemometer"],
    explanation: "Thermophones measure temperature, rain gauges measure rainfall, and barometers measure atmospheric pressure.",
    marks: 1,
  },
  {
    id: 17,
    subject: "Geography",
    topic: "Agriculture",
    question: "What is the term for the artificial application of water to land for agriculture?",
    answer: "irrigation",
    acceptedAnswers: ["irrigation"],
    explanation: "Methods include drip, sprinkler, furrow, and basin irrigation.",
    marks: 1,
  },
  {
    id: 18,
    subject: "Geography",
    topic: "Physical Geography",
    question: "What major physical feature of East Africa is a series of trenches formed by faulting/tensional forces?",
    answer: "great rift valley",
    acceptedAnswers: ["great rift valley", "rift valley", "the great rift valley", "the rift valley"],
    explanation: "It stretches from Lebanon to Mozambique and contains lakes like Nakuru and Turkana.",
    marks: 1,
  },
  {
    id: 19,
    subject: "Geography",
    topic: "Climate",
    question: "Climatic zones are mainly determined by the distance from the equator. What is this distance called?",
    answer: "latitude",
    acceptedAnswers: ["latitude"],
    explanation: "Latitude affects the amount of solar energy received. Other factors include altitude and distance from the sea.",
    marks: 1,
  },
  {
    id: 20,
    subject: "Geography",
    topic: "Resources",
    question: "Resources that are finite and cannot be replaced once used (like oil or coal) are called _____ resources.",
    answer: "non-renewable",
    acceptedAnswers: ["non-renewable", "non renewable", "nonrenewable"],
    explanation: "Renewable resources, like solar energy and forests, can be replenished naturally.",
    marks: 1,
  },
  {
    id: 21,
    subject: "Geography",
    topic: "Vegetation",
    question: "What is the process by which fertile land becomes desert, often due to overgrazing or climate change?",
    answer: "desertification",
    acceptedAnswers: ["desertification"],
    explanation: "The Sahel region of Africa is particularly affected by this phenomenon.",
    marks: 1,
  },
  {
    id: 22,
    subject: "Geography",
    topic: "Map Reading",
    question: "If the map scale is 1:50,000, what actual ground distance (in kilometers) does 2 cm on the map represent?",
    answer: "1",
    acceptedAnswers: ["1", "1km", "1 km", "one", "one km", "one kilometer"],
    explanation: "Scale 1:50,000 means 1 cm = 50,000 cm = 0.5 km. Therefore, 2 cm = 2 × 0.5 km = 1 km.",
    marks: 2,
  },
  {
    id: 23,
    subject: "Geography",
    topic: "Weather",
    question: "What type of rainfall is formed when moist air is forced to rise over a mountain?",
    answer: "relief",
    acceptedAnswers: ["relief", "relief rainfall", "orographic", "orographic rainfall"],
    explanation: "The windward side receives rain, while the leeward side becomes a dry 'rain shadow'.",
    marks: 1,
  },
  {
    id: 24,
    subject: "Geography",
    topic: "Rivers",
    question: "What is the area of land drained by a river and its tributaries called?",
    answer: "drainage basin",
    acceptedAnswers: ["drainage basin", "a drainage basin", "catchment area", "river basin"],
    explanation: "Its boundary is the higher ground called a watershed.",
    marks: 1,
  },
  {
    id: 25,
    subject: "Geography",
    topic: "Population",
    question: "What is the term for the increase in the proportion of people living in urban areas (cities)?",
    answer: "urbanization",
    acceptedAnswers: ["urbanization", "urbanisation"],
    explanation: "It is driven by rural-urban migration and can cause overcrowding and slums.",
    marks: 1,
  },
  {
    id: 26,
    subject: "Geography",
    topic: "Physical Geography",
    question: "What type of rock is formed from the cooling and solidification of magma or lava (e.g., granite)?",
    answer: "igneous",
    acceptedAnswers: ["igneous", "igneous rock", "igneous rocks"],
    explanation: "Other types are sedimentary (deposited sediments) and metamorphic (changed by heat/pressure).",
    marks: 1,
  },
  {
    id: 27,
    subject: "Geography",
    topic: "Agriculture",
    question: "Growing different crops in the same field in successive seasons to prevent soil exhaustion is called crop _____.",
    answer: "rotation",
    acceptedAnswers: ["rotation", "crop rotation"],
    explanation: "Legumes in the rotation fix nitrogen, improving soil fertility.",
    marks: 1,
  },
  {
    id: 28,
    subject: "Geography",
    topic: "Resources",
    question: "What is the extraction of valuable minerals or geological materials from the earth called?",
    answer: "mining",
    acceptedAnswers: ["mining"],
    explanation: "An important economic activity that can cause environmental damage if not managed.",
    marks: 1,
  },
  {
    id: 29,
    subject: "Geography",
    topic: "Climate",
    question: "What is the imaginary line at 0° latitude dividing the Earth into Northern and Southern hemispheres?",
    answer: "equator",
    acceptedAnswers: ["equator", "the equator"],
    explanation: "Areas near the equator receive direct sunlight, causing high temperatures year-round.",
    marks: 1,
  },
  {
    id: 30,
    subject: "Geography",
    topic: "Soils",
    question: "Terracing and planting cover crops are methods to prevent soil _____.",
    answer: "erosion",
    acceptedAnswers: ["erosion", "soil erosion"],
    explanation: "Soil erosion is the removal of topsoil by wind or water. Prevention maintains agricultural productivity.",
    marks: 1,
  },
];

export default grade9Geography;
